#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Fri Dec 05 23:16:43 PST 2025
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 4543fd3c92a64e3580def2dfa30e86a2 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot dual_weight_fifo_tb_behav xil_defaultlib.dual_weight_fifo_tb xil_defaultlib.glbl -log elaborate.log"
xelab -wto 4543fd3c92a64e3580def2dfa30e86a2 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot dual_weight_fifo_tb_behav xil_defaultlib.dual_weight_fifo_tb xil_defaultlib.glbl -log elaborate.log

