#!/usr/bin/env tclsh
# Yosys/nextpnr build script for TinyTinyTPU
# Alternative open-source toolchain for FPGA synthesis

set script_dir [file dirname [file normalize [info script]]]
set rtl_dir [file normalize "$script_dir/../rtl"]
set project_name "tinytinyTPU_basys3"
set fpga_part "xc7a35tcpg236-1"

puts "=========================================="
puts "Yosys/nextpnr Build Script"
puts "=========================================="
puts "Project: $project_name"
puts "FPGA Part: $fpga_part"
puts ""

# Check if Yosys is available
if {[catch {exec yosys -V} version]} {
    puts "ERROR: Yosys not found. Please install Yosys:"
    puts "  Ubuntu/Debian: sudo apt-get install yosys"
    puts "  macOS: brew install yosys"
    exit 1
}
puts "Found Yosys: $version"

# Create Yosys synthesis script
set yosys_script "$script_dir/synth_yosys.ys"
set yosys_fd [open $yosys_script w]

puts $yosys_fd "# Yosys synthesis script for TinyTinyTPU"
puts $yosys_fd "# Auto-generated by build_yosys.tcl"
puts $yosys_fd ""

# Read all RTL files
puts $yosys_fd "# Read SystemVerilog RTL files"
puts $yosys_fd "read_verilog -sv $rtl_dir/pe.sv"
puts $yosys_fd "read_verilog -sv $rtl_dir/mmu.sv"
puts $yosys_fd "read_verilog -sv $rtl_dir/weight_fifo.sv"
puts $yosys_fd "read_verilog -sv $rtl_dir/dual_weight_fifo.sv"
puts $yosys_fd "read_verilog -sv $rtl_dir/accumulator_align.sv"
puts $yosys_fd "read_verilog -sv $rtl_dir/accumulator_mem.sv"
puts $yosys_fd "read_verilog -sv $rtl_dir/accumulator.sv"
puts $yosys_fd "read_verilog -sv $rtl_dir/activation_func.sv"
puts $yosys_fd "read_verilog -sv $rtl_dir/normalizer.sv"
puts $yosys_fd "read_verilog -sv $rtl_dir/loss_block.sv"
puts $yosys_fd "read_verilog -sv $rtl_dir/activation_pipeline.sv"
puts $yosys_fd "read_verilog -sv $rtl_dir/unified_buffer.sv"
puts $yosys_fd "read_verilog -sv $rtl_dir/mlp_top.sv"
puts $yosys_fd "read_verilog -sv $rtl_dir/uart_rx.sv"
puts $yosys_fd "read_verilog -sv $rtl_dir/uart_tx.sv"
puts $yosys_fd "read_verilog -sv $rtl_dir/uart_controller.sv"
puts $yosys_fd "read_verilog -sv $rtl_dir/tpu_bridge.sv"
puts $yosys_fd "read_verilog -sv $rtl_dir/tpu_top.sv"
puts $yosys_fd "read_verilog -sv $script_dir/basys3_top.sv"
puts $yosys_fd ""

puts $yosys_fd "# Set top module"
puts $yosys_fd "hierarchy -top basys3_top"
puts $yosys_fd ""

puts $yosys_fd "# Synthesize for Xilinx 7-series"
puts $yosys_fd "synth_xilinx -top basys3_top -family xc7"
puts $yosys_fd ""

puts $yosys_fd "# Write output files"
puts $yosys_fd "write_verilog $script_dir/basys3_top_yosys.v"
puts $yosys_fd "write_json $script_dir/basys3_top.json"
puts $yosys_fd "write_edif $script_dir/basys3_top.edif"
puts $yosys_fd ""

puts $yosys_fd "# Statistics"
puts $yosys_fd "stat"

close $yosys_fd

puts "Generated Yosys script: $yosys_script"
puts ""
puts "Running Yosys synthesis..."
puts "=========================================="

# Run Yosys
if {[catch {exec yosys $yosys_script} result]} {
    puts "ERROR: Yosys synthesis failed!"
    puts $result
    exit 1
}

puts $result
puts ""
puts "=========================================="
puts "Yosys synthesis completed"
puts ""

# Check if nextpnr is available
if {[catch {exec nextpnr-xilinx --version} version]} {
    puts "WARNING: nextpnr-xilinx not found."
    puts "Synthesis complete, but place & route requires nextpnr."
    puts ""
    puts "To install nextpnr:"
    puts "  git clone https://github.com/YosysHQ/nextpnr.git"
    puts "  cd nextpnr && cmake . -DARCH=xilinx && make -j\$(nproc)"
    puts ""
    puts "Output files:"
    puts "  - Netlist: basys3_top_yosys.v"
    puts "  - JSON: basys3_top.json"
    puts "  - EDIF: basys3_top.edif"
    exit 0
}

puts "Found nextpnr-xilinx: $version"
puts ""
puts "Running nextpnr place & route..."
puts "=========================================="

# Run nextpnr
set xdc_file "$script_dir/basys3.xdc"
set json_file "$script_dir/basys3_top.json"
set fasm_file "$script_dir/basys3_top.fasm"

if {[catch {exec nextpnr-xilinx \
    --xdc $xdc_file \
    --json $json_file \
    --write $script_dir/basys3_top_routed.json \
    --fasm $fasm_file \
    2>&1} result]} {
    puts "WARNING: nextpnr place & route had issues:"
    puts $result
    puts ""
    puts "Note: nextpnr may have limitations compared to Vivado."
    puts "For production builds, use Vivado (build_vivado.tcl)."
    exit 1
}

puts $result
puts ""
puts "=========================================="
puts "nextpnr place & route completed"
puts ""
puts "Output files:"
puts "  - FASM: $fasm_file"
puts "  - Routed JSON: $script_dir/basys3_top_routed.json"
puts ""
puts "NOTE: Converting FASM to bitstream requires additional tools."
puts "      For now, use Vivado for complete bitstream generation."
puts "=========================================="

