// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Symbol table implementation internals

#include "Vtop__pch.h"
#include "Vtop.h"
#include "Vtop___024root.h"

// FUNCTIONS
Vtop__Syms::~Vtop__Syms()
{

    // Tear down scope hierarchy
    __Vhier.remove(0, &__Vscope_mlp_top);
    __Vhier.remove(&__Vscope_mlp_top, &__Vscope_mlp_top__accum_u);
    __Vhier.remove(&__Vscope_mlp_top, &__Vscope_mlp_top__ap_col0);
    __Vhier.remove(&__Vscope_mlp_top, &__Vscope_mlp_top__ap_col1);
    __Vhier.remove(&__Vscope_mlp_top, &__Vscope_mlp_top__mmu_u);
    __Vhier.remove(&__Vscope_mlp_top, &__Vscope_mlp_top__ub_a);
    __Vhier.remove(&__Vscope_mlp_top, &__Vscope_mlp_top__ub_b);
    __Vhier.remove(&__Vscope_mlp_top, &__Vscope_mlp_top__weight_fifo_u);
    __Vhier.remove(&__Vscope_mlp_top__accum_u, &__Vscope_mlp_top__accum_u__u_align);
    __Vhier.remove(&__Vscope_mlp_top__accum_u, &__Vscope_mlp_top__accum_u__u_mem);
    __Vhier.remove(&__Vscope_mlp_top__ap_col0, &__Vscope_mlp_top__ap_col0__act_u);
    __Vhier.remove(&__Vscope_mlp_top__ap_col0, &__Vscope_mlp_top__ap_col0__loss_u);
    __Vhier.remove(&__Vscope_mlp_top__ap_col0, &__Vscope_mlp_top__ap_col0__norm_u);
    __Vhier.remove(&__Vscope_mlp_top__ap_col0, &__Vscope_mlp_top__ap_col0__unnamedblk1);
    __Vhier.remove(&__Vscope_mlp_top__ap_col1, &__Vscope_mlp_top__ap_col1__act_u);
    __Vhier.remove(&__Vscope_mlp_top__ap_col1, &__Vscope_mlp_top__ap_col1__loss_u);
    __Vhier.remove(&__Vscope_mlp_top__ap_col1, &__Vscope_mlp_top__ap_col1__norm_u);
    __Vhier.remove(&__Vscope_mlp_top__ap_col1, &__Vscope_mlp_top__ap_col1__unnamedblk1);
    __Vhier.remove(&__Vscope_mlp_top__mmu_u, &__Vscope_mlp_top__mmu_u__pe00);
    __Vhier.remove(&__Vscope_mlp_top__mmu_u, &__Vscope_mlp_top__mmu_u__pe01);
    __Vhier.remove(&__Vscope_mlp_top__mmu_u, &__Vscope_mlp_top__mmu_u__pe10);
    __Vhier.remove(&__Vscope_mlp_top__mmu_u, &__Vscope_mlp_top__mmu_u__pe11);

}

Vtop__Syms::Vtop__Syms(VerilatedContext* contextp, const char* namep, Vtop* modelp)
    : VerilatedSyms{contextp}
    // Setup internal state of the Syms class
    , __Vm_modelp{modelp}
    // Setup module instances
    , TOP{this, namep}
{
    // Check resources
    Verilated::stackCheck(370);
    // Configure time unit / time precision
    _vm_contextp__->timeunit(-9);
    _vm_contextp__->timeprecision(-12);
    // Setup each module's pointers to their submodules
    // Setup each module's pointer back to symbol table (for public functions)
    TOP.__Vconfigure(true);
    // Setup scopes
    __Vscope_TOP.configure(this, name(), "TOP", "TOP", "<null>", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_mlp_top.configure(this, name(), "mlp_top", "mlp_top", "mlp_top", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_mlp_top__accum_u.configure(this, name(), "mlp_top.accum_u", "accum_u", "accumulator", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_mlp_top__accum_u__u_align.configure(this, name(), "mlp_top.accum_u.u_align", "u_align", "accumulator_align", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_mlp_top__accum_u__u_mem.configure(this, name(), "mlp_top.accum_u.u_mem", "u_mem", "accumulator_mem", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_mlp_top__ap_col0.configure(this, name(), "mlp_top.ap_col0", "ap_col0", "activation_pipeline", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_mlp_top__ap_col0__act_u.configure(this, name(), "mlp_top.ap_col0.act_u", "act_u", "activation_func", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_mlp_top__ap_col0__loss_u.configure(this, name(), "mlp_top.ap_col0.loss_u", "loss_u", "loss_block", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_mlp_top__ap_col0__norm_u.configure(this, name(), "mlp_top.ap_col0.norm_u", "norm_u", "normalizer", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_mlp_top__ap_col0__unnamedblk1.configure(this, name(), "mlp_top.ap_col0.unnamedblk1", "unnamedblk1", "<null>", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_mlp_top__ap_col1.configure(this, name(), "mlp_top.ap_col1", "ap_col1", "activation_pipeline", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_mlp_top__ap_col1__act_u.configure(this, name(), "mlp_top.ap_col1.act_u", "act_u", "activation_func", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_mlp_top__ap_col1__loss_u.configure(this, name(), "mlp_top.ap_col1.loss_u", "loss_u", "loss_block", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_mlp_top__ap_col1__norm_u.configure(this, name(), "mlp_top.ap_col1.norm_u", "norm_u", "normalizer", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_mlp_top__ap_col1__unnamedblk1.configure(this, name(), "mlp_top.ap_col1.unnamedblk1", "unnamedblk1", "<null>", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_mlp_top__mmu_u.configure(this, name(), "mlp_top.mmu_u", "mmu_u", "mmu", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_mlp_top__mmu_u__pe00.configure(this, name(), "mlp_top.mmu_u.pe00", "pe00", "pe", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_mlp_top__mmu_u__pe01.configure(this, name(), "mlp_top.mmu_u.pe01", "pe01", "pe", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_mlp_top__mmu_u__pe10.configure(this, name(), "mlp_top.mmu_u.pe10", "pe10", "pe", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_mlp_top__mmu_u__pe11.configure(this, name(), "mlp_top.mmu_u.pe11", "pe11", "pe", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_mlp_top__ub_a.configure(this, name(), "mlp_top.ub_a", "ub_a", "unified_buffer", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_mlp_top__ub_b.configure(this, name(), "mlp_top.ub_b", "ub_b", "unified_buffer", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_mlp_top__weight_fifo_u.configure(this, name(), "mlp_top.weight_fifo_u", "weight_fifo_u", "dual_weight_fifo", -9, VerilatedScope::SCOPE_MODULE);

    // Set up scope hierarchy
    __Vhier.add(0, &__Vscope_mlp_top);
    __Vhier.add(&__Vscope_mlp_top, &__Vscope_mlp_top__accum_u);
    __Vhier.add(&__Vscope_mlp_top, &__Vscope_mlp_top__ap_col0);
    __Vhier.add(&__Vscope_mlp_top, &__Vscope_mlp_top__ap_col1);
    __Vhier.add(&__Vscope_mlp_top, &__Vscope_mlp_top__mmu_u);
    __Vhier.add(&__Vscope_mlp_top, &__Vscope_mlp_top__ub_a);
    __Vhier.add(&__Vscope_mlp_top, &__Vscope_mlp_top__ub_b);
    __Vhier.add(&__Vscope_mlp_top, &__Vscope_mlp_top__weight_fifo_u);
    __Vhier.add(&__Vscope_mlp_top__accum_u, &__Vscope_mlp_top__accum_u__u_align);
    __Vhier.add(&__Vscope_mlp_top__accum_u, &__Vscope_mlp_top__accum_u__u_mem);
    __Vhier.add(&__Vscope_mlp_top__ap_col0, &__Vscope_mlp_top__ap_col0__act_u);
    __Vhier.add(&__Vscope_mlp_top__ap_col0, &__Vscope_mlp_top__ap_col0__loss_u);
    __Vhier.add(&__Vscope_mlp_top__ap_col0, &__Vscope_mlp_top__ap_col0__norm_u);
    __Vhier.add(&__Vscope_mlp_top__ap_col0, &__Vscope_mlp_top__ap_col0__unnamedblk1);
    __Vhier.add(&__Vscope_mlp_top__ap_col1, &__Vscope_mlp_top__ap_col1__act_u);
    __Vhier.add(&__Vscope_mlp_top__ap_col1, &__Vscope_mlp_top__ap_col1__loss_u);
    __Vhier.add(&__Vscope_mlp_top__ap_col1, &__Vscope_mlp_top__ap_col1__norm_u);
    __Vhier.add(&__Vscope_mlp_top__ap_col1, &__Vscope_mlp_top__ap_col1__unnamedblk1);
    __Vhier.add(&__Vscope_mlp_top__mmu_u, &__Vscope_mlp_top__mmu_u__pe00);
    __Vhier.add(&__Vscope_mlp_top__mmu_u, &__Vscope_mlp_top__mmu_u__pe01);
    __Vhier.add(&__Vscope_mlp_top__mmu_u, &__Vscope_mlp_top__mmu_u__pe10);
    __Vhier.add(&__Vscope_mlp_top__mmu_u, &__Vscope_mlp_top__mmu_u__pe11);

    // Setup export functions
    for (int __Vfinal = 0; __Vfinal < 2; ++__Vfinal) {
        __Vscope_TOP.varInsert(__Vfinal,"acc0", &(TOP.acc0), false, VLVT_UINT32,VLVD_OUT|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"acc1", &(TOP.acc1), false, VLVT_UINT32,VLVD_OUT|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"acc_valid", &(TOP.acc_valid), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"clk", &(TOP.clk), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"current_layer", &(TOP.current_layer), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_TOP.varInsert(__Vfinal,"cycle_cnt", &(TOP.cycle_cnt), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_TOP.varInsert(__Vfinal,"init_act_data", &(TOP.init_act_data), false, VLVT_UINT16,VLVD_IN|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_TOP.varInsert(__Vfinal,"init_act_valid", &(TOP.init_act_valid), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"layer_complete", &(TOP.layer_complete), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"mmu_acc0_out", &(TOP.mmu_acc0_out), false, VLVT_UINT16,VLVD_OUT|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_TOP.varInsert(__Vfinal,"mmu_acc1_out", &(TOP.mmu_acc1_out), false, VLVT_UINT16,VLVD_OUT|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_TOP.varInsert(__Vfinal,"norm_bias", &(TOP.norm_bias), false, VLVT_UINT32,VLVD_IN|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"norm_gain", &(TOP.norm_gain), false, VLVT_UINT16,VLVD_IN|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_TOP.varInsert(__Vfinal,"norm_shift", &(TOP.norm_shift), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_TOP.varInsert(__Vfinal,"q_inv_scale", &(TOP.q_inv_scale), false, VLVT_UINT16,VLVD_IN|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_TOP.varInsert(__Vfinal,"q_zero_point", &(TOP.q_zero_point), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_TOP.varInsert(__Vfinal,"reset", &(TOP.reset), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"start_mlp", &(TOP.start_mlp), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"state", &(TOP.state), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_TOP.varInsert(__Vfinal,"weights_ready", &(TOP.weights_ready), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"wf_data_in", &(TOP.wf_data_in), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_TOP.varInsert(__Vfinal,"wf_push_col0", &(TOP.wf_push_col0), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"wf_push_col1", &(TOP.wf_push_col1), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"wf_reset", &(TOP.wf_reset), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"COMPUTE", const_cast<void*>(static_cast<const void*>(&(TOP.mlp_top__DOT__COMPUTE))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"DONE", const_cast<void*>(static_cast<const void*>(&(TOP.mlp_top__DOT__DONE))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"DRAIN", const_cast<void*>(static_cast<const void*>(&(TOP.mlp_top__DOT__DRAIN))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"IDLE", const_cast<void*>(static_cast<const void*>(&(TOP.mlp_top__DOT__IDLE))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"LOAD_ACT", const_cast<void*>(static_cast<const void*>(&(TOP.mlp_top__DOT__LOAD_ACT))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"LOAD_WEIGHT", const_cast<void*>(static_cast<const void*>(&(TOP.mlp_top__DOT__LOAD_WEIGHT))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"NEXT_LAYER", const_cast<void*>(static_cast<const void*>(&(TOP.mlp_top__DOT__NEXT_LAYER))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"NUM_LAYERS", const_cast<void*>(static_cast<const void*>(&(TOP.mlp_top__DOT__NUM_LAYERS))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"TRANSFER", const_cast<void*>(static_cast<const void*>(&(TOP.mlp_top__DOT__TRANSFER))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"WAIT_WEIGHTS", const_cast<void*>(static_cast<const void*>(&(TOP.mlp_top__DOT__WAIT_WEIGHTS))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"acc0", &(TOP.mlp_top__DOT__acc0), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"acc1", &(TOP.mlp_top__DOT__acc1), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"acc_valid", &(TOP.mlp_top__DOT__acc_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"accum_en", &(TOP.mlp_top__DOT__accum_en), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"act_row0_data", &(TOP.mlp_top__DOT__act_row0_data), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"act_row1_data", &(TOP.mlp_top__DOT__act_row1_data), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"act_ub_empty", &(TOP.mlp_top__DOT__act_ub_empty), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"act_ub_rd_data", &(TOP.mlp_top__DOT__act_ub_rd_data), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"act_ub_rd_valid", &(TOP.mlp_top__DOT__act_ub_rd_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"addr_sel", &(TOP.mlp_top__DOT__addr_sel), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"ap_data_col0", &(TOP.mlp_top__DOT__ap_data_col0), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"ap_data_col1", &(TOP.mlp_top__DOT__ap_data_col1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"ap_valid", &(TOP.mlp_top__DOT__ap_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"buffer_select", &(TOP.mlp_top__DOT__buffer_select), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"clk", &(TOP.mlp_top__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"compute_phase", &(TOP.mlp_top__DOT__compute_phase), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"current_layer", &(TOP.mlp_top__DOT__current_layer), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"current_layer_reg", &(TOP.mlp_top__DOT__current_layer_reg), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"cycle_cnt", &(TOP.mlp_top__DOT__cycle_cnt), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"cycle_cnt_reg", &(TOP.mlp_top__DOT__cycle_cnt_reg), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"drain_phase", &(TOP.mlp_top__DOT__drain_phase), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"en_capture_col0", &(TOP.mlp_top__DOT__en_capture_col0), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"en_capture_col1", &(TOP.mlp_top__DOT__en_capture_col1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"en_load_weight", &(TOP.mlp_top__DOT__en_load_weight), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"init_act_data", &(TOP.mlp_top__DOT__init_act_data), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"init_act_valid", &(TOP.mlp_top__DOT__init_act_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"layer_complete", &(TOP.mlp_top__DOT__layer_complete), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"mmu_acc0_out", &(TOP.mlp_top__DOT__mmu_acc0_out), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"mmu_acc1_out", &(TOP.mlp_top__DOT__mmu_acc1_out), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"mmu_col0_in", &(TOP.mlp_top__DOT__mmu_col0_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"mmu_col1_in", &(TOP.mlp_top__DOT__mmu_col1_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"mmu_row0_in", &(TOP.mlp_top__DOT__mmu_row0_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"mmu_row1_in", &(TOP.mlp_top__DOT__mmu_row1_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"mmu_valid", &(TOP.mlp_top__DOT__mmu_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"norm_bias", &(TOP.mlp_top__DOT__norm_bias), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"norm_gain", &(TOP.mlp_top__DOT__norm_gain), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"norm_shift", &(TOP.mlp_top__DOT__norm_shift), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"q_inv_scale", &(TOP.mlp_top__DOT__q_inv_scale), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"q_zero_point", &(TOP.mlp_top__DOT__q_zero_point), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"refill_data", &(TOP.mlp_top__DOT__refill_data), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"refill_valid", &(TOP.mlp_top__DOT__refill_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"reset", &(TOP.mlp_top__DOT__reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"row1_skew_reg", &(TOP.mlp_top__DOT__row1_skew_reg), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"start_mlp", &(TOP.mlp_top__DOT__start_mlp), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"state", &(TOP.mlp_top__DOT__state), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"state_reg", &(TOP.mlp_top__DOT__state_reg), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"transfer_phase", &(TOP.mlp_top__DOT__transfer_phase), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"ub_a_empty", &(TOP.mlp_top__DOT__ub_a_empty), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"ub_a_rd_data", &(TOP.mlp_top__DOT__ub_a_rd_data), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"ub_a_rd_ready", &(TOP.mlp_top__DOT__ub_a_rd_ready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"ub_a_rd_valid", &(TOP.mlp_top__DOT__ub_a_rd_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"ub_a_wr_data", &(TOP.mlp_top__DOT__ub_a_wr_data), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"ub_a_wr_ready", &(TOP.mlp_top__DOT__ub_a_wr_ready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"ub_a_wr_valid", &(TOP.mlp_top__DOT__ub_a_wr_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"ub_b_empty", &(TOP.mlp_top__DOT__ub_b_empty), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"ub_b_rd_data", &(TOP.mlp_top__DOT__ub_b_rd_data), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"ub_b_rd_ready", &(TOP.mlp_top__DOT__ub_b_rd_ready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"ub_b_rd_valid", &(TOP.mlp_top__DOT__ub_b_rd_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"ub_b_wr_data", &(TOP.mlp_top__DOT__ub_b_wr_data), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"ub_b_wr_ready", &(TOP.mlp_top__DOT__ub_b_wr_ready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"ub_b_wr_valid", &(TOP.mlp_top__DOT__ub_b_wr_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"weights_loaded", &(TOP.mlp_top__DOT__weights_loaded), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"weights_ready", &(TOP.mlp_top__DOT__weights_ready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"wf_col0_out", &(TOP.mlp_top__DOT__wf_col0_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"wf_col1_out", &(TOP.mlp_top__DOT__wf_col1_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"wf_col1_raw", &(TOP.mlp_top__DOT__wf_col1_raw), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"wf_data_in", &(TOP.mlp_top__DOT__wf_data_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"wf_push_col0", &(TOP.mlp_top__DOT__wf_push_col0), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"wf_push_col1", &(TOP.mlp_top__DOT__wf_push_col1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top.varInsert(__Vfinal,"wf_reset", &(TOP.mlp_top__DOT__wf_reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__accum_u.varInsert(__Vfinal,"acc_col0_out", &(TOP.mlp_top__DOT__accum_u__DOT__acc_col0_out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_mlp_top__accum_u.varInsert(__Vfinal,"acc_col1_out", &(TOP.mlp_top__DOT__accum_u__DOT__acc_col1_out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_mlp_top__accum_u.varInsert(__Vfinal,"accumulator_enable", &(TOP.mlp_top__DOT__accum_u__DOT__accumulator_enable), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__accum_u.varInsert(__Vfinal,"addr_sel", &(TOP.mlp_top__DOT__accum_u__DOT__addr_sel), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__accum_u.varInsert(__Vfinal,"aligned_c0", &(TOP.mlp_top__DOT__accum_u__DOT__aligned_c0), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_mlp_top__accum_u.varInsert(__Vfinal,"aligned_c1", &(TOP.mlp_top__DOT__accum_u__DOT__aligned_c1), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_mlp_top__accum_u.varInsert(__Vfinal,"aligned_valid", &(TOP.mlp_top__DOT__accum_u__DOT__aligned_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__accum_u.varInsert(__Vfinal,"clk", &(TOP.mlp_top__DOT__accum_u__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__accum_u.varInsert(__Vfinal,"mmu_col0_in", &(TOP.mlp_top__DOT__accum_u__DOT__mmu_col0_in), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_mlp_top__accum_u.varInsert(__Vfinal,"mmu_col1_in", &(TOP.mlp_top__DOT__accum_u__DOT__mmu_col1_in), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_mlp_top__accum_u.varInsert(__Vfinal,"reset", &(TOP.mlp_top__DOT__accum_u__DOT__reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__accum_u.varInsert(__Vfinal,"valid_in", &(TOP.mlp_top__DOT__accum_u__DOT__valid_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__accum_u.varInsert(__Vfinal,"valid_out", &(TOP.mlp_top__DOT__accum_u__DOT__valid_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__accum_u__u_align.varInsert(__Vfinal,"align_col0", &(TOP.mlp_top__DOT__accum_u__DOT__u_align__DOT__align_col0), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_mlp_top__accum_u__u_align.varInsert(__Vfinal,"align_col1", &(TOP.mlp_top__DOT__accum_u__DOT__u_align__DOT__align_col1), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_mlp_top__accum_u__u_align.varInsert(__Vfinal,"aligned_valid", &(TOP.mlp_top__DOT__accum_u__DOT__u_align__DOT__aligned_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__accum_u__u_align.varInsert(__Vfinal,"clk", &(TOP.mlp_top__DOT__accum_u__DOT__u_align__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__accum_u__u_align.varInsert(__Vfinal,"col0_delay_reg", &(TOP.mlp_top__DOT__accum_u__DOT__u_align__DOT__col0_delay_reg), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_mlp_top__accum_u__u_align.varInsert(__Vfinal,"pending", &(TOP.mlp_top__DOT__accum_u__DOT__u_align__DOT__pending), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__accum_u__u_align.varInsert(__Vfinal,"raw_col0", &(TOP.mlp_top__DOT__accum_u__DOT__u_align__DOT__raw_col0), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_mlp_top__accum_u__u_align.varInsert(__Vfinal,"raw_col1", &(TOP.mlp_top__DOT__accum_u__DOT__u_align__DOT__raw_col1), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_mlp_top__accum_u__u_align.varInsert(__Vfinal,"reset", &(TOP.mlp_top__DOT__accum_u__DOT__u_align__DOT__reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__accum_u__u_align.varInsert(__Vfinal,"valid_in", &(TOP.mlp_top__DOT__accum_u__DOT__u_align__DOT__valid_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__accum_u__u_mem.varInsert(__Vfinal,"BYPASS_READ_NEW", const_cast<void*>(static_cast<const void*>(&(TOP.mlp_top__DOT__accum_u__DOT__u_mem__DOT__BYPASS_READ_NEW))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,0);
        __Vscope_mlp_top__accum_u__u_mem.varInsert(__Vfinal,"accumulator_mode", &(TOP.mlp_top__DOT__accum_u__DOT__u_mem__DOT__accumulator_mode), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__accum_u__u_mem.varInsert(__Vfinal,"buffer_select", &(TOP.mlp_top__DOT__accum_u__DOT__u_mem__DOT__buffer_select), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__accum_u__u_mem.varInsert(__Vfinal,"clk", &(TOP.mlp_top__DOT__accum_u__DOT__u_mem__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__accum_u__u_mem.varInsert(__Vfinal,"enable", &(TOP.mlp_top__DOT__accum_u__DOT__u_mem__DOT__enable), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__accum_u__u_mem.varInsert(__Vfinal,"in_col0", &(TOP.mlp_top__DOT__accum_u__DOT__u_mem__DOT__in_col0), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_mlp_top__accum_u__u_mem.varInsert(__Vfinal,"in_col1", &(TOP.mlp_top__DOT__accum_u__DOT__u_mem__DOT__in_col1), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_mlp_top__accum_u__u_mem.varInsert(__Vfinal,"mem_buff0_col0", &(TOP.mlp_top__DOT__accum_u__DOT__u_mem__DOT__mem_buff0_col0), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_mlp_top__accum_u__u_mem.varInsert(__Vfinal,"mem_buff0_col1", &(TOP.mlp_top__DOT__accum_u__DOT__u_mem__DOT__mem_buff0_col1), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_mlp_top__accum_u__u_mem.varInsert(__Vfinal,"mem_buff1_col0", &(TOP.mlp_top__DOT__accum_u__DOT__u_mem__DOT__mem_buff1_col0), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_mlp_top__accum_u__u_mem.varInsert(__Vfinal,"mem_buff1_col1", &(TOP.mlp_top__DOT__accum_u__DOT__u_mem__DOT__mem_buff1_col1), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_mlp_top__accum_u__u_mem.varInsert(__Vfinal,"out_col0", &(TOP.mlp_top__DOT__accum_u__DOT__u_mem__DOT__out_col0), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_mlp_top__accum_u__u_mem.varInsert(__Vfinal,"out_col1", &(TOP.mlp_top__DOT__accum_u__DOT__u_mem__DOT__out_col1), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_mlp_top__accum_u__u_mem.varInsert(__Vfinal,"reset", &(TOP.mlp_top__DOT__accum_u__DOT__u_mem__DOT__reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__accum_u__u_mem.varInsert(__Vfinal,"valid_out", &(TOP.mlp_top__DOT__accum_u__DOT__u_mem__DOT__valid_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ap_col0.varInsert(__Vfinal,"acc_in", &(TOP.mlp_top__DOT__ap_col0__DOT__acc_in), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_mlp_top__ap_col0.varInsert(__Vfinal,"biased_reg", &(TOP.mlp_top__DOT__ap_col0__DOT__biased_reg), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_mlp_top__ap_col0.varInsert(__Vfinal,"clk", &(TOP.mlp_top__DOT__ap_col0__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ap_col0.varInsert(__Vfinal,"loss_out", &(TOP.mlp_top__DOT__ap_col0__DOT__loss_out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_mlp_top__ap_col0.varInsert(__Vfinal,"loss_valid", &(TOP.mlp_top__DOT__ap_col0__DOT__loss_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ap_col0.varInsert(__Vfinal,"mult_reg", &(TOP.mlp_top__DOT__ap_col0__DOT__mult_reg), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,0,1 ,47,0);
        __Vscope_mlp_top__ap_col0.varInsert(__Vfinal,"norm_bias", &(TOP.mlp_top__DOT__ap_col0__DOT__norm_bias), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_mlp_top__ap_col0.varInsert(__Vfinal,"norm_gain", &(TOP.mlp_top__DOT__ap_col0__DOT__norm_gain), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_mlp_top__ap_col0.varInsert(__Vfinal,"norm_shift", &(TOP.mlp_top__DOT__ap_col0__DOT__norm_shift), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_mlp_top__ap_col0.varInsert(__Vfinal,"q_inv_scale", &(TOP.mlp_top__DOT__ap_col0__DOT__q_inv_scale), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_mlp_top__ap_col0.varInsert(__Vfinal,"q_inv_scale_d0", &(TOP.mlp_top__DOT__ap_col0__DOT__q_inv_scale_d0), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_mlp_top__ap_col0.varInsert(__Vfinal,"q_s1_data", &(TOP.mlp_top__DOT__ap_col0__DOT__q_s1_data), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_mlp_top__ap_col0.varInsert(__Vfinal,"q_s1_valid", &(TOP.mlp_top__DOT__ap_col0__DOT__q_s1_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ap_col0.varInsert(__Vfinal,"q_s2_valid", &(TOP.mlp_top__DOT__ap_col0__DOT__q_s2_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ap_col0.varInsert(__Vfinal,"q_s3_valid", &(TOP.mlp_top__DOT__ap_col0__DOT__q_s3_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ap_col0.varInsert(__Vfinal,"q_s4_valid", &(TOP.mlp_top__DOT__ap_col0__DOT__q_s4_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ap_col0.varInsert(__Vfinal,"q_zero_point", &(TOP.mlp_top__DOT__ap_col0__DOT__q_zero_point), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_mlp_top__ap_col0.varInsert(__Vfinal,"q_zero_point_d0", &(TOP.mlp_top__DOT__ap_col0__DOT__q_zero_point_d0), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_mlp_top__ap_col0.varInsert(__Vfinal,"q_zero_point_d1", &(TOP.mlp_top__DOT__ap_col0__DOT__q_zero_point_d1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_mlp_top__ap_col0.varInsert(__Vfinal,"q_zero_point_d2", &(TOP.mlp_top__DOT__ap_col0__DOT__q_zero_point_d2), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_mlp_top__ap_col0.varInsert(__Vfinal,"reset", &(TOP.mlp_top__DOT__ap_col0__DOT__reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ap_col0.varInsert(__Vfinal,"s1_data", &(TOP.mlp_top__DOT__ap_col0__DOT__s1_data), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_mlp_top__ap_col0.varInsert(__Vfinal,"s1_valid", &(TOP.mlp_top__DOT__ap_col0__DOT__s1_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ap_col0.varInsert(__Vfinal,"s2_data", &(TOP.mlp_top__DOT__ap_col0__DOT__s2_data), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_mlp_top__ap_col0.varInsert(__Vfinal,"s2_valid", &(TOP.mlp_top__DOT__ap_col0__DOT__s2_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ap_col0.varInsert(__Vfinal,"scaled_reg", &(TOP.mlp_top__DOT__ap_col0__DOT__scaled_reg), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_mlp_top__ap_col0.varInsert(__Vfinal,"target_d1", &(TOP.mlp_top__DOT__ap_col0__DOT__target_d1), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_mlp_top__ap_col0.varInsert(__Vfinal,"target_in", &(TOP.mlp_top__DOT__ap_col0__DOT__target_in), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_mlp_top__ap_col0.varInsert(__Vfinal,"ub_data_out", &(TOP.mlp_top__DOT__ap_col0__DOT__ub_data_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_mlp_top__ap_col0.varInsert(__Vfinal,"ub_q_reg", &(TOP.mlp_top__DOT__ap_col0__DOT__ub_q_reg), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_mlp_top__ap_col0.varInsert(__Vfinal,"valid_in", &(TOP.mlp_top__DOT__ap_col0__DOT__valid_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ap_col0.varInsert(__Vfinal,"valid_out", &(TOP.mlp_top__DOT__ap_col0__DOT__valid_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ap_col0.varInsert(__Vfinal,"valid_reg", &(TOP.mlp_top__DOT__ap_col0__DOT__valid_reg), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ap_col0__act_u.varInsert(__Vfinal,"DEFAULT_ACT", const_cast<void*>(static_cast<const void*>(&(TOP.mlp_top__DOT__ap_col0__DOT__act_u__DOT__DEFAULT_ACT))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_mlp_top__ap_col0__act_u.varInsert(__Vfinal,"clk", &(TOP.mlp_top__DOT__ap_col0__DOT__act_u__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ap_col0__act_u.varInsert(__Vfinal,"data_in", &(TOP.mlp_top__DOT__ap_col0__DOT__act_u__DOT__data_in), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_mlp_top__ap_col0__act_u.varInsert(__Vfinal,"data_out", &(TOP.mlp_top__DOT__ap_col0__DOT__act_u__DOT__data_out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_mlp_top__ap_col0__act_u.varInsert(__Vfinal,"reset", &(TOP.mlp_top__DOT__ap_col0__DOT__act_u__DOT__reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ap_col0__act_u.varInsert(__Vfinal,"valid_in", &(TOP.mlp_top__DOT__ap_col0__DOT__act_u__DOT__valid_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ap_col0__act_u.varInsert(__Vfinal,"valid_out", &(TOP.mlp_top__DOT__ap_col0__DOT__act_u__DOT__valid_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ap_col0__loss_u.varInsert(__Vfinal,"abs_diff", &(TOP.mlp_top__DOT__ap_col0__DOT__loss_u__DOT__abs_diff), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_mlp_top__ap_col0__loss_u.varInsert(__Vfinal,"clk", &(TOP.mlp_top__DOT__ap_col0__DOT__loss_u__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ap_col0__loss_u.varInsert(__Vfinal,"data_in", &(TOP.mlp_top__DOT__ap_col0__DOT__loss_u__DOT__data_in), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_mlp_top__ap_col0__loss_u.varInsert(__Vfinal,"diff", &(TOP.mlp_top__DOT__ap_col0__DOT__loss_u__DOT__diff), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_mlp_top__ap_col0__loss_u.varInsert(__Vfinal,"loss_out", &(TOP.mlp_top__DOT__ap_col0__DOT__loss_u__DOT__loss_out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_mlp_top__ap_col0__loss_u.varInsert(__Vfinal,"reset", &(TOP.mlp_top__DOT__ap_col0__DOT__loss_u__DOT__reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ap_col0__loss_u.varInsert(__Vfinal,"target_in", &(TOP.mlp_top__DOT__ap_col0__DOT__loss_u__DOT__target_in), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_mlp_top__ap_col0__loss_u.varInsert(__Vfinal,"valid_in", &(TOP.mlp_top__DOT__ap_col0__DOT__loss_u__DOT__valid_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ap_col0__loss_u.varInsert(__Vfinal,"valid_out", &(TOP.mlp_top__DOT__ap_col0__DOT__loss_u__DOT__valid_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ap_col0__norm_u.varInsert(__Vfinal,"bias", &(TOP.mlp_top__DOT__ap_col0__DOT__norm_u__DOT__bias), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_mlp_top__ap_col0__norm_u.varInsert(__Vfinal,"bias_d", &(TOP.mlp_top__DOT__ap_col0__DOT__norm_u__DOT__bias_d), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_mlp_top__ap_col0__norm_u.varInsert(__Vfinal,"bias_d1", &(TOP.mlp_top__DOT__ap_col0__DOT__norm_u__DOT__bias_d1), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_mlp_top__ap_col0__norm_u.varInsert(__Vfinal,"clk", &(TOP.mlp_top__DOT__ap_col0__DOT__norm_u__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ap_col0__norm_u.varInsert(__Vfinal,"data_in", &(TOP.mlp_top__DOT__ap_col0__DOT__norm_u__DOT__data_in), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_mlp_top__ap_col0__norm_u.varInsert(__Vfinal,"data_in_d", &(TOP.mlp_top__DOT__ap_col0__DOT__norm_u__DOT__data_in_d), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_mlp_top__ap_col0__norm_u.varInsert(__Vfinal,"data_out", &(TOP.mlp_top__DOT__ap_col0__DOT__norm_u__DOT__data_out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_mlp_top__ap_col0__norm_u.varInsert(__Vfinal,"gain", &(TOP.mlp_top__DOT__ap_col0__DOT__norm_u__DOT__gain), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_mlp_top__ap_col0__norm_u.varInsert(__Vfinal,"gain_d", &(TOP.mlp_top__DOT__ap_col0__DOT__norm_u__DOT__gain_d), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_mlp_top__ap_col0__norm_u.varInsert(__Vfinal,"mult_res", &(TOP.mlp_top__DOT__ap_col0__DOT__norm_u__DOT__mult_res), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,0,1 ,47,0);
        __Vscope_mlp_top__ap_col0__norm_u.varInsert(__Vfinal,"reset", &(TOP.mlp_top__DOT__ap_col0__DOT__norm_u__DOT__reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ap_col0__norm_u.varInsert(__Vfinal,"s1_valid", &(TOP.mlp_top__DOT__ap_col0__DOT__norm_u__DOT__s1_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ap_col0__norm_u.varInsert(__Vfinal,"s2_valid", &(TOP.mlp_top__DOT__ap_col0__DOT__norm_u__DOT__s2_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ap_col0__norm_u.varInsert(__Vfinal,"shift", &(TOP.mlp_top__DOT__ap_col0__DOT__norm_u__DOT__shift), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_mlp_top__ap_col0__norm_u.varInsert(__Vfinal,"shift_d", &(TOP.mlp_top__DOT__ap_col0__DOT__norm_u__DOT__shift_d), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_mlp_top__ap_col0__norm_u.varInsert(__Vfinal,"shift_d1", &(TOP.mlp_top__DOT__ap_col0__DOT__norm_u__DOT__shift_d1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_mlp_top__ap_col0__norm_u.varInsert(__Vfinal,"shifted_res", &(TOP.mlp_top__DOT__ap_col0__DOT__norm_u__DOT__shifted_res), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,0,1 ,47,0);
        __Vscope_mlp_top__ap_col0__norm_u.varInsert(__Vfinal,"valid_in", &(TOP.mlp_top__DOT__ap_col0__DOT__norm_u__DOT__valid_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ap_col0__norm_u.varInsert(__Vfinal,"valid_out", &(TOP.mlp_top__DOT__ap_col0__DOT__norm_u__DOT__valid_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ap_col0__unnamedblk1.varInsert(__Vfinal,"mult_rounded", &(TOP.mlp_top__DOT__ap_col0__DOT__unnamedblk1__DOT__mult_rounded), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,0,1 ,47,0);
        __Vscope_mlp_top__ap_col1.varInsert(__Vfinal,"acc_in", &(TOP.mlp_top__DOT__ap_col1__DOT__acc_in), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_mlp_top__ap_col1.varInsert(__Vfinal,"biased_reg", &(TOP.mlp_top__DOT__ap_col1__DOT__biased_reg), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_mlp_top__ap_col1.varInsert(__Vfinal,"clk", &(TOP.mlp_top__DOT__ap_col1__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ap_col1.varInsert(__Vfinal,"loss_out", &(TOP.mlp_top__DOT__ap_col1__DOT__loss_out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_mlp_top__ap_col1.varInsert(__Vfinal,"loss_valid", &(TOP.mlp_top__DOT__ap_col1__DOT__loss_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ap_col1.varInsert(__Vfinal,"mult_reg", &(TOP.mlp_top__DOT__ap_col1__DOT__mult_reg), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,0,1 ,47,0);
        __Vscope_mlp_top__ap_col1.varInsert(__Vfinal,"norm_bias", &(TOP.mlp_top__DOT__ap_col1__DOT__norm_bias), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_mlp_top__ap_col1.varInsert(__Vfinal,"norm_gain", &(TOP.mlp_top__DOT__ap_col1__DOT__norm_gain), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_mlp_top__ap_col1.varInsert(__Vfinal,"norm_shift", &(TOP.mlp_top__DOT__ap_col1__DOT__norm_shift), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_mlp_top__ap_col1.varInsert(__Vfinal,"q_inv_scale", &(TOP.mlp_top__DOT__ap_col1__DOT__q_inv_scale), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_mlp_top__ap_col1.varInsert(__Vfinal,"q_inv_scale_d0", &(TOP.mlp_top__DOT__ap_col1__DOT__q_inv_scale_d0), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_mlp_top__ap_col1.varInsert(__Vfinal,"q_s1_data", &(TOP.mlp_top__DOT__ap_col1__DOT__q_s1_data), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_mlp_top__ap_col1.varInsert(__Vfinal,"q_s1_valid", &(TOP.mlp_top__DOT__ap_col1__DOT__q_s1_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ap_col1.varInsert(__Vfinal,"q_s2_valid", &(TOP.mlp_top__DOT__ap_col1__DOT__q_s2_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ap_col1.varInsert(__Vfinal,"q_s3_valid", &(TOP.mlp_top__DOT__ap_col1__DOT__q_s3_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ap_col1.varInsert(__Vfinal,"q_s4_valid", &(TOP.mlp_top__DOT__ap_col1__DOT__q_s4_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ap_col1.varInsert(__Vfinal,"q_zero_point", &(TOP.mlp_top__DOT__ap_col1__DOT__q_zero_point), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_mlp_top__ap_col1.varInsert(__Vfinal,"q_zero_point_d0", &(TOP.mlp_top__DOT__ap_col1__DOT__q_zero_point_d0), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_mlp_top__ap_col1.varInsert(__Vfinal,"q_zero_point_d1", &(TOP.mlp_top__DOT__ap_col1__DOT__q_zero_point_d1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_mlp_top__ap_col1.varInsert(__Vfinal,"q_zero_point_d2", &(TOP.mlp_top__DOT__ap_col1__DOT__q_zero_point_d2), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_mlp_top__ap_col1.varInsert(__Vfinal,"reset", &(TOP.mlp_top__DOT__ap_col1__DOT__reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ap_col1.varInsert(__Vfinal,"s1_data", &(TOP.mlp_top__DOT__ap_col1__DOT__s1_data), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_mlp_top__ap_col1.varInsert(__Vfinal,"s1_valid", &(TOP.mlp_top__DOT__ap_col1__DOT__s1_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ap_col1.varInsert(__Vfinal,"s2_data", &(TOP.mlp_top__DOT__ap_col1__DOT__s2_data), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_mlp_top__ap_col1.varInsert(__Vfinal,"s2_valid", &(TOP.mlp_top__DOT__ap_col1__DOT__s2_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ap_col1.varInsert(__Vfinal,"scaled_reg", &(TOP.mlp_top__DOT__ap_col1__DOT__scaled_reg), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_mlp_top__ap_col1.varInsert(__Vfinal,"target_d1", &(TOP.mlp_top__DOT__ap_col1__DOT__target_d1), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_mlp_top__ap_col1.varInsert(__Vfinal,"target_in", &(TOP.mlp_top__DOT__ap_col1__DOT__target_in), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_mlp_top__ap_col1.varInsert(__Vfinal,"ub_data_out", &(TOP.mlp_top__DOT__ap_col1__DOT__ub_data_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_mlp_top__ap_col1.varInsert(__Vfinal,"ub_q_reg", &(TOP.mlp_top__DOT__ap_col1__DOT__ub_q_reg), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_mlp_top__ap_col1.varInsert(__Vfinal,"valid_in", &(TOP.mlp_top__DOT__ap_col1__DOT__valid_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ap_col1.varInsert(__Vfinal,"valid_out", &(TOP.mlp_top__DOT__ap_col1__DOT__valid_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ap_col1.varInsert(__Vfinal,"valid_reg", &(TOP.mlp_top__DOT__ap_col1__DOT__valid_reg), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ap_col1__act_u.varInsert(__Vfinal,"DEFAULT_ACT", const_cast<void*>(static_cast<const void*>(&(TOP.mlp_top__DOT__ap_col1__DOT__act_u__DOT__DEFAULT_ACT))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_mlp_top__ap_col1__act_u.varInsert(__Vfinal,"clk", &(TOP.mlp_top__DOT__ap_col1__DOT__act_u__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ap_col1__act_u.varInsert(__Vfinal,"data_in", &(TOP.mlp_top__DOT__ap_col1__DOT__act_u__DOT__data_in), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_mlp_top__ap_col1__act_u.varInsert(__Vfinal,"data_out", &(TOP.mlp_top__DOT__ap_col1__DOT__act_u__DOT__data_out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_mlp_top__ap_col1__act_u.varInsert(__Vfinal,"reset", &(TOP.mlp_top__DOT__ap_col1__DOT__act_u__DOT__reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ap_col1__act_u.varInsert(__Vfinal,"valid_in", &(TOP.mlp_top__DOT__ap_col1__DOT__act_u__DOT__valid_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ap_col1__act_u.varInsert(__Vfinal,"valid_out", &(TOP.mlp_top__DOT__ap_col1__DOT__act_u__DOT__valid_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ap_col1__loss_u.varInsert(__Vfinal,"abs_diff", &(TOP.mlp_top__DOT__ap_col1__DOT__loss_u__DOT__abs_diff), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_mlp_top__ap_col1__loss_u.varInsert(__Vfinal,"clk", &(TOP.mlp_top__DOT__ap_col1__DOT__loss_u__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ap_col1__loss_u.varInsert(__Vfinal,"data_in", &(TOP.mlp_top__DOT__ap_col1__DOT__loss_u__DOT__data_in), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_mlp_top__ap_col1__loss_u.varInsert(__Vfinal,"diff", &(TOP.mlp_top__DOT__ap_col1__DOT__loss_u__DOT__diff), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_mlp_top__ap_col1__loss_u.varInsert(__Vfinal,"loss_out", &(TOP.mlp_top__DOT__ap_col1__DOT__loss_u__DOT__loss_out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_mlp_top__ap_col1__loss_u.varInsert(__Vfinal,"reset", &(TOP.mlp_top__DOT__ap_col1__DOT__loss_u__DOT__reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ap_col1__loss_u.varInsert(__Vfinal,"target_in", &(TOP.mlp_top__DOT__ap_col1__DOT__loss_u__DOT__target_in), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_mlp_top__ap_col1__loss_u.varInsert(__Vfinal,"valid_in", &(TOP.mlp_top__DOT__ap_col1__DOT__loss_u__DOT__valid_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ap_col1__loss_u.varInsert(__Vfinal,"valid_out", &(TOP.mlp_top__DOT__ap_col1__DOT__loss_u__DOT__valid_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ap_col1__norm_u.varInsert(__Vfinal,"bias", &(TOP.mlp_top__DOT__ap_col1__DOT__norm_u__DOT__bias), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_mlp_top__ap_col1__norm_u.varInsert(__Vfinal,"bias_d", &(TOP.mlp_top__DOT__ap_col1__DOT__norm_u__DOT__bias_d), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_mlp_top__ap_col1__norm_u.varInsert(__Vfinal,"bias_d1", &(TOP.mlp_top__DOT__ap_col1__DOT__norm_u__DOT__bias_d1), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_mlp_top__ap_col1__norm_u.varInsert(__Vfinal,"clk", &(TOP.mlp_top__DOT__ap_col1__DOT__norm_u__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ap_col1__norm_u.varInsert(__Vfinal,"data_in", &(TOP.mlp_top__DOT__ap_col1__DOT__norm_u__DOT__data_in), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_mlp_top__ap_col1__norm_u.varInsert(__Vfinal,"data_in_d", &(TOP.mlp_top__DOT__ap_col1__DOT__norm_u__DOT__data_in_d), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_mlp_top__ap_col1__norm_u.varInsert(__Vfinal,"data_out", &(TOP.mlp_top__DOT__ap_col1__DOT__norm_u__DOT__data_out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_mlp_top__ap_col1__norm_u.varInsert(__Vfinal,"gain", &(TOP.mlp_top__DOT__ap_col1__DOT__norm_u__DOT__gain), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_mlp_top__ap_col1__norm_u.varInsert(__Vfinal,"gain_d", &(TOP.mlp_top__DOT__ap_col1__DOT__norm_u__DOT__gain_d), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_mlp_top__ap_col1__norm_u.varInsert(__Vfinal,"mult_res", &(TOP.mlp_top__DOT__ap_col1__DOT__norm_u__DOT__mult_res), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,0,1 ,47,0);
        __Vscope_mlp_top__ap_col1__norm_u.varInsert(__Vfinal,"reset", &(TOP.mlp_top__DOT__ap_col1__DOT__norm_u__DOT__reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ap_col1__norm_u.varInsert(__Vfinal,"s1_valid", &(TOP.mlp_top__DOT__ap_col1__DOT__norm_u__DOT__s1_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ap_col1__norm_u.varInsert(__Vfinal,"s2_valid", &(TOP.mlp_top__DOT__ap_col1__DOT__norm_u__DOT__s2_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ap_col1__norm_u.varInsert(__Vfinal,"shift", &(TOP.mlp_top__DOT__ap_col1__DOT__norm_u__DOT__shift), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_mlp_top__ap_col1__norm_u.varInsert(__Vfinal,"shift_d", &(TOP.mlp_top__DOT__ap_col1__DOT__norm_u__DOT__shift_d), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_mlp_top__ap_col1__norm_u.varInsert(__Vfinal,"shift_d1", &(TOP.mlp_top__DOT__ap_col1__DOT__norm_u__DOT__shift_d1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_mlp_top__ap_col1__norm_u.varInsert(__Vfinal,"shifted_res", &(TOP.mlp_top__DOT__ap_col1__DOT__norm_u__DOT__shifted_res), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,0,1 ,47,0);
        __Vscope_mlp_top__ap_col1__norm_u.varInsert(__Vfinal,"valid_in", &(TOP.mlp_top__DOT__ap_col1__DOT__norm_u__DOT__valid_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ap_col1__norm_u.varInsert(__Vfinal,"valid_out", &(TOP.mlp_top__DOT__ap_col1__DOT__norm_u__DOT__valid_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ap_col1__unnamedblk1.varInsert(__Vfinal,"mult_rounded", &(TOP.mlp_top__DOT__ap_col1__DOT__unnamedblk1__DOT__mult_rounded), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,0,1 ,47,0);
        __Vscope_mlp_top__mmu_u.varInsert(__Vfinal,"acc0_out", &(TOP.mlp_top__DOT__mmu_u__DOT__acc0_out), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_mlp_top__mmu_u.varInsert(__Vfinal,"acc1_out", &(TOP.mlp_top__DOT__mmu_u__DOT__acc1_out), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_mlp_top__mmu_u.varInsert(__Vfinal,"clk", &(TOP.mlp_top__DOT__mmu_u__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__mmu_u.varInsert(__Vfinal,"col0_in", &(TOP.mlp_top__DOT__mmu_u__DOT__col0_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_mlp_top__mmu_u.varInsert(__Vfinal,"col1_in", &(TOP.mlp_top__DOT__mmu_u__DOT__col1_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_mlp_top__mmu_u.varInsert(__Vfinal,"en_capture_col0", &(TOP.mlp_top__DOT__mmu_u__DOT__en_capture_col0), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__mmu_u.varInsert(__Vfinal,"en_capture_col1", &(TOP.mlp_top__DOT__mmu_u__DOT__en_capture_col1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__mmu_u.varInsert(__Vfinal,"en_weight_pass", &(TOP.mlp_top__DOT__mmu_u__DOT__en_weight_pass), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__mmu_u.varInsert(__Vfinal,"pe00_01_act", &(TOP.mlp_top__DOT__mmu_u__DOT__pe00_01_act), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_mlp_top__mmu_u.varInsert(__Vfinal,"pe00_10_psum", &(TOP.mlp_top__DOT__mmu_u__DOT__pe00_10_psum), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_mlp_top__mmu_u.varInsert(__Vfinal,"pe01_11_psum", &(TOP.mlp_top__DOT__mmu_u__DOT__pe01_11_psum), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_mlp_top__mmu_u.varInsert(__Vfinal,"pe10_11_act", &(TOP.mlp_top__DOT__mmu_u__DOT__pe10_11_act), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_mlp_top__mmu_u.varInsert(__Vfinal,"reset", &(TOP.mlp_top__DOT__mmu_u__DOT__reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__mmu_u.varInsert(__Vfinal,"row0_in", &(TOP.mlp_top__DOT__mmu_u__DOT__row0_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_mlp_top__mmu_u.varInsert(__Vfinal,"row1_in", &(TOP.mlp_top__DOT__mmu_u__DOT__row1_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_mlp_top__mmu_u__pe00.varInsert(__Vfinal,"clk", &(TOP.mlp_top__DOT__mmu_u__DOT__pe00__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__mmu_u__pe00.varInsert(__Vfinal,"en_weight_capture", &(TOP.mlp_top__DOT__mmu_u__DOT__pe00__DOT__en_weight_capture), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__mmu_u__pe00.varInsert(__Vfinal,"en_weight_pass", &(TOP.mlp_top__DOT__mmu_u__DOT__pe00__DOT__en_weight_pass), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__mmu_u__pe00.varInsert(__Vfinal,"in_act", &(TOP.mlp_top__DOT__mmu_u__DOT__pe00__DOT__in_act), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_mlp_top__mmu_u__pe00.varInsert(__Vfinal,"in_psum", &(TOP.mlp_top__DOT__mmu_u__DOT__pe00__DOT__in_psum), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_mlp_top__mmu_u__pe00.varInsert(__Vfinal,"out_act", &(TOP.mlp_top__DOT__mmu_u__DOT__pe00__DOT__out_act), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_mlp_top__mmu_u__pe00.varInsert(__Vfinal,"out_psum", &(TOP.mlp_top__DOT__mmu_u__DOT__pe00__DOT__out_psum), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_mlp_top__mmu_u__pe00.varInsert(__Vfinal,"reset", &(TOP.mlp_top__DOT__mmu_u__DOT__pe00__DOT__reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__mmu_u__pe00.varInsert(__Vfinal,"weight", &(TOP.mlp_top__DOT__mmu_u__DOT__pe00__DOT__weight), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_mlp_top__mmu_u__pe01.varInsert(__Vfinal,"clk", &(TOP.mlp_top__DOT__mmu_u__DOT__pe01__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__mmu_u__pe01.varInsert(__Vfinal,"en_weight_capture", &(TOP.mlp_top__DOT__mmu_u__DOT__pe01__DOT__en_weight_capture), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__mmu_u__pe01.varInsert(__Vfinal,"en_weight_pass", &(TOP.mlp_top__DOT__mmu_u__DOT__pe01__DOT__en_weight_pass), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__mmu_u__pe01.varInsert(__Vfinal,"in_act", &(TOP.mlp_top__DOT__mmu_u__DOT__pe01__DOT__in_act), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_mlp_top__mmu_u__pe01.varInsert(__Vfinal,"in_psum", &(TOP.mlp_top__DOT__mmu_u__DOT__pe01__DOT__in_psum), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_mlp_top__mmu_u__pe01.varInsert(__Vfinal,"out_act", &(TOP.mlp_top__DOT__mmu_u__DOT__pe01__DOT__out_act), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_mlp_top__mmu_u__pe01.varInsert(__Vfinal,"out_psum", &(TOP.mlp_top__DOT__mmu_u__DOT__pe01__DOT__out_psum), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_mlp_top__mmu_u__pe01.varInsert(__Vfinal,"reset", &(TOP.mlp_top__DOT__mmu_u__DOT__pe01__DOT__reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__mmu_u__pe01.varInsert(__Vfinal,"weight", &(TOP.mlp_top__DOT__mmu_u__DOT__pe01__DOT__weight), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_mlp_top__mmu_u__pe10.varInsert(__Vfinal,"clk", &(TOP.mlp_top__DOT__mmu_u__DOT__pe10__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__mmu_u__pe10.varInsert(__Vfinal,"en_weight_capture", &(TOP.mlp_top__DOT__mmu_u__DOT__pe10__DOT__en_weight_capture), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__mmu_u__pe10.varInsert(__Vfinal,"en_weight_pass", &(TOP.mlp_top__DOT__mmu_u__DOT__pe10__DOT__en_weight_pass), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__mmu_u__pe10.varInsert(__Vfinal,"in_act", &(TOP.mlp_top__DOT__mmu_u__DOT__pe10__DOT__in_act), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_mlp_top__mmu_u__pe10.varInsert(__Vfinal,"in_psum", &(TOP.mlp_top__DOT__mmu_u__DOT__pe10__DOT__in_psum), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_mlp_top__mmu_u__pe10.varInsert(__Vfinal,"out_act", &(TOP.mlp_top__DOT__mmu_u__DOT__pe10__DOT__out_act), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_mlp_top__mmu_u__pe10.varInsert(__Vfinal,"out_psum", &(TOP.mlp_top__DOT__mmu_u__DOT__pe10__DOT__out_psum), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_mlp_top__mmu_u__pe10.varInsert(__Vfinal,"reset", &(TOP.mlp_top__DOT__mmu_u__DOT__pe10__DOT__reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__mmu_u__pe10.varInsert(__Vfinal,"weight", &(TOP.mlp_top__DOT__mmu_u__DOT__pe10__DOT__weight), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_mlp_top__mmu_u__pe11.varInsert(__Vfinal,"clk", &(TOP.mlp_top__DOT__mmu_u__DOT__pe11__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__mmu_u__pe11.varInsert(__Vfinal,"en_weight_capture", &(TOP.mlp_top__DOT__mmu_u__DOT__pe11__DOT__en_weight_capture), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__mmu_u__pe11.varInsert(__Vfinal,"en_weight_pass", &(TOP.mlp_top__DOT__mmu_u__DOT__pe11__DOT__en_weight_pass), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__mmu_u__pe11.varInsert(__Vfinal,"in_act", &(TOP.mlp_top__DOT__mmu_u__DOT__pe11__DOT__in_act), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_mlp_top__mmu_u__pe11.varInsert(__Vfinal,"in_psum", &(TOP.mlp_top__DOT__mmu_u__DOT__pe11__DOT__in_psum), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_mlp_top__mmu_u__pe11.varInsert(__Vfinal,"out_act", &(TOP.mlp_top__DOT__mmu_u__DOT__pe11__DOT__out_act), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_mlp_top__mmu_u__pe11.varInsert(__Vfinal,"out_psum", &(TOP.mlp_top__DOT__mmu_u__DOT__pe11__DOT__out_psum), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_mlp_top__mmu_u__pe11.varInsert(__Vfinal,"reset", &(TOP.mlp_top__DOT__mmu_u__DOT__pe11__DOT__reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__mmu_u__pe11.varInsert(__Vfinal,"weight", &(TOP.mlp_top__DOT__mmu_u__DOT__pe11__DOT__weight), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_mlp_top__ub_a.varInsert(__Vfinal,"ADDR_W", const_cast<void*>(static_cast<const void*>(&(TOP.mlp_top__DOT__ub_a__DOT__ADDR_W))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_mlp_top__ub_a.varInsert(__Vfinal,"DEPTH", const_cast<void*>(static_cast<const void*>(&(TOP.mlp_top__DOT__ub_a__DOT__DEPTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_mlp_top__ub_a.varInsert(__Vfinal,"WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.mlp_top__DOT__ub_a__DOT__WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_mlp_top__ub_a.varInsert(__Vfinal,"clk", &(TOP.mlp_top__DOT__ub_a__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ub_a.varInsert(__Vfinal,"count", &(TOP.mlp_top__DOT__ub_a__DOT__count), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_mlp_top__ub_a.varInsert(__Vfinal,"do_read", &(TOP.mlp_top__DOT__ub_a__DOT__do_read), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ub_a.varInsert(__Vfinal,"do_write", &(TOP.mlp_top__DOT__ub_a__DOT__do_write), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ub_a.varInsert(__Vfinal,"empty", &(TOP.mlp_top__DOT__ub_a__DOT__empty), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ub_a.varInsert(__Vfinal,"full", &(TOP.mlp_top__DOT__ub_a__DOT__full), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ub_a.varInsert(__Vfinal,"mem", &(TOP.mlp_top__DOT__ub_a__DOT__mem), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1,1 ,0,15 ,15,0);
        __Vscope_mlp_top__ub_a.varInsert(__Vfinal,"rd_data", &(TOP.mlp_top__DOT__ub_a__DOT__rd_data), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_mlp_top__ub_a.varInsert(__Vfinal,"rd_data_comb", &(TOP.mlp_top__DOT__ub_a__DOT__rd_data_comb), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_mlp_top__ub_a.varInsert(__Vfinal,"rd_data_reg", &(TOP.mlp_top__DOT__ub_a__DOT__rd_data_reg), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_mlp_top__ub_a.varInsert(__Vfinal,"rd_ptr", &(TOP.mlp_top__DOT__ub_a__DOT__rd_ptr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_mlp_top__ub_a.varInsert(__Vfinal,"rd_ready", &(TOP.mlp_top__DOT__ub_a__DOT__rd_ready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ub_a.varInsert(__Vfinal,"rd_valid", &(TOP.mlp_top__DOT__ub_a__DOT__rd_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ub_a.varInsert(__Vfinal,"rd_valid_comb", &(TOP.mlp_top__DOT__ub_a__DOT__rd_valid_comb), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ub_a.varInsert(__Vfinal,"rd_valid_reg", &(TOP.mlp_top__DOT__ub_a__DOT__rd_valid_reg), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ub_a.varInsert(__Vfinal,"reset", &(TOP.mlp_top__DOT__ub_a__DOT__reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ub_a.varInsert(__Vfinal,"wr_data", &(TOP.mlp_top__DOT__ub_a__DOT__wr_data), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_mlp_top__ub_a.varInsert(__Vfinal,"wr_ptr", &(TOP.mlp_top__DOT__ub_a__DOT__wr_ptr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_mlp_top__ub_a.varInsert(__Vfinal,"wr_ready", &(TOP.mlp_top__DOT__ub_a__DOT__wr_ready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ub_a.varInsert(__Vfinal,"wr_valid", &(TOP.mlp_top__DOT__ub_a__DOT__wr_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ub_b.varInsert(__Vfinal,"ADDR_W", const_cast<void*>(static_cast<const void*>(&(TOP.mlp_top__DOT__ub_b__DOT__ADDR_W))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_mlp_top__ub_b.varInsert(__Vfinal,"DEPTH", const_cast<void*>(static_cast<const void*>(&(TOP.mlp_top__DOT__ub_b__DOT__DEPTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_mlp_top__ub_b.varInsert(__Vfinal,"WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.mlp_top__DOT__ub_b__DOT__WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_mlp_top__ub_b.varInsert(__Vfinal,"clk", &(TOP.mlp_top__DOT__ub_b__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ub_b.varInsert(__Vfinal,"count", &(TOP.mlp_top__DOT__ub_b__DOT__count), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_mlp_top__ub_b.varInsert(__Vfinal,"do_read", &(TOP.mlp_top__DOT__ub_b__DOT__do_read), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ub_b.varInsert(__Vfinal,"do_write", &(TOP.mlp_top__DOT__ub_b__DOT__do_write), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ub_b.varInsert(__Vfinal,"empty", &(TOP.mlp_top__DOT__ub_b__DOT__empty), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ub_b.varInsert(__Vfinal,"full", &(TOP.mlp_top__DOT__ub_b__DOT__full), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ub_b.varInsert(__Vfinal,"mem", &(TOP.mlp_top__DOT__ub_b__DOT__mem), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1,1 ,0,15 ,15,0);
        __Vscope_mlp_top__ub_b.varInsert(__Vfinal,"rd_data", &(TOP.mlp_top__DOT__ub_b__DOT__rd_data), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_mlp_top__ub_b.varInsert(__Vfinal,"rd_data_comb", &(TOP.mlp_top__DOT__ub_b__DOT__rd_data_comb), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_mlp_top__ub_b.varInsert(__Vfinal,"rd_data_reg", &(TOP.mlp_top__DOT__ub_b__DOT__rd_data_reg), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_mlp_top__ub_b.varInsert(__Vfinal,"rd_ptr", &(TOP.mlp_top__DOT__ub_b__DOT__rd_ptr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_mlp_top__ub_b.varInsert(__Vfinal,"rd_ready", &(TOP.mlp_top__DOT__ub_b__DOT__rd_ready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ub_b.varInsert(__Vfinal,"rd_valid", &(TOP.mlp_top__DOT__ub_b__DOT__rd_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ub_b.varInsert(__Vfinal,"rd_valid_comb", &(TOP.mlp_top__DOT__ub_b__DOT__rd_valid_comb), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ub_b.varInsert(__Vfinal,"rd_valid_reg", &(TOP.mlp_top__DOT__ub_b__DOT__rd_valid_reg), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ub_b.varInsert(__Vfinal,"reset", &(TOP.mlp_top__DOT__ub_b__DOT__reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ub_b.varInsert(__Vfinal,"wr_data", &(TOP.mlp_top__DOT__ub_b__DOT__wr_data), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_mlp_top__ub_b.varInsert(__Vfinal,"wr_ptr", &(TOP.mlp_top__DOT__ub_b__DOT__wr_ptr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_mlp_top__ub_b.varInsert(__Vfinal,"wr_ready", &(TOP.mlp_top__DOT__ub_b__DOT__wr_ready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__ub_b.varInsert(__Vfinal,"wr_valid", &(TOP.mlp_top__DOT__ub_b__DOT__wr_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__weight_fifo_u.varInsert(__Vfinal,"clk", &(TOP.mlp_top__DOT__weight_fifo_u__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__weight_fifo_u.varInsert(__Vfinal,"col0_out", &(TOP.mlp_top__DOT__weight_fifo_u__DOT__col0_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_mlp_top__weight_fifo_u.varInsert(__Vfinal,"col1_out", &(TOP.mlp_top__DOT__weight_fifo_u__DOT__col1_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_mlp_top__weight_fifo_u.varInsert(__Vfinal,"col1_raw", &(TOP.mlp_top__DOT__weight_fifo_u__DOT__col1_raw), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_mlp_top__weight_fifo_u.varInsert(__Vfinal,"data_in", &(TOP.mlp_top__DOT__weight_fifo_u__DOT__data_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_mlp_top__weight_fifo_u.varInsert(__Vfinal,"pop", &(TOP.mlp_top__DOT__weight_fifo_u__DOT__pop), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__weight_fifo_u.varInsert(__Vfinal,"push_col0", &(TOP.mlp_top__DOT__weight_fifo_u__DOT__push_col0), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__weight_fifo_u.varInsert(__Vfinal,"push_col1", &(TOP.mlp_top__DOT__weight_fifo_u__DOT__push_col1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__weight_fifo_u.varInsert(__Vfinal,"queue0", &(TOP.mlp_top__DOT__weight_fifo_u__DOT__queue0), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1,1 ,0,3 ,7,0);
        __Vscope_mlp_top__weight_fifo_u.varInsert(__Vfinal,"queue1", &(TOP.mlp_top__DOT__weight_fifo_u__DOT__queue1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1,1 ,0,3 ,7,0);
        __Vscope_mlp_top__weight_fifo_u.varInsert(__Vfinal,"rd_ptr0", &(TOP.mlp_top__DOT__weight_fifo_u__DOT__rd_ptr0), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_mlp_top__weight_fifo_u.varInsert(__Vfinal,"rd_ptr1", &(TOP.mlp_top__DOT__weight_fifo_u__DOT__rd_ptr1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_mlp_top__weight_fifo_u.varInsert(__Vfinal,"reset", &(TOP.mlp_top__DOT__weight_fifo_u__DOT__reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_mlp_top__weight_fifo_u.varInsert(__Vfinal,"wr_ptr0", &(TOP.mlp_top__DOT__weight_fifo_u__DOT__wr_ptr0), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_mlp_top__weight_fifo_u.varInsert(__Vfinal,"wr_ptr1", &(TOP.mlp_top__DOT__weight_fifo_u__DOT__wr_ptr1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
    }
}
