// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_vcd_c.h"
#include "Vtop__Syms.h"


VL_ATTR_COLD void Vtop___024root__trace_init_sub__TOP__0(Vtop___024root* vlSelf, VerilatedVcd* tracep) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_init_sub__TOP__0\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    const int c = vlSymsp->__Vm_baseCode;
    tracep->pushPrefix("$rootio", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+1,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+2,0,"reset",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+3,0,"wf_push_col0",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+4,0,"wf_push_col1",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+5,0,"wf_data_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBit(c+6,0,"wf_reset",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+7,0,"init_act_valid",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+8,0,"init_act_data",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+9,0,"start_mlp",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+10,0,"weights_ready",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+11,0,"norm_gain",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+12,0,"norm_bias",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+13,0,"norm_shift",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+14,0,"q_inv_scale",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+15,0,"q_zero_point",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+16,0,"state",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+17,0,"cycle_cnt",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+18,0,"current_layer",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBit(c+19,0,"layer_complete",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+20,0,"mmu_acc0_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+21,0,"mmu_acc1_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+22,0,"acc0",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+23,0,"acc1",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+24,0,"acc_valid",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("mlp_top", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+25,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+26,0,"reset",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+27,0,"wf_push_col0",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+28,0,"wf_push_col1",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+29,0,"wf_data_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBit(c+30,0,"wf_reset",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+31,0,"init_act_valid",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+32,0,"init_act_data",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+33,0,"start_mlp",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+34,0,"weights_ready",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+35,0,"norm_gain",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+36,0,"norm_bias",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+37,0,"norm_shift",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+38,0,"q_inv_scale",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+39,0,"q_zero_point",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+40,0,"state",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+41,0,"cycle_cnt",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+42,0,"current_layer",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBit(c+43,0,"layer_complete",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+44,0,"mmu_acc0_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+45,0,"mmu_acc1_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+46,0,"acc0",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+47,0,"acc1",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+48,0,"acc_valid",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+376,0,"IDLE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+377,0,"LOAD_WEIGHT",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+378,0,"LOAD_ACT",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+379,0,"COMPUTE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+380,0,"DRAIN",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+381,0,"TRANSFER",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+382,0,"NEXT_LAYER",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+383,0,"WAIT_WEIGHTS",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+384,0,"DONE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+385,0,"NUM_LAYERS",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+49,0,"state_reg",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+50,0,"cycle_cnt_reg",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+51,0,"current_layer_reg",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBit(c+52,0,"buffer_select",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+53,0,"weights_loaded",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+54,0,"en_load_weight",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+55,0,"compute_phase",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+56,0,"drain_phase",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+57,0,"transfer_phase",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+58,0,"wf_col0_out",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+59,0,"wf_col1_out",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+60,0,"wf_col1_raw",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBit(c+61,0,"ub_a_wr_valid",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+62,0,"ub_a_rd_ready",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+63,0,"ub_a_wr_data",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+64,0,"ub_a_rd_data",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+65,0,"ub_a_wr_ready",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+66,0,"ub_a_rd_valid",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+67,0,"ub_a_empty",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+68,0,"ub_b_wr_valid",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+69,0,"ub_b_rd_ready",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+70,0,"ub_b_wr_data",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+71,0,"ub_b_rd_data",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+72,0,"ub_b_wr_ready",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+73,0,"ub_b_rd_valid",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+74,0,"ub_b_empty",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+75,0,"act_ub_rd_valid",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+76,0,"act_ub_rd_data",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+77,0,"act_ub_empty",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+78,0,"act_row0_data",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+79,0,"act_row1_data",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+80,0,"row1_skew_reg",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+81,0,"mmu_row0_in",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+82,0,"mmu_row1_in",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+83,0,"mmu_col0_in",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+84,0,"mmu_col1_in",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBit(c+85,0,"en_capture_col0",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+86,0,"en_capture_col1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+87,0,"accum_en",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+88,0,"addr_sel",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+89,0,"mmu_valid",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+90,0,"ap_valid",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+91,0,"ap_data_col0",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+92,0,"ap_data_col1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBit(c+93,0,"refill_valid",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+94,0,"refill_data",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->pushPrefix("accum_u", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+95,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+96,0,"reset",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+97,0,"valid_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+98,0,"accumulator_enable",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+99,0,"addr_sel",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+100,0,"mmu_col0_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+101,0,"mmu_col1_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+102,0,"acc_col0_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+103,0,"acc_col1_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+104,0,"valid_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+105,0,"aligned_valid",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+106,0,"aligned_c0",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+107,0,"aligned_c1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->pushPrefix("u_align", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+108,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+109,0,"reset",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+110,0,"valid_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+111,0,"raw_col0",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+112,0,"raw_col1",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+113,0,"aligned_valid",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+114,0,"align_col0",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+115,0,"align_col1",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+116,0,"col0_delay_reg",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+117,0,"pending",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("u_mem", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+386,0,"BYPASS_READ_NEW",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::BIT, false,-1);
    tracep->declBit(c+118,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+119,0,"reset",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+120,0,"enable",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+121,0,"accumulator_mode",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+122,0,"buffer_select",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+123,0,"in_col0",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+124,0,"in_col1",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+125,0,"valid_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+126,0,"out_col0",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+127,0,"out_col1",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+128,0,"mem_buff0_col0",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+129,0,"mem_buff0_col1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+130,0,"mem_buff1_col0",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+131,0,"mem_buff1_col1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("ap_col0", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+132,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+133,0,"reset",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+134,0,"valid_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+135,0,"acc_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+136,0,"target_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+137,0,"norm_gain",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+138,0,"norm_bias",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+139,0,"norm_shift",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+140,0,"q_inv_scale",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+141,0,"q_zero_point",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBit(c+142,0,"valid_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+143,0,"ub_data_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBit(c+144,0,"loss_valid",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+145,0,"loss_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+146,0,"s1_valid",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+147,0,"s1_data",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+148,0,"target_d1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+149,0,"s2_valid",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+150,0,"s2_data",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+151,0,"ub_q_reg",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBit(c+152,0,"valid_reg",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declQuad(c+153,0,"mult",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 47,0);
    tracep->declQuad(c+155,0,"mult_rounded",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 47,0);
    tracep->declBus(c+157,0,"scaled",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+158,0,"biased",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->pushPrefix("act_u", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+387,0,"DEFAULT_ACT",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+159,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+160,0,"reset",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+161,0,"valid_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+162,0,"data_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+163,0,"valid_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+164,0,"data_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("loss_u", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+165,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+166,0,"reset",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+167,0,"valid_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+168,0,"data_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+169,0,"target_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+170,0,"valid_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+171,0,"loss_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+172,0,"diff",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+173,0,"abs_diff",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("norm_u", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+174,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+175,0,"reset",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+176,0,"valid_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+177,0,"data_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+178,0,"gain",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+179,0,"bias",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+180,0,"shift",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBit(c+181,0,"valid_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+182,0,"data_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declQuad(c+183,0,"mult",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 47,0);
    tracep->declQuad(c+185,0,"shifted",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 47,0);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("ap_col1", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+187,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+188,0,"reset",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+189,0,"valid_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+190,0,"acc_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+191,0,"target_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+192,0,"norm_gain",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+193,0,"norm_bias",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+194,0,"norm_shift",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+195,0,"q_inv_scale",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+196,0,"q_zero_point",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBit(c+197,0,"valid_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+198,0,"ub_data_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBit(c+199,0,"loss_valid",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+200,0,"loss_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+201,0,"s1_valid",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+202,0,"s1_data",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+203,0,"target_d1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+204,0,"s2_valid",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+205,0,"s2_data",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+206,0,"ub_q_reg",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBit(c+207,0,"valid_reg",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declQuad(c+208,0,"mult",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 47,0);
    tracep->declQuad(c+210,0,"mult_rounded",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 47,0);
    tracep->declBus(c+212,0,"scaled",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+213,0,"biased",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->pushPrefix("act_u", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+387,0,"DEFAULT_ACT",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+214,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+215,0,"reset",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+216,0,"valid_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+217,0,"data_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+218,0,"valid_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+219,0,"data_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("loss_u", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+220,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+221,0,"reset",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+222,0,"valid_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+223,0,"data_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+224,0,"target_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+225,0,"valid_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+226,0,"loss_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+227,0,"diff",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+228,0,"abs_diff",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("norm_u", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+229,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+230,0,"reset",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+231,0,"valid_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+232,0,"data_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+233,0,"gain",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+234,0,"bias",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+235,0,"shift",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBit(c+236,0,"valid_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+237,0,"data_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declQuad(c+238,0,"mult",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 47,0);
    tracep->declQuad(c+240,0,"shifted",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 47,0);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("mmu_u", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+242,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+243,0,"reset",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+244,0,"en_weight_pass",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+245,0,"en_capture_col0",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+246,0,"en_capture_col1",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+247,0,"row0_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+248,0,"row1_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+249,0,"col0_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+250,0,"col1_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+251,0,"acc0_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+252,0,"acc1_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+253,0,"pe00_01_act",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+254,0,"pe10_11_act",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+255,0,"pe00_10_psum",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+256,0,"pe01_11_psum",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->pushPrefix("pe00", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+257,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+258,0,"reset",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+259,0,"en_weight_pass",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+260,0,"en_weight_capture",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+261,0,"in_act",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+262,0,"in_psum",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+263,0,"out_act",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+264,0,"out_psum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+265,0,"weight",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->popPrefix();
    tracep->pushPrefix("pe01", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+266,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+267,0,"reset",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+268,0,"en_weight_pass",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+269,0,"en_weight_capture",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+270,0,"in_act",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+271,0,"in_psum",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+272,0,"out_act",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+273,0,"out_psum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+274,0,"weight",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->popPrefix();
    tracep->pushPrefix("pe10", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+275,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+276,0,"reset",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+277,0,"en_weight_pass",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+278,0,"en_weight_capture",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+279,0,"in_act",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+280,0,"in_psum",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+281,0,"out_act",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+282,0,"out_psum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+283,0,"weight",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->popPrefix();
    tracep->pushPrefix("pe11", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+284,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+285,0,"reset",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+286,0,"en_weight_pass",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+287,0,"en_weight_capture",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+288,0,"in_act",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+289,0,"in_psum",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+290,0,"out_act",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+291,0,"out_psum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+292,0,"weight",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("ub_a", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+388,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+388,0,"DEPTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+389,0,"ADDR_W",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBit(c+293,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+294,0,"reset",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+295,0,"wr_valid",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+296,0,"wr_data",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+297,0,"wr_ready",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+298,0,"rd_ready",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+299,0,"rd_valid",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+300,0,"rd_data",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+301,0,"full",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+302,0,"empty",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+303,0,"count",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->pushPrefix("mem", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 16; ++i) {
        tracep->declBus(c+304+i*1,0,"",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, true,(i+0), 15,0);
    }
    tracep->popPrefix();
    tracep->declBus(c+320,0,"wr_ptr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+321,0,"rd_ptr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+322,0,"do_write",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+323,0,"do_read",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("ub_b", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+388,0,"WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+388,0,"DEPTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+389,0,"ADDR_W",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBit(c+324,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+325,0,"reset",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+326,0,"wr_valid",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+327,0,"wr_data",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+328,0,"wr_ready",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+329,0,"rd_ready",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+330,0,"rd_valid",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+331,0,"rd_data",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+332,0,"full",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+333,0,"empty",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+334,0,"count",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->pushPrefix("mem", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 16; ++i) {
        tracep->declBus(c+335+i*1,0,"",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, true,(i+0), 15,0);
    }
    tracep->popPrefix();
    tracep->declBus(c+351,0,"wr_ptr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+352,0,"rd_ptr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+353,0,"do_write",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+354,0,"do_read",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("weight_fifo_u", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+355,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+356,0,"reset",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+357,0,"push_col0",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+358,0,"push_col1",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+359,0,"data_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBit(c+360,0,"pop",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+361,0,"col0_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+362,0,"col1_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+363,0,"col1_raw",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->pushPrefix("queue0", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 4; ++i) {
        tracep->declBus(c+364+i*1,0,"",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, true,(i+0), 7,0);
    }
    tracep->popPrefix();
    tracep->pushPrefix("queue1", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 4; ++i) {
        tracep->declBus(c+368+i*1,0,"",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, true,(i+0), 7,0);
    }
    tracep->popPrefix();
    tracep->declBus(c+372,0,"wr_ptr0",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+373,0,"rd_ptr0",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+374,0,"wr_ptr1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+375,0,"rd_ptr1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->popPrefix();
    tracep->popPrefix();
}

VL_ATTR_COLD void Vtop___024root__trace_init_top(Vtop___024root* vlSelf, VerilatedVcd* tracep) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_init_top\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    Vtop___024root__trace_init_sub__TOP__0(vlSelf, tracep);
}

VL_ATTR_COLD void Vtop___024root__trace_const_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
VL_ATTR_COLD void Vtop___024root__trace_full_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void Vtop___024root__trace_chg_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void Vtop___024root__trace_cleanup(void* voidSelf, VerilatedVcd* /*unused*/);

VL_ATTR_COLD void Vtop___024root__trace_register(Vtop___024root* vlSelf, VerilatedVcd* tracep) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_register\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    tracep->addConstCb(&Vtop___024root__trace_const_0, 0, vlSelf);
    tracep->addFullCb(&Vtop___024root__trace_full_0, 0, vlSelf);
    tracep->addChgCb(&Vtop___024root__trace_chg_0, 0, vlSelf);
    tracep->addCleanupCb(&Vtop___024root__trace_cleanup, vlSelf);
}

VL_ATTR_COLD void Vtop___024root__trace_const_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp);

VL_ATTR_COLD void Vtop___024root__trace_const_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_const_0\n"); );
    // Body
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    Vtop___024root__trace_const_0_sub_0((&vlSymsp->TOP), bufp);
}

VL_ATTR_COLD void Vtop___024root__trace_const_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_const_0_sub_0\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);
    bufp->fullCData(oldp+376,(0U),4);
    bufp->fullCData(oldp+377,(1U),4);
    bufp->fullCData(oldp+378,(2U),4);
    bufp->fullCData(oldp+379,(3U),4);
    bufp->fullCData(oldp+380,(4U),4);
    bufp->fullCData(oldp+381,(5U),4);
    bufp->fullCData(oldp+382,(6U),4);
    bufp->fullCData(oldp+383,(7U),4);
    bufp->fullCData(oldp+384,(8U),4);
    bufp->fullIData(oldp+385,(2U),32);
    bufp->fullBit(oldp+386,(1U));
    bufp->fullCData(oldp+387,(1U),2);
    bufp->fullIData(oldp+388,(0x00000010U),32);
    bufp->fullIData(oldp+389,(4U),32);
}

VL_ATTR_COLD void Vtop___024root__trace_full_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp);

VL_ATTR_COLD void Vtop___024root__trace_full_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_full_0\n"); );
    // Body
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    Vtop___024root__trace_full_0_sub_0((&vlSymsp->TOP), bufp);
}

VL_ATTR_COLD void Vtop___024root__trace_full_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_full_0_sub_0\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);
    bufp->fullBit(oldp+1,(vlSelfRef.clk));
    bufp->fullBit(oldp+2,(vlSelfRef.reset));
    bufp->fullBit(oldp+3,(vlSelfRef.wf_push_col0));
    bufp->fullBit(oldp+4,(vlSelfRef.wf_push_col1));
    bufp->fullCData(oldp+5,(vlSelfRef.wf_data_in),8);
    bufp->fullBit(oldp+6,(vlSelfRef.wf_reset));
    bufp->fullBit(oldp+7,(vlSelfRef.init_act_valid));
    bufp->fullSData(oldp+8,(vlSelfRef.init_act_data),16);
    bufp->fullBit(oldp+9,(vlSelfRef.start_mlp));
    bufp->fullBit(oldp+10,(vlSelfRef.weights_ready));
    bufp->fullSData(oldp+11,(vlSelfRef.norm_gain),16);
    bufp->fullIData(oldp+12,(vlSelfRef.norm_bias),32);
    bufp->fullCData(oldp+13,(vlSelfRef.norm_shift),5);
    bufp->fullSData(oldp+14,(vlSelfRef.q_inv_scale),16);
    bufp->fullCData(oldp+15,(vlSelfRef.q_zero_point),8);
    bufp->fullCData(oldp+16,(vlSelfRef.state),4);
    bufp->fullCData(oldp+17,(vlSelfRef.cycle_cnt),5);
    bufp->fullCData(oldp+18,(vlSelfRef.current_layer),3);
    bufp->fullBit(oldp+19,(vlSelfRef.layer_complete));
    bufp->fullSData(oldp+20,(vlSelfRef.mmu_acc0_out),16);
    bufp->fullSData(oldp+21,(vlSelfRef.mmu_acc1_out),16);
    bufp->fullIData(oldp+22,(vlSelfRef.acc0),32);
    bufp->fullIData(oldp+23,(vlSelfRef.acc1),32);
    bufp->fullBit(oldp+24,(vlSelfRef.acc_valid));
    bufp->fullBit(oldp+25,(vlSelfRef.mlp_top__DOT__clk));
    bufp->fullBit(oldp+26,(vlSelfRef.mlp_top__DOT__reset));
    bufp->fullBit(oldp+27,(vlSelfRef.mlp_top__DOT__wf_push_col0));
    bufp->fullBit(oldp+28,(vlSelfRef.mlp_top__DOT__wf_push_col1));
    bufp->fullCData(oldp+29,(vlSelfRef.mlp_top__DOT__wf_data_in),8);
    bufp->fullBit(oldp+30,(vlSelfRef.mlp_top__DOT__wf_reset));
    bufp->fullBit(oldp+31,(vlSelfRef.mlp_top__DOT__init_act_valid));
    bufp->fullSData(oldp+32,(vlSelfRef.mlp_top__DOT__init_act_data),16);
    bufp->fullBit(oldp+33,(vlSelfRef.mlp_top__DOT__start_mlp));
    bufp->fullBit(oldp+34,(vlSelfRef.mlp_top__DOT__weights_ready));
    bufp->fullSData(oldp+35,(vlSelfRef.mlp_top__DOT__norm_gain),16);
    bufp->fullIData(oldp+36,(vlSelfRef.mlp_top__DOT__norm_bias),32);
    bufp->fullCData(oldp+37,(vlSelfRef.mlp_top__DOT__norm_shift),5);
    bufp->fullSData(oldp+38,(vlSelfRef.mlp_top__DOT__q_inv_scale),16);
    bufp->fullCData(oldp+39,(vlSelfRef.mlp_top__DOT__q_zero_point),8);
    bufp->fullCData(oldp+40,(vlSelfRef.mlp_top__DOT__state),4);
    bufp->fullCData(oldp+41,(vlSelfRef.mlp_top__DOT__cycle_cnt),5);
    bufp->fullCData(oldp+42,(vlSelfRef.mlp_top__DOT__current_layer),3);
    bufp->fullBit(oldp+43,(vlSelfRef.mlp_top__DOT__layer_complete));
    bufp->fullSData(oldp+44,(vlSelfRef.mlp_top__DOT__mmu_acc0_out),16);
    bufp->fullSData(oldp+45,(vlSelfRef.mlp_top__DOT__mmu_acc1_out),16);
    bufp->fullIData(oldp+46,(vlSelfRef.mlp_top__DOT__acc0),32);
    bufp->fullIData(oldp+47,(vlSelfRef.mlp_top__DOT__acc1),32);
    bufp->fullBit(oldp+48,(vlSelfRef.mlp_top__DOT__acc_valid));
    bufp->fullCData(oldp+49,(vlSelfRef.mlp_top__DOT__state_reg),4);
    bufp->fullCData(oldp+50,(vlSelfRef.mlp_top__DOT__cycle_cnt_reg),5);
    bufp->fullCData(oldp+51,(vlSelfRef.mlp_top__DOT__current_layer_reg),3);
    bufp->fullBit(oldp+52,(vlSelfRef.mlp_top__DOT__buffer_select));
    bufp->fullBit(oldp+53,(vlSelfRef.mlp_top__DOT__weights_loaded));
    bufp->fullBit(oldp+54,(vlSelfRef.mlp_top__DOT__en_load_weight));
    bufp->fullBit(oldp+55,(vlSelfRef.mlp_top__DOT__compute_phase));
    bufp->fullBit(oldp+56,(vlSelfRef.mlp_top__DOT__drain_phase));
    bufp->fullBit(oldp+57,(vlSelfRef.mlp_top__DOT__transfer_phase));
    bufp->fullCData(oldp+58,(vlSelfRef.mlp_top__DOT__wf_col0_out),8);
    bufp->fullCData(oldp+59,(vlSelfRef.mlp_top__DOT__wf_col1_out),8);
    bufp->fullCData(oldp+60,(vlSelfRef.mlp_top__DOT__wf_col1_raw),8);
    bufp->fullBit(oldp+61,(vlSelfRef.mlp_top__DOT__ub_a_wr_valid));
    bufp->fullBit(oldp+62,(vlSelfRef.mlp_top__DOT__ub_a_rd_ready));
    bufp->fullSData(oldp+63,(vlSelfRef.mlp_top__DOT__ub_a_wr_data),16);
    bufp->fullSData(oldp+64,(vlSelfRef.mlp_top__DOT__ub_a_rd_data),16);
    bufp->fullBit(oldp+65,(vlSelfRef.mlp_top__DOT__ub_a_wr_ready));
    bufp->fullBit(oldp+66,(vlSelfRef.mlp_top__DOT__ub_a_rd_valid));
    bufp->fullBit(oldp+67,(vlSelfRef.mlp_top__DOT__ub_a_empty));
    bufp->fullBit(oldp+68,(vlSelfRef.mlp_top__DOT__ub_b_wr_valid));
    bufp->fullBit(oldp+69,(vlSelfRef.mlp_top__DOT__ub_b_rd_ready));
    bufp->fullSData(oldp+70,(vlSelfRef.mlp_top__DOT__ub_b_wr_data),16);
    bufp->fullSData(oldp+71,(vlSelfRef.mlp_top__DOT__ub_b_rd_data),16);
    bufp->fullBit(oldp+72,(vlSelfRef.mlp_top__DOT__ub_b_wr_ready));
    bufp->fullBit(oldp+73,(vlSelfRef.mlp_top__DOT__ub_b_rd_valid));
    bufp->fullBit(oldp+74,(vlSelfRef.mlp_top__DOT__ub_b_empty));
    bufp->fullBit(oldp+75,(vlSelfRef.mlp_top__DOT__act_ub_rd_valid));
    bufp->fullSData(oldp+76,(vlSelfRef.mlp_top__DOT__act_ub_rd_data),16);
    bufp->fullBit(oldp+77,(vlSelfRef.mlp_top__DOT__act_ub_empty));
    bufp->fullCData(oldp+78,(vlSelfRef.mlp_top__DOT__act_row0_data),8);
    bufp->fullCData(oldp+79,(vlSelfRef.mlp_top__DOT__act_row1_data),8);
    bufp->fullCData(oldp+80,(vlSelfRef.mlp_top__DOT__row1_skew_reg),8);
    bufp->fullCData(oldp+81,(vlSelfRef.mlp_top__DOT__mmu_row0_in),8);
    bufp->fullCData(oldp+82,(vlSelfRef.mlp_top__DOT__mmu_row1_in),8);
    bufp->fullCData(oldp+83,(vlSelfRef.mlp_top__DOT__mmu_col0_in),8);
    bufp->fullCData(oldp+84,(vlSelfRef.mlp_top__DOT__mmu_col1_in),8);
    bufp->fullBit(oldp+85,(vlSelfRef.mlp_top__DOT__en_capture_col0));
    bufp->fullBit(oldp+86,(vlSelfRef.mlp_top__DOT__en_capture_col1));
    bufp->fullBit(oldp+87,(vlSelfRef.mlp_top__DOT__accum_en));
    bufp->fullBit(oldp+88,(vlSelfRef.mlp_top__DOT__addr_sel));
    bufp->fullBit(oldp+89,(vlSelfRef.mlp_top__DOT__mmu_valid));
    bufp->fullBit(oldp+90,(vlSelfRef.mlp_top__DOT__ap_valid));
    bufp->fullCData(oldp+91,(vlSelfRef.mlp_top__DOT__ap_data_col0),8);
    bufp->fullCData(oldp+92,(vlSelfRef.mlp_top__DOT__ap_data_col1),8);
    bufp->fullBit(oldp+93,(vlSelfRef.mlp_top__DOT__refill_valid));
    bufp->fullSData(oldp+94,(vlSelfRef.mlp_top__DOT__refill_data),16);
    bufp->fullBit(oldp+95,(vlSelfRef.mlp_top__DOT__accum_u__DOT__clk));
    bufp->fullBit(oldp+96,(vlSelfRef.mlp_top__DOT__accum_u__DOT__reset));
    bufp->fullBit(oldp+97,(vlSelfRef.mlp_top__DOT__accum_u__DOT__valid_in));
    bufp->fullBit(oldp+98,(vlSelfRef.mlp_top__DOT__accum_u__DOT__accumulator_enable));
    bufp->fullBit(oldp+99,(vlSelfRef.mlp_top__DOT__accum_u__DOT__addr_sel));
    bufp->fullSData(oldp+100,(vlSelfRef.mlp_top__DOT__accum_u__DOT__mmu_col0_in),16);
    bufp->fullSData(oldp+101,(vlSelfRef.mlp_top__DOT__accum_u__DOT__mmu_col1_in),16);
    bufp->fullIData(oldp+102,(vlSelfRef.mlp_top__DOT__accum_u__DOT__acc_col0_out),32);
    bufp->fullIData(oldp+103,(vlSelfRef.mlp_top__DOT__accum_u__DOT__acc_col1_out),32);
    bufp->fullBit(oldp+104,(vlSelfRef.mlp_top__DOT__accum_u__DOT__valid_out));
    bufp->fullBit(oldp+105,(vlSelfRef.mlp_top__DOT__accum_u__DOT__aligned_valid));
    bufp->fullSData(oldp+106,(vlSelfRef.mlp_top__DOT__accum_u__DOT__aligned_c0),16);
    bufp->fullSData(oldp+107,(vlSelfRef.mlp_top__DOT__accum_u__DOT__aligned_c1),16);
    bufp->fullBit(oldp+108,(vlSelfRef.mlp_top__DOT__accum_u__DOT__u_align__DOT__clk));
    bufp->fullBit(oldp+109,(vlSelfRef.mlp_top__DOT__accum_u__DOT__u_align__DOT__reset));
    bufp->fullBit(oldp+110,(vlSelfRef.mlp_top__DOT__accum_u__DOT__u_align__DOT__valid_in));
    bufp->fullSData(oldp+111,(vlSelfRef.mlp_top__DOT__accum_u__DOT__u_align__DOT__raw_col0),16);
    bufp->fullSData(oldp+112,(vlSelfRef.mlp_top__DOT__accum_u__DOT__u_align__DOT__raw_col1),16);
    bufp->fullBit(oldp+113,(vlSelfRef.mlp_top__DOT__accum_u__DOT__u_align__DOT__aligned_valid));
    bufp->fullSData(oldp+114,(vlSelfRef.mlp_top__DOT__accum_u__DOT__u_align__DOT__align_col0),16);
    bufp->fullSData(oldp+115,(vlSelfRef.mlp_top__DOT__accum_u__DOT__u_align__DOT__align_col1),16);
    bufp->fullSData(oldp+116,(vlSelfRef.mlp_top__DOT__accum_u__DOT__u_align__DOT__col0_delay_reg),16);
    bufp->fullBit(oldp+117,(vlSelfRef.mlp_top__DOT__accum_u__DOT__u_align__DOT__pending));
    bufp->fullBit(oldp+118,(vlSelfRef.mlp_top__DOT__accum_u__DOT__u_mem__DOT__clk));
    bufp->fullBit(oldp+119,(vlSelfRef.mlp_top__DOT__accum_u__DOT__u_mem__DOT__reset));
    bufp->fullBit(oldp+120,(vlSelfRef.mlp_top__DOT__accum_u__DOT__u_mem__DOT__enable));
    bufp->fullBit(oldp+121,(vlSelfRef.mlp_top__DOT__accum_u__DOT__u_mem__DOT__accumulator_mode));
    bufp->fullBit(oldp+122,(vlSelfRef.mlp_top__DOT__accum_u__DOT__u_mem__DOT__buffer_select));
    bufp->fullSData(oldp+123,(vlSelfRef.mlp_top__DOT__accum_u__DOT__u_mem__DOT__in_col0),16);
    bufp->fullSData(oldp+124,(vlSelfRef.mlp_top__DOT__accum_u__DOT__u_mem__DOT__in_col1),16);
    bufp->fullBit(oldp+125,(vlSelfRef.mlp_top__DOT__accum_u__DOT__u_mem__DOT__valid_out));
    bufp->fullIData(oldp+126,(vlSelfRef.mlp_top__DOT__accum_u__DOT__u_mem__DOT__out_col0),32);
    bufp->fullIData(oldp+127,(vlSelfRef.mlp_top__DOT__accum_u__DOT__u_mem__DOT__out_col1),32);
    bufp->fullIData(oldp+128,(vlSelfRef.mlp_top__DOT__accum_u__DOT__u_mem__DOT__mem_buff0_col0),32);
    bufp->fullIData(oldp+129,(vlSelfRef.mlp_top__DOT__accum_u__DOT__u_mem__DOT__mem_buff0_col1),32);
    bufp->fullIData(oldp+130,(vlSelfRef.mlp_top__DOT__accum_u__DOT__u_mem__DOT__mem_buff1_col0),32);
    bufp->fullIData(oldp+131,(vlSelfRef.mlp_top__DOT__accum_u__DOT__u_mem__DOT__mem_buff1_col1),32);
    bufp->fullBit(oldp+132,(vlSelfRef.mlp_top__DOT__ap_col0__DOT__clk));
    bufp->fullBit(oldp+133,(vlSelfRef.mlp_top__DOT__ap_col0__DOT__reset));
    bufp->fullBit(oldp+134,(vlSelfRef.mlp_top__DOT__ap_col0__DOT__valid_in));
    bufp->fullIData(oldp+135,(vlSelfRef.mlp_top__DOT__ap_col0__DOT__acc_in),32);
    bufp->fullIData(oldp+136,(vlSelfRef.mlp_top__DOT__ap_col0__DOT__target_in),32);
    bufp->fullSData(oldp+137,(vlSelfRef.mlp_top__DOT__ap_col0__DOT__norm_gain),16);
    bufp->fullIData(oldp+138,(vlSelfRef.mlp_top__DOT__ap_col0__DOT__norm_bias),32);
    bufp->fullCData(oldp+139,(vlSelfRef.mlp_top__DOT__ap_col0__DOT__norm_shift),5);
    bufp->fullSData(oldp+140,(vlSelfRef.mlp_top__DOT__ap_col0__DOT__q_inv_scale),16);
    bufp->fullCData(oldp+141,(vlSelfRef.mlp_top__DOT__ap_col0__DOT__q_zero_point),8);
    bufp->fullBit(oldp+142,(vlSelfRef.mlp_top__DOT__ap_col0__DOT__valid_out));
    bufp->fullCData(oldp+143,(vlSelfRef.mlp_top__DOT__ap_col0__DOT__ub_data_out),8);
    bufp->fullBit(oldp+144,(vlSelfRef.mlp_top__DOT__ap_col0__DOT__loss_valid));
    bufp->fullIData(oldp+145,(vlSelfRef.mlp_top__DOT__ap_col0__DOT__loss_out),32);
    bufp->fullBit(oldp+146,(vlSelfRef.mlp_top__DOT__ap_col0__DOT__s1_valid));
    bufp->fullIData(oldp+147,(vlSelfRef.mlp_top__DOT__ap_col0__DOT__s1_data),32);
    bufp->fullIData(oldp+148,(vlSelfRef.mlp_top__DOT__ap_col0__DOT__target_d1),32);
    bufp->fullBit(oldp+149,(vlSelfRef.mlp_top__DOT__ap_col0__DOT__s2_valid));
    bufp->fullIData(oldp+150,(vlSelfRef.mlp_top__DOT__ap_col0__DOT__s2_data),32);
    bufp->fullCData(oldp+151,(vlSelfRef.mlp_top__DOT__ap_col0__DOT__ub_q_reg),8);
    bufp->fullBit(oldp+152,(vlSelfRef.mlp_top__DOT__ap_col0__DOT__valid_reg));
    bufp->fullQData(oldp+153,(vlSelfRef.mlp_top__DOT__ap_col0__DOT__mult),48);
    bufp->fullQData(oldp+155,(vlSelfRef.mlp_top__DOT__ap_col0__DOT__mult_rounded),48);
    bufp->fullIData(oldp+157,(vlSelfRef.mlp_top__DOT__ap_col0__DOT__scaled),32);
    bufp->fullIData(oldp+158,(vlSelfRef.mlp_top__DOT__ap_col0__DOT__biased),32);
    bufp->fullBit(oldp+159,(vlSelfRef.mlp_top__DOT__ap_col0__DOT__act_u__DOT__clk));
    bufp->fullBit(oldp+160,(vlSelfRef.mlp_top__DOT__ap_col0__DOT__act_u__DOT__reset));
    bufp->fullBit(oldp+161,(vlSelfRef.mlp_top__DOT__ap_col0__DOT__act_u__DOT__valid_in));
    bufp->fullIData(oldp+162,(vlSelfRef.mlp_top__DOT__ap_col0__DOT__act_u__DOT__data_in),32);
    bufp->fullBit(oldp+163,(vlSelfRef.mlp_top__DOT__ap_col0__DOT__act_u__DOT__valid_out));
    bufp->fullIData(oldp+164,(vlSelfRef.mlp_top__DOT__ap_col0__DOT__act_u__DOT__data_out),32);
    bufp->fullBit(oldp+165,(vlSelfRef.mlp_top__DOT__ap_col0__DOT__loss_u__DOT__clk));
    bufp->fullBit(oldp+166,(vlSelfRef.mlp_top__DOT__ap_col0__DOT__loss_u__DOT__reset));
    bufp->fullBit(oldp+167,(vlSelfRef.mlp_top__DOT__ap_col0__DOT__loss_u__DOT__valid_in));
    bufp->fullIData(oldp+168,(vlSelfRef.mlp_top__DOT__ap_col0__DOT__loss_u__DOT__data_in),32);
    bufp->fullIData(oldp+169,(vlSelfRef.mlp_top__DOT__ap_col0__DOT__loss_u__DOT__target_in),32);
    bufp->fullBit(oldp+170,(vlSelfRef.mlp_top__DOT__ap_col0__DOT__loss_u__DOT__valid_out));
    bufp->fullIData(oldp+171,(vlSelfRef.mlp_top__DOT__ap_col0__DOT__loss_u__DOT__loss_out),32);
    bufp->fullIData(oldp+172,(vlSelfRef.mlp_top__DOT__ap_col0__DOT__loss_u__DOT__diff),32);
    bufp->fullIData(oldp+173,(vlSelfRef.mlp_top__DOT__ap_col0__DOT__loss_u__DOT__abs_diff),32);
    bufp->fullBit(oldp+174,(vlSelfRef.mlp_top__DOT__ap_col0__DOT__norm_u__DOT__clk));
    bufp->fullBit(oldp+175,(vlSelfRef.mlp_top__DOT__ap_col0__DOT__norm_u__DOT__reset));
    bufp->fullBit(oldp+176,(vlSelfRef.mlp_top__DOT__ap_col0__DOT__norm_u__DOT__valid_in));
    bufp->fullIData(oldp+177,(vlSelfRef.mlp_top__DOT__ap_col0__DOT__norm_u__DOT__data_in),32);
    bufp->fullSData(oldp+178,(vlSelfRef.mlp_top__DOT__ap_col0__DOT__norm_u__DOT__gain),16);
    bufp->fullIData(oldp+179,(vlSelfRef.mlp_top__DOT__ap_col0__DOT__norm_u__DOT__bias),32);
    bufp->fullCData(oldp+180,(vlSelfRef.mlp_top__DOT__ap_col0__DOT__norm_u__DOT__shift),5);
    bufp->fullBit(oldp+181,(vlSelfRef.mlp_top__DOT__ap_col0__DOT__norm_u__DOT__valid_out));
    bufp->fullIData(oldp+182,(vlSelfRef.mlp_top__DOT__ap_col0__DOT__norm_u__DOT__data_out),32);
    bufp->fullQData(oldp+183,(vlSelfRef.mlp_top__DOT__ap_col0__DOT__norm_u__DOT__mult),48);
    bufp->fullQData(oldp+185,(vlSelfRef.mlp_top__DOT__ap_col0__DOT__norm_u__DOT__shifted),48);
    bufp->fullBit(oldp+187,(vlSelfRef.mlp_top__DOT__ap_col1__DOT__clk));
    bufp->fullBit(oldp+188,(vlSelfRef.mlp_top__DOT__ap_col1__DOT__reset));
    bufp->fullBit(oldp+189,(vlSelfRef.mlp_top__DOT__ap_col1__DOT__valid_in));
    bufp->fullIData(oldp+190,(vlSelfRef.mlp_top__DOT__ap_col1__DOT__acc_in),32);
    bufp->fullIData(oldp+191,(vlSelfRef.mlp_top__DOT__ap_col1__DOT__target_in),32);
    bufp->fullSData(oldp+192,(vlSelfRef.mlp_top__DOT__ap_col1__DOT__norm_gain),16);
    bufp->fullIData(oldp+193,(vlSelfRef.mlp_top__DOT__ap_col1__DOT__norm_bias),32);
    bufp->fullCData(oldp+194,(vlSelfRef.mlp_top__DOT__ap_col1__DOT__norm_shift),5);
    bufp->fullSData(oldp+195,(vlSelfRef.mlp_top__DOT__ap_col1__DOT__q_inv_scale),16);
    bufp->fullCData(oldp+196,(vlSelfRef.mlp_top__DOT__ap_col1__DOT__q_zero_point),8);
    bufp->fullBit(oldp+197,(vlSelfRef.mlp_top__DOT__ap_col1__DOT__valid_out));
    bufp->fullCData(oldp+198,(vlSelfRef.mlp_top__DOT__ap_col1__DOT__ub_data_out),8);
    bufp->fullBit(oldp+199,(vlSelfRef.mlp_top__DOT__ap_col1__DOT__loss_valid));
    bufp->fullIData(oldp+200,(vlSelfRef.mlp_top__DOT__ap_col1__DOT__loss_out),32);
    bufp->fullBit(oldp+201,(vlSelfRef.mlp_top__DOT__ap_col1__DOT__s1_valid));
    bufp->fullIData(oldp+202,(vlSelfRef.mlp_top__DOT__ap_col1__DOT__s1_data),32);
    bufp->fullIData(oldp+203,(vlSelfRef.mlp_top__DOT__ap_col1__DOT__target_d1),32);
    bufp->fullBit(oldp+204,(vlSelfRef.mlp_top__DOT__ap_col1__DOT__s2_valid));
    bufp->fullIData(oldp+205,(vlSelfRef.mlp_top__DOT__ap_col1__DOT__s2_data),32);
    bufp->fullCData(oldp+206,(vlSelfRef.mlp_top__DOT__ap_col1__DOT__ub_q_reg),8);
    bufp->fullBit(oldp+207,(vlSelfRef.mlp_top__DOT__ap_col1__DOT__valid_reg));
    bufp->fullQData(oldp+208,(vlSelfRef.mlp_top__DOT__ap_col1__DOT__mult),48);
    bufp->fullQData(oldp+210,(vlSelfRef.mlp_top__DOT__ap_col1__DOT__mult_rounded),48);
    bufp->fullIData(oldp+212,(vlSelfRef.mlp_top__DOT__ap_col1__DOT__scaled),32);
    bufp->fullIData(oldp+213,(vlSelfRef.mlp_top__DOT__ap_col1__DOT__biased),32);
    bufp->fullBit(oldp+214,(vlSelfRef.mlp_top__DOT__ap_col1__DOT__act_u__DOT__clk));
    bufp->fullBit(oldp+215,(vlSelfRef.mlp_top__DOT__ap_col1__DOT__act_u__DOT__reset));
    bufp->fullBit(oldp+216,(vlSelfRef.mlp_top__DOT__ap_col1__DOT__act_u__DOT__valid_in));
    bufp->fullIData(oldp+217,(vlSelfRef.mlp_top__DOT__ap_col1__DOT__act_u__DOT__data_in),32);
    bufp->fullBit(oldp+218,(vlSelfRef.mlp_top__DOT__ap_col1__DOT__act_u__DOT__valid_out));
    bufp->fullIData(oldp+219,(vlSelfRef.mlp_top__DOT__ap_col1__DOT__act_u__DOT__data_out),32);
    bufp->fullBit(oldp+220,(vlSelfRef.mlp_top__DOT__ap_col1__DOT__loss_u__DOT__clk));
    bufp->fullBit(oldp+221,(vlSelfRef.mlp_top__DOT__ap_col1__DOT__loss_u__DOT__reset));
    bufp->fullBit(oldp+222,(vlSelfRef.mlp_top__DOT__ap_col1__DOT__loss_u__DOT__valid_in));
    bufp->fullIData(oldp+223,(vlSelfRef.mlp_top__DOT__ap_col1__DOT__loss_u__DOT__data_in),32);
    bufp->fullIData(oldp+224,(vlSelfRef.mlp_top__DOT__ap_col1__DOT__loss_u__DOT__target_in),32);
    bufp->fullBit(oldp+225,(vlSelfRef.mlp_top__DOT__ap_col1__DOT__loss_u__DOT__valid_out));
    bufp->fullIData(oldp+226,(vlSelfRef.mlp_top__DOT__ap_col1__DOT__loss_u__DOT__loss_out),32);
    bufp->fullIData(oldp+227,(vlSelfRef.mlp_top__DOT__ap_col1__DOT__loss_u__DOT__diff),32);
    bufp->fullIData(oldp+228,(vlSelfRef.mlp_top__DOT__ap_col1__DOT__loss_u__DOT__abs_diff),32);
    bufp->fullBit(oldp+229,(vlSelfRef.mlp_top__DOT__ap_col1__DOT__norm_u__DOT__clk));
    bufp->fullBit(oldp+230,(vlSelfRef.mlp_top__DOT__ap_col1__DOT__norm_u__DOT__reset));
    bufp->fullBit(oldp+231,(vlSelfRef.mlp_top__DOT__ap_col1__DOT__norm_u__DOT__valid_in));
    bufp->fullIData(oldp+232,(vlSelfRef.mlp_top__DOT__ap_col1__DOT__norm_u__DOT__data_in),32);
    bufp->fullSData(oldp+233,(vlSelfRef.mlp_top__DOT__ap_col1__DOT__norm_u__DOT__gain),16);
    bufp->fullIData(oldp+234,(vlSelfRef.mlp_top__DOT__ap_col1__DOT__norm_u__DOT__bias),32);
    bufp->fullCData(oldp+235,(vlSelfRef.mlp_top__DOT__ap_col1__DOT__norm_u__DOT__shift),5);
    bufp->fullBit(oldp+236,(vlSelfRef.mlp_top__DOT__ap_col1__DOT__norm_u__DOT__valid_out));
    bufp->fullIData(oldp+237,(vlSelfRef.mlp_top__DOT__ap_col1__DOT__norm_u__DOT__data_out),32);
    bufp->fullQData(oldp+238,(vlSelfRef.mlp_top__DOT__ap_col1__DOT__norm_u__DOT__mult),48);
    bufp->fullQData(oldp+240,(vlSelfRef.mlp_top__DOT__ap_col1__DOT__norm_u__DOT__shifted),48);
    bufp->fullBit(oldp+242,(vlSelfRef.mlp_top__DOT__mmu_u__DOT__clk));
    bufp->fullBit(oldp+243,(vlSelfRef.mlp_top__DOT__mmu_u__DOT__reset));
    bufp->fullBit(oldp+244,(vlSelfRef.mlp_top__DOT__mmu_u__DOT__en_weight_pass));
    bufp->fullBit(oldp+245,(vlSelfRef.mlp_top__DOT__mmu_u__DOT__en_capture_col0));
    bufp->fullBit(oldp+246,(vlSelfRef.mlp_top__DOT__mmu_u__DOT__en_capture_col1));
    bufp->fullCData(oldp+247,(vlSelfRef.mlp_top__DOT__mmu_u__DOT__row0_in),8);
    bufp->fullCData(oldp+248,(vlSelfRef.mlp_top__DOT__mmu_u__DOT__row1_in),8);
    bufp->fullCData(oldp+249,(vlSelfRef.mlp_top__DOT__mmu_u__DOT__col0_in),8);
    bufp->fullCData(oldp+250,(vlSelfRef.mlp_top__DOT__mmu_u__DOT__col1_in),8);
    bufp->fullSData(oldp+251,(vlSelfRef.mlp_top__DOT__mmu_u__DOT__acc0_out),16);
    bufp->fullSData(oldp+252,(vlSelfRef.mlp_top__DOT__mmu_u__DOT__acc1_out),16);
    bufp->fullCData(oldp+253,(vlSelfRef.mlp_top__DOT__mmu_u__DOT__pe00_01_act),8);
    bufp->fullCData(oldp+254,(vlSelfRef.mlp_top__DOT__mmu_u__DOT__pe10_11_act),8);
    bufp->fullSData(oldp+255,(vlSelfRef.mlp_top__DOT__mmu_u__DOT__pe00_10_psum),16);
    bufp->fullSData(oldp+256,(vlSelfRef.mlp_top__DOT__mmu_u__DOT__pe01_11_psum),16);
    bufp->fullBit(oldp+257,(vlSelfRef.mlp_top__DOT__mmu_u__DOT__pe00__DOT__clk));
    bufp->fullBit(oldp+258,(vlSelfRef.mlp_top__DOT__mmu_u__DOT__pe00__DOT__reset));
    bufp->fullBit(oldp+259,(vlSelfRef.mlp_top__DOT__mmu_u__DOT__pe00__DOT__en_weight_pass));
    bufp->fullBit(oldp+260,(vlSelfRef.mlp_top__DOT__mmu_u__DOT__pe00__DOT__en_weight_capture));
    bufp->fullCData(oldp+261,(vlSelfRef.mlp_top__DOT__mmu_u__DOT__pe00__DOT__in_act),8);
    bufp->fullSData(oldp+262,(vlSelfRef.mlp_top__DOT__mmu_u__DOT__pe00__DOT__in_psum),16);
    bufp->fullCData(oldp+263,(vlSelfRef.mlp_top__DOT__mmu_u__DOT__pe00__DOT__out_act),8);
    bufp->fullSData(oldp+264,(vlSelfRef.mlp_top__DOT__mmu_u__DOT__pe00__DOT__out_psum),16);
    bufp->fullCData(oldp+265,(vlSelfRef.mlp_top__DOT__mmu_u__DOT__pe00__DOT__weight),8);
    bufp->fullBit(oldp+266,(vlSelfRef.mlp_top__DOT__mmu_u__DOT__pe01__DOT__clk));
    bufp->fullBit(oldp+267,(vlSelfRef.mlp_top__DOT__mmu_u__DOT__pe01__DOT__reset));
    bufp->fullBit(oldp+268,(vlSelfRef.mlp_top__DOT__mmu_u__DOT__pe01__DOT__en_weight_pass));
    bufp->fullBit(oldp+269,(vlSelfRef.mlp_top__DOT__mmu_u__DOT__pe01__DOT__en_weight_capture));
    bufp->fullCData(oldp+270,(vlSelfRef.mlp_top__DOT__mmu_u__DOT__pe01__DOT__in_act),8);
    bufp->fullSData(oldp+271,(vlSelfRef.mlp_top__DOT__mmu_u__DOT__pe01__DOT__in_psum),16);
    bufp->fullCData(oldp+272,(vlSelfRef.mlp_top__DOT__mmu_u__DOT__pe01__DOT__out_act),8);
    bufp->fullSData(oldp+273,(vlSelfRef.mlp_top__DOT__mmu_u__DOT__pe01__DOT__out_psum),16);
    bufp->fullCData(oldp+274,(vlSelfRef.mlp_top__DOT__mmu_u__DOT__pe01__DOT__weight),8);
    bufp->fullBit(oldp+275,(vlSelfRef.mlp_top__DOT__mmu_u__DOT__pe10__DOT__clk));
    bufp->fullBit(oldp+276,(vlSelfRef.mlp_top__DOT__mmu_u__DOT__pe10__DOT__reset));
    bufp->fullBit(oldp+277,(vlSelfRef.mlp_top__DOT__mmu_u__DOT__pe10__DOT__en_weight_pass));
    bufp->fullBit(oldp+278,(vlSelfRef.mlp_top__DOT__mmu_u__DOT__pe10__DOT__en_weight_capture));
    bufp->fullCData(oldp+279,(vlSelfRef.mlp_top__DOT__mmu_u__DOT__pe10__DOT__in_act),8);
    bufp->fullSData(oldp+280,(vlSelfRef.mlp_top__DOT__mmu_u__DOT__pe10__DOT__in_psum),16);
    bufp->fullCData(oldp+281,(vlSelfRef.mlp_top__DOT__mmu_u__DOT__pe10__DOT__out_act),8);
    bufp->fullSData(oldp+282,(vlSelfRef.mlp_top__DOT__mmu_u__DOT__pe10__DOT__out_psum),16);
    bufp->fullCData(oldp+283,(vlSelfRef.mlp_top__DOT__mmu_u__DOT__pe10__DOT__weight),8);
    bufp->fullBit(oldp+284,(vlSelfRef.mlp_top__DOT__mmu_u__DOT__pe11__DOT__clk));
    bufp->fullBit(oldp+285,(vlSelfRef.mlp_top__DOT__mmu_u__DOT__pe11__DOT__reset));
    bufp->fullBit(oldp+286,(vlSelfRef.mlp_top__DOT__mmu_u__DOT__pe11__DOT__en_weight_pass));
    bufp->fullBit(oldp+287,(vlSelfRef.mlp_top__DOT__mmu_u__DOT__pe11__DOT__en_weight_capture));
    bufp->fullCData(oldp+288,(vlSelfRef.mlp_top__DOT__mmu_u__DOT__pe11__DOT__in_act),8);
    bufp->fullSData(oldp+289,(vlSelfRef.mlp_top__DOT__mmu_u__DOT__pe11__DOT__in_psum),16);
    bufp->fullCData(oldp+290,(vlSelfRef.mlp_top__DOT__mmu_u__DOT__pe11__DOT__out_act),8);
    bufp->fullSData(oldp+291,(vlSelfRef.mlp_top__DOT__mmu_u__DOT__pe11__DOT__out_psum),16);
    bufp->fullCData(oldp+292,(vlSelfRef.mlp_top__DOT__mmu_u__DOT__pe11__DOT__weight),8);
    bufp->fullBit(oldp+293,(vlSelfRef.mlp_top__DOT__ub_a__DOT__clk));
    bufp->fullBit(oldp+294,(vlSelfRef.mlp_top__DOT__ub_a__DOT__reset));
    bufp->fullBit(oldp+295,(vlSelfRef.mlp_top__DOT__ub_a__DOT__wr_valid));
    bufp->fullSData(oldp+296,(vlSelfRef.mlp_top__DOT__ub_a__DOT__wr_data),16);
    bufp->fullBit(oldp+297,(vlSelfRef.mlp_top__DOT__ub_a__DOT__wr_ready));
    bufp->fullBit(oldp+298,(vlSelfRef.mlp_top__DOT__ub_a__DOT__rd_ready));
    bufp->fullBit(oldp+299,(vlSelfRef.mlp_top__DOT__ub_a__DOT__rd_valid));
    bufp->fullSData(oldp+300,(vlSelfRef.mlp_top__DOT__ub_a__DOT__rd_data),16);
    bufp->fullBit(oldp+301,(vlSelfRef.mlp_top__DOT__ub_a__DOT__full));
    bufp->fullBit(oldp+302,(vlSelfRef.mlp_top__DOT__ub_a__DOT__empty));
    bufp->fullCData(oldp+303,(vlSelfRef.mlp_top__DOT__ub_a__DOT__count),5);
    bufp->fullSData(oldp+304,(vlSelfRef.mlp_top__DOT__ub_a__DOT__mem[0]),16);
    bufp->fullSData(oldp+305,(vlSelfRef.mlp_top__DOT__ub_a__DOT__mem[1]),16);
    bufp->fullSData(oldp+306,(vlSelfRef.mlp_top__DOT__ub_a__DOT__mem[2]),16);
    bufp->fullSData(oldp+307,(vlSelfRef.mlp_top__DOT__ub_a__DOT__mem[3]),16);
    bufp->fullSData(oldp+308,(vlSelfRef.mlp_top__DOT__ub_a__DOT__mem[4]),16);
    bufp->fullSData(oldp+309,(vlSelfRef.mlp_top__DOT__ub_a__DOT__mem[5]),16);
    bufp->fullSData(oldp+310,(vlSelfRef.mlp_top__DOT__ub_a__DOT__mem[6]),16);
    bufp->fullSData(oldp+311,(vlSelfRef.mlp_top__DOT__ub_a__DOT__mem[7]),16);
    bufp->fullSData(oldp+312,(vlSelfRef.mlp_top__DOT__ub_a__DOT__mem[8]),16);
    bufp->fullSData(oldp+313,(vlSelfRef.mlp_top__DOT__ub_a__DOT__mem[9]),16);
    bufp->fullSData(oldp+314,(vlSelfRef.mlp_top__DOT__ub_a__DOT__mem[10]),16);
    bufp->fullSData(oldp+315,(vlSelfRef.mlp_top__DOT__ub_a__DOT__mem[11]),16);
    bufp->fullSData(oldp+316,(vlSelfRef.mlp_top__DOT__ub_a__DOT__mem[12]),16);
    bufp->fullSData(oldp+317,(vlSelfRef.mlp_top__DOT__ub_a__DOT__mem[13]),16);
    bufp->fullSData(oldp+318,(vlSelfRef.mlp_top__DOT__ub_a__DOT__mem[14]),16);
    bufp->fullSData(oldp+319,(vlSelfRef.mlp_top__DOT__ub_a__DOT__mem[15]),16);
    bufp->fullCData(oldp+320,(vlSelfRef.mlp_top__DOT__ub_a__DOT__wr_ptr),4);
    bufp->fullCData(oldp+321,(vlSelfRef.mlp_top__DOT__ub_a__DOT__rd_ptr),4);
    bufp->fullBit(oldp+322,(vlSelfRef.mlp_top__DOT__ub_a__DOT__do_write));
    bufp->fullBit(oldp+323,(vlSelfRef.mlp_top__DOT__ub_a__DOT__do_read));
    bufp->fullBit(oldp+324,(vlSelfRef.mlp_top__DOT__ub_b__DOT__clk));
    bufp->fullBit(oldp+325,(vlSelfRef.mlp_top__DOT__ub_b__DOT__reset));
    bufp->fullBit(oldp+326,(vlSelfRef.mlp_top__DOT__ub_b__DOT__wr_valid));
    bufp->fullSData(oldp+327,(vlSelfRef.mlp_top__DOT__ub_b__DOT__wr_data),16);
    bufp->fullBit(oldp+328,(vlSelfRef.mlp_top__DOT__ub_b__DOT__wr_ready));
    bufp->fullBit(oldp+329,(vlSelfRef.mlp_top__DOT__ub_b__DOT__rd_ready));
    bufp->fullBit(oldp+330,(vlSelfRef.mlp_top__DOT__ub_b__DOT__rd_valid));
    bufp->fullSData(oldp+331,(vlSelfRef.mlp_top__DOT__ub_b__DOT__rd_data),16);
    bufp->fullBit(oldp+332,(vlSelfRef.mlp_top__DOT__ub_b__DOT__full));
    bufp->fullBit(oldp+333,(vlSelfRef.mlp_top__DOT__ub_b__DOT__empty));
    bufp->fullCData(oldp+334,(vlSelfRef.mlp_top__DOT__ub_b__DOT__count),5);
    bufp->fullSData(oldp+335,(vlSelfRef.mlp_top__DOT__ub_b__DOT__mem[0]),16);
    bufp->fullSData(oldp+336,(vlSelfRef.mlp_top__DOT__ub_b__DOT__mem[1]),16);
    bufp->fullSData(oldp+337,(vlSelfRef.mlp_top__DOT__ub_b__DOT__mem[2]),16);
    bufp->fullSData(oldp+338,(vlSelfRef.mlp_top__DOT__ub_b__DOT__mem[3]),16);
    bufp->fullSData(oldp+339,(vlSelfRef.mlp_top__DOT__ub_b__DOT__mem[4]),16);
    bufp->fullSData(oldp+340,(vlSelfRef.mlp_top__DOT__ub_b__DOT__mem[5]),16);
    bufp->fullSData(oldp+341,(vlSelfRef.mlp_top__DOT__ub_b__DOT__mem[6]),16);
    bufp->fullSData(oldp+342,(vlSelfRef.mlp_top__DOT__ub_b__DOT__mem[7]),16);
    bufp->fullSData(oldp+343,(vlSelfRef.mlp_top__DOT__ub_b__DOT__mem[8]),16);
    bufp->fullSData(oldp+344,(vlSelfRef.mlp_top__DOT__ub_b__DOT__mem[9]),16);
    bufp->fullSData(oldp+345,(vlSelfRef.mlp_top__DOT__ub_b__DOT__mem[10]),16);
    bufp->fullSData(oldp+346,(vlSelfRef.mlp_top__DOT__ub_b__DOT__mem[11]),16);
    bufp->fullSData(oldp+347,(vlSelfRef.mlp_top__DOT__ub_b__DOT__mem[12]),16);
    bufp->fullSData(oldp+348,(vlSelfRef.mlp_top__DOT__ub_b__DOT__mem[13]),16);
    bufp->fullSData(oldp+349,(vlSelfRef.mlp_top__DOT__ub_b__DOT__mem[14]),16);
    bufp->fullSData(oldp+350,(vlSelfRef.mlp_top__DOT__ub_b__DOT__mem[15]),16);
    bufp->fullCData(oldp+351,(vlSelfRef.mlp_top__DOT__ub_b__DOT__wr_ptr),4);
    bufp->fullCData(oldp+352,(vlSelfRef.mlp_top__DOT__ub_b__DOT__rd_ptr),4);
    bufp->fullBit(oldp+353,(vlSelfRef.mlp_top__DOT__ub_b__DOT__do_write));
    bufp->fullBit(oldp+354,(vlSelfRef.mlp_top__DOT__ub_b__DOT__do_read));
    bufp->fullBit(oldp+355,(vlSelfRef.mlp_top__DOT__weight_fifo_u__DOT__clk));
    bufp->fullBit(oldp+356,(vlSelfRef.mlp_top__DOT__weight_fifo_u__DOT__reset));
    bufp->fullBit(oldp+357,(vlSelfRef.mlp_top__DOT__weight_fifo_u__DOT__push_col0));
    bufp->fullBit(oldp+358,(vlSelfRef.mlp_top__DOT__weight_fifo_u__DOT__push_col1));
    bufp->fullCData(oldp+359,(vlSelfRef.mlp_top__DOT__weight_fifo_u__DOT__data_in),8);
    bufp->fullBit(oldp+360,(vlSelfRef.mlp_top__DOT__weight_fifo_u__DOT__pop));
    bufp->fullCData(oldp+361,(vlSelfRef.mlp_top__DOT__weight_fifo_u__DOT__col0_out),8);
    bufp->fullCData(oldp+362,(vlSelfRef.mlp_top__DOT__weight_fifo_u__DOT__col1_out),8);
    bufp->fullCData(oldp+363,(vlSelfRef.mlp_top__DOT__weight_fifo_u__DOT__col1_raw),8);
    bufp->fullCData(oldp+364,(vlSelfRef.mlp_top__DOT__weight_fifo_u__DOT__queue0[0]),8);
    bufp->fullCData(oldp+365,(vlSelfRef.mlp_top__DOT__weight_fifo_u__DOT__queue0[1]),8);
    bufp->fullCData(oldp+366,(vlSelfRef.mlp_top__DOT__weight_fifo_u__DOT__queue0[2]),8);
    bufp->fullCData(oldp+367,(vlSelfRef.mlp_top__DOT__weight_fifo_u__DOT__queue0[3]),8);
    bufp->fullCData(oldp+368,(vlSelfRef.mlp_top__DOT__weight_fifo_u__DOT__queue1[0]),8);
    bufp->fullCData(oldp+369,(vlSelfRef.mlp_top__DOT__weight_fifo_u__DOT__queue1[1]),8);
    bufp->fullCData(oldp+370,(vlSelfRef.mlp_top__DOT__weight_fifo_u__DOT__queue1[2]),8);
    bufp->fullCData(oldp+371,(vlSelfRef.mlp_top__DOT__weight_fifo_u__DOT__queue1[3]),8);
    bufp->fullCData(oldp+372,(vlSelfRef.mlp_top__DOT__weight_fifo_u__DOT__wr_ptr0),2);
    bufp->fullCData(oldp+373,(vlSelfRef.mlp_top__DOT__weight_fifo_u__DOT__rd_ptr0),2);
    bufp->fullCData(oldp+374,(vlSelfRef.mlp_top__DOT__weight_fifo_u__DOT__wr_ptr1),2);
    bufp->fullCData(oldp+375,(vlSelfRef.mlp_top__DOT__weight_fifo_u__DOT__rd_ptr1),2);
}
