// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtop.h for the primary calling header

#ifndef VERILATED_VTOP___024ROOT_H_
#define VERILATED_VTOP___024ROOT_H_  // guard

#include "verilated.h"


class Vtop__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtop___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk,0,0);
        VL_IN8(reset,0,0);
        VL_IN8(wf_reset,0,0);
        VL_IN8(wf_push_col0,0,0);
        VL_IN8(wf_push_col1,0,0);
        VL_IN8(wf_data_in,7,0);
        VL_IN8(init_act_valid,0,0);
        VL_IN8(start_mlp,0,0);
        VL_IN8(weights_ready,0,0);
        VL_IN8(norm_shift,4,0);
        VL_IN8(q_zero_point,7,0);
        VL_OUT8(state,3,0);
        VL_OUT8(cycle_cnt,4,0);
        VL_OUT8(current_layer,2,0);
        VL_OUT8(layer_complete,0,0);
        VL_OUT8(acc_valid,0,0);
        CData/*0:0*/ mlp_top__DOT__clk;
        CData/*0:0*/ mlp_top__DOT__reset;
        CData/*0:0*/ mlp_top__DOT__wf_push_col0;
        CData/*0:0*/ mlp_top__DOT__wf_push_col1;
        CData/*7:0*/ mlp_top__DOT__wf_data_in;
        CData/*0:0*/ mlp_top__DOT__wf_reset;
        CData/*0:0*/ mlp_top__DOT__init_act_valid;
        CData/*0:0*/ mlp_top__DOT__start_mlp;
        CData/*0:0*/ mlp_top__DOT__weights_ready;
        CData/*4:0*/ mlp_top__DOT__norm_shift;
        CData/*7:0*/ mlp_top__DOT__q_zero_point;
        CData/*3:0*/ mlp_top__DOT__state;
        CData/*4:0*/ mlp_top__DOT__cycle_cnt;
        CData/*2:0*/ mlp_top__DOT__current_layer;
        CData/*0:0*/ mlp_top__DOT__layer_complete;
        CData/*0:0*/ mlp_top__DOT__acc_valid;
        CData/*3:0*/ mlp_top__DOT__state_reg;
        CData/*4:0*/ mlp_top__DOT__cycle_cnt_reg;
        CData/*2:0*/ mlp_top__DOT__current_layer_reg;
        CData/*0:0*/ mlp_top__DOT__buffer_select;
        CData/*0:0*/ mlp_top__DOT__weights_loaded;
        CData/*0:0*/ mlp_top__DOT__en_load_weight;
        CData/*0:0*/ mlp_top__DOT__compute_phase;
        CData/*0:0*/ mlp_top__DOT__drain_phase;
        CData/*0:0*/ mlp_top__DOT__transfer_phase;
        CData/*7:0*/ mlp_top__DOT__wf_col0_out;
        CData/*7:0*/ mlp_top__DOT__wf_col1_out;
        CData/*7:0*/ mlp_top__DOT__wf_col1_raw;
        CData/*0:0*/ mlp_top__DOT__ub_a_wr_valid;
        CData/*0:0*/ mlp_top__DOT__ub_a_rd_ready;
        CData/*0:0*/ mlp_top__DOT__ub_a_wr_ready;
        CData/*0:0*/ mlp_top__DOT__ub_a_rd_valid;
        CData/*0:0*/ mlp_top__DOT__ub_a_empty;
        CData/*0:0*/ mlp_top__DOT__ub_b_wr_valid;
        CData/*0:0*/ mlp_top__DOT__ub_b_rd_ready;
        CData/*0:0*/ mlp_top__DOT__ub_b_wr_ready;
        CData/*0:0*/ mlp_top__DOT__ub_b_rd_valid;
        CData/*0:0*/ mlp_top__DOT__ub_b_empty;
        CData/*0:0*/ mlp_top__DOT__act_ub_rd_valid;
        CData/*0:0*/ mlp_top__DOT__act_ub_empty;
        CData/*7:0*/ mlp_top__DOT__act_row0_data;
        CData/*7:0*/ mlp_top__DOT__act_row1_data;
        CData/*7:0*/ mlp_top__DOT__row1_skew_reg;
        CData/*7:0*/ mlp_top__DOT__mmu_row0_in;
        CData/*7:0*/ mlp_top__DOT__mmu_row1_in;
        CData/*7:0*/ mlp_top__DOT__mmu_col0_in;
        CData/*7:0*/ mlp_top__DOT__mmu_col1_in;
        CData/*0:0*/ mlp_top__DOT__en_capture_col0;
    };
    struct {
        CData/*0:0*/ mlp_top__DOT__en_capture_col1;
        CData/*0:0*/ mlp_top__DOT__accum_en;
        CData/*0:0*/ mlp_top__DOT__addr_sel;
        CData/*0:0*/ mlp_top__DOT__mmu_valid;
        CData/*0:0*/ mlp_top__DOT__ap_valid;
        CData/*7:0*/ mlp_top__DOT__ap_data_col0;
        CData/*7:0*/ mlp_top__DOT__ap_data_col1;
        CData/*0:0*/ mlp_top__DOT__refill_valid;
        CData/*0:0*/ mlp_top__DOT__weight_fifo_u__DOT__clk;
        CData/*0:0*/ mlp_top__DOT__weight_fifo_u__DOT__reset;
        CData/*0:0*/ mlp_top__DOT__weight_fifo_u__DOT__push_col0;
        CData/*0:0*/ mlp_top__DOT__weight_fifo_u__DOT__push_col1;
        CData/*7:0*/ mlp_top__DOT__weight_fifo_u__DOT__data_in;
        CData/*0:0*/ mlp_top__DOT__weight_fifo_u__DOT__pop;
        CData/*7:0*/ mlp_top__DOT__weight_fifo_u__DOT__col0_out;
        CData/*7:0*/ mlp_top__DOT__weight_fifo_u__DOT__col1_out;
        CData/*7:0*/ mlp_top__DOT__weight_fifo_u__DOT__col1_raw;
        CData/*1:0*/ mlp_top__DOT__weight_fifo_u__DOT__wr_ptr0;
        CData/*1:0*/ mlp_top__DOT__weight_fifo_u__DOT__rd_ptr0;
        CData/*1:0*/ mlp_top__DOT__weight_fifo_u__DOT__wr_ptr1;
        CData/*1:0*/ mlp_top__DOT__weight_fifo_u__DOT__rd_ptr1;
        CData/*0:0*/ mlp_top__DOT__ub_a__DOT__clk;
        CData/*0:0*/ mlp_top__DOT__ub_a__DOT__reset;
        CData/*0:0*/ mlp_top__DOT__ub_a__DOT__wr_valid;
        CData/*0:0*/ mlp_top__DOT__ub_a__DOT__wr_ready;
        CData/*0:0*/ mlp_top__DOT__ub_a__DOT__rd_ready;
        CData/*0:0*/ mlp_top__DOT__ub_a__DOT__rd_valid;
        CData/*0:0*/ mlp_top__DOT__ub_a__DOT__full;
        CData/*0:0*/ mlp_top__DOT__ub_a__DOT__empty;
        CData/*4:0*/ mlp_top__DOT__ub_a__DOT__count;
        CData/*3:0*/ mlp_top__DOT__ub_a__DOT__wr_ptr;
        CData/*3:0*/ mlp_top__DOT__ub_a__DOT__rd_ptr;
        CData/*0:0*/ mlp_top__DOT__ub_a__DOT__do_write;
        CData/*0:0*/ mlp_top__DOT__ub_a__DOT__do_read;
        CData/*0:0*/ mlp_top__DOT__ub_b__DOT__clk;
        CData/*0:0*/ mlp_top__DOT__ub_b__DOT__reset;
        CData/*0:0*/ mlp_top__DOT__ub_b__DOT__wr_valid;
        CData/*0:0*/ mlp_top__DOT__ub_b__DOT__wr_ready;
        CData/*0:0*/ mlp_top__DOT__ub_b__DOT__rd_ready;
        CData/*0:0*/ mlp_top__DOT__ub_b__DOT__rd_valid;
        CData/*0:0*/ mlp_top__DOT__ub_b__DOT__full;
        CData/*0:0*/ mlp_top__DOT__ub_b__DOT__empty;
        CData/*4:0*/ mlp_top__DOT__ub_b__DOT__count;
        CData/*3:0*/ mlp_top__DOT__ub_b__DOT__wr_ptr;
        CData/*3:0*/ mlp_top__DOT__ub_b__DOT__rd_ptr;
        CData/*0:0*/ mlp_top__DOT__ub_b__DOT__do_write;
        CData/*0:0*/ mlp_top__DOT__ub_b__DOT__do_read;
        CData/*0:0*/ mlp_top__DOT__mmu_u__DOT__clk;
        CData/*0:0*/ mlp_top__DOT__mmu_u__DOT__reset;
        CData/*0:0*/ mlp_top__DOT__mmu_u__DOT__en_weight_pass;
        CData/*0:0*/ mlp_top__DOT__mmu_u__DOT__en_capture_col0;
        CData/*0:0*/ mlp_top__DOT__mmu_u__DOT__en_capture_col1;
        CData/*7:0*/ mlp_top__DOT__mmu_u__DOT__row0_in;
        CData/*7:0*/ mlp_top__DOT__mmu_u__DOT__row1_in;
        CData/*7:0*/ mlp_top__DOT__mmu_u__DOT__col0_in;
        CData/*7:0*/ mlp_top__DOT__mmu_u__DOT__col1_in;
        CData/*7:0*/ mlp_top__DOT__mmu_u__DOT__pe00_01_act;
        CData/*7:0*/ mlp_top__DOT__mmu_u__DOT__pe10_11_act;
        CData/*0:0*/ mlp_top__DOT__mmu_u__DOT__pe00__DOT__clk;
        CData/*0:0*/ mlp_top__DOT__mmu_u__DOT__pe00__DOT__reset;
        CData/*0:0*/ mlp_top__DOT__mmu_u__DOT__pe00__DOT__en_weight_pass;
        CData/*0:0*/ mlp_top__DOT__mmu_u__DOT__pe00__DOT__en_weight_capture;
        CData/*7:0*/ mlp_top__DOT__mmu_u__DOT__pe00__DOT__in_act;
        CData/*7:0*/ mlp_top__DOT__mmu_u__DOT__pe00__DOT__out_act;
    };
    struct {
        CData/*7:0*/ mlp_top__DOT__mmu_u__DOT__pe00__DOT__weight;
        CData/*0:0*/ mlp_top__DOT__mmu_u__DOT__pe01__DOT__clk;
        CData/*0:0*/ mlp_top__DOT__mmu_u__DOT__pe01__DOT__reset;
        CData/*0:0*/ mlp_top__DOT__mmu_u__DOT__pe01__DOT__en_weight_pass;
        CData/*0:0*/ mlp_top__DOT__mmu_u__DOT__pe01__DOT__en_weight_capture;
        CData/*7:0*/ mlp_top__DOT__mmu_u__DOT__pe01__DOT__in_act;
        CData/*7:0*/ mlp_top__DOT__mmu_u__DOT__pe01__DOT__out_act;
        CData/*7:0*/ mlp_top__DOT__mmu_u__DOT__pe01__DOT__weight;
        CData/*0:0*/ mlp_top__DOT__mmu_u__DOT__pe10__DOT__clk;
        CData/*0:0*/ mlp_top__DOT__mmu_u__DOT__pe10__DOT__reset;
        CData/*0:0*/ mlp_top__DOT__mmu_u__DOT__pe10__DOT__en_weight_pass;
        CData/*0:0*/ mlp_top__DOT__mmu_u__DOT__pe10__DOT__en_weight_capture;
        CData/*7:0*/ mlp_top__DOT__mmu_u__DOT__pe10__DOT__in_act;
        CData/*7:0*/ mlp_top__DOT__mmu_u__DOT__pe10__DOT__out_act;
        CData/*7:0*/ mlp_top__DOT__mmu_u__DOT__pe10__DOT__weight;
        CData/*0:0*/ mlp_top__DOT__mmu_u__DOT__pe11__DOT__clk;
        CData/*0:0*/ mlp_top__DOT__mmu_u__DOT__pe11__DOT__reset;
        CData/*0:0*/ mlp_top__DOT__mmu_u__DOT__pe11__DOT__en_weight_pass;
        CData/*0:0*/ mlp_top__DOT__mmu_u__DOT__pe11__DOT__en_weight_capture;
        CData/*7:0*/ mlp_top__DOT__mmu_u__DOT__pe11__DOT__in_act;
        CData/*7:0*/ mlp_top__DOT__mmu_u__DOT__pe11__DOT__out_act;
        CData/*7:0*/ mlp_top__DOT__mmu_u__DOT__pe11__DOT__weight;
        CData/*0:0*/ mlp_top__DOT__accum_u__DOT__clk;
        CData/*0:0*/ mlp_top__DOT__accum_u__DOT__reset;
        CData/*0:0*/ mlp_top__DOT__accum_u__DOT__valid_in;
        CData/*0:0*/ mlp_top__DOT__accum_u__DOT__accumulator_enable;
        CData/*0:0*/ mlp_top__DOT__accum_u__DOT__addr_sel;
        CData/*0:0*/ mlp_top__DOT__accum_u__DOT__valid_out;
        CData/*0:0*/ mlp_top__DOT__accum_u__DOT__aligned_valid;
        CData/*0:0*/ mlp_top__DOT__accum_u__DOT__u_align__DOT__clk;
        CData/*0:0*/ mlp_top__DOT__accum_u__DOT__u_align__DOT__reset;
        CData/*0:0*/ mlp_top__DOT__accum_u__DOT__u_align__DOT__valid_in;
        CData/*0:0*/ mlp_top__DOT__accum_u__DOT__u_align__DOT__aligned_valid;
        CData/*0:0*/ mlp_top__DOT__accum_u__DOT__u_align__DOT__pending;
        CData/*0:0*/ mlp_top__DOT__accum_u__DOT__u_mem__DOT__clk;
        CData/*0:0*/ mlp_top__DOT__accum_u__DOT__u_mem__DOT__reset;
        CData/*0:0*/ mlp_top__DOT__accum_u__DOT__u_mem__DOT__enable;
        CData/*0:0*/ mlp_top__DOT__accum_u__DOT__u_mem__DOT__accumulator_mode;
        CData/*0:0*/ mlp_top__DOT__accum_u__DOT__u_mem__DOT__buffer_select;
        CData/*0:0*/ mlp_top__DOT__accum_u__DOT__u_mem__DOT__valid_out;
        CData/*0:0*/ mlp_top__DOT__ap_col0__DOT__clk;
        CData/*0:0*/ mlp_top__DOT__ap_col0__DOT__reset;
        CData/*0:0*/ mlp_top__DOT__ap_col0__DOT__valid_in;
        CData/*4:0*/ mlp_top__DOT__ap_col0__DOT__norm_shift;
        CData/*7:0*/ mlp_top__DOT__ap_col0__DOT__q_zero_point;
        CData/*0:0*/ mlp_top__DOT__ap_col0__DOT__valid_out;
        CData/*7:0*/ mlp_top__DOT__ap_col0__DOT__ub_data_out;
        CData/*0:0*/ mlp_top__DOT__ap_col0__DOT__loss_valid;
        CData/*0:0*/ mlp_top__DOT__ap_col0__DOT__s1_valid;
        CData/*0:0*/ mlp_top__DOT__ap_col0__DOT__s2_valid;
        CData/*7:0*/ mlp_top__DOT__ap_col0__DOT__ub_q_reg;
        CData/*0:0*/ mlp_top__DOT__ap_col0__DOT__valid_reg;
        CData/*0:0*/ mlp_top__DOT__ap_col0__DOT__act_u__DOT__clk;
        CData/*0:0*/ mlp_top__DOT__ap_col0__DOT__act_u__DOT__reset;
        CData/*0:0*/ mlp_top__DOT__ap_col0__DOT__act_u__DOT__valid_in;
        CData/*0:0*/ mlp_top__DOT__ap_col0__DOT__act_u__DOT__valid_out;
        CData/*0:0*/ mlp_top__DOT__ap_col0__DOT__norm_u__DOT__clk;
        CData/*0:0*/ mlp_top__DOT__ap_col0__DOT__norm_u__DOT__reset;
        CData/*0:0*/ mlp_top__DOT__ap_col0__DOT__norm_u__DOT__valid_in;
        CData/*4:0*/ mlp_top__DOT__ap_col0__DOT__norm_u__DOT__shift;
        CData/*0:0*/ mlp_top__DOT__ap_col0__DOT__norm_u__DOT__valid_out;
        CData/*0:0*/ mlp_top__DOT__ap_col0__DOT__loss_u__DOT__clk;
        CData/*0:0*/ mlp_top__DOT__ap_col0__DOT__loss_u__DOT__reset;
        CData/*0:0*/ mlp_top__DOT__ap_col0__DOT__loss_u__DOT__valid_in;
    };
    struct {
        CData/*0:0*/ mlp_top__DOT__ap_col0__DOT__loss_u__DOT__valid_out;
        CData/*0:0*/ mlp_top__DOT__ap_col1__DOT__clk;
        CData/*0:0*/ mlp_top__DOT__ap_col1__DOT__reset;
        CData/*0:0*/ mlp_top__DOT__ap_col1__DOT__valid_in;
        CData/*4:0*/ mlp_top__DOT__ap_col1__DOT__norm_shift;
        CData/*7:0*/ mlp_top__DOT__ap_col1__DOT__q_zero_point;
        CData/*0:0*/ mlp_top__DOT__ap_col1__DOT__valid_out;
        CData/*7:0*/ mlp_top__DOT__ap_col1__DOT__ub_data_out;
        CData/*0:0*/ mlp_top__DOT__ap_col1__DOT__loss_valid;
        CData/*0:0*/ mlp_top__DOT__ap_col1__DOT__s1_valid;
        CData/*0:0*/ mlp_top__DOT__ap_col1__DOT__s2_valid;
        CData/*7:0*/ mlp_top__DOT__ap_col1__DOT__ub_q_reg;
        CData/*0:0*/ mlp_top__DOT__ap_col1__DOT__valid_reg;
        CData/*0:0*/ mlp_top__DOT__ap_col1__DOT__act_u__DOT__clk;
        CData/*0:0*/ mlp_top__DOT__ap_col1__DOT__act_u__DOT__reset;
        CData/*0:0*/ mlp_top__DOT__ap_col1__DOT__act_u__DOT__valid_in;
        CData/*0:0*/ mlp_top__DOT__ap_col1__DOT__act_u__DOT__valid_out;
        CData/*0:0*/ mlp_top__DOT__ap_col1__DOT__norm_u__DOT__clk;
        CData/*0:0*/ mlp_top__DOT__ap_col1__DOT__norm_u__DOT__reset;
        CData/*0:0*/ mlp_top__DOT__ap_col1__DOT__norm_u__DOT__valid_in;
        CData/*4:0*/ mlp_top__DOT__ap_col1__DOT__norm_u__DOT__shift;
        CData/*0:0*/ mlp_top__DOT__ap_col1__DOT__norm_u__DOT__valid_out;
        CData/*0:0*/ mlp_top__DOT__ap_col1__DOT__loss_u__DOT__clk;
        CData/*0:0*/ mlp_top__DOT__ap_col1__DOT__loss_u__DOT__reset;
        CData/*0:0*/ mlp_top__DOT__ap_col1__DOT__loss_u__DOT__valid_in;
        CData/*0:0*/ mlp_top__DOT__ap_col1__DOT__loss_u__DOT__valid_out;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mlp_top__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mlp_top__DOT__reset__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mlp_top__DOT__weight_fifo_u__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mlp_top__DOT__weight_fifo_u__DOT__reset__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mlp_top__DOT__ub_a__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mlp_top__DOT__ub_a__DOT__reset__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mlp_top__DOT__ub_b__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mlp_top__DOT__ub_b__DOT__reset__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mlp_top__DOT__mmu_u__DOT__pe00__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mlp_top__DOT__mmu_u__DOT__pe00__DOT__reset__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mlp_top__DOT__mmu_u__DOT__pe01__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mlp_top__DOT__mmu_u__DOT__pe01__DOT__reset__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mlp_top__DOT__mmu_u__DOT__pe10__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mlp_top__DOT__mmu_u__DOT__pe10__DOT__reset__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mlp_top__DOT__mmu_u__DOT__pe11__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mlp_top__DOT__mmu_u__DOT__pe11__DOT__reset__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mlp_top__DOT__accum_u__DOT__u_align__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mlp_top__DOT__accum_u__DOT__u_align__DOT__reset__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mlp_top__DOT__accum_u__DOT__u_mem__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mlp_top__DOT__accum_u__DOT__u_mem__DOT__reset__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mlp_top__DOT__ap_col0__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mlp_top__DOT__ap_col0__DOT__reset__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mlp_top__DOT__ap_col0__DOT__act_u__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mlp_top__DOT__ap_col0__DOT__act_u__DOT__reset__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mlp_top__DOT__ap_col0__DOT__norm_u__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mlp_top__DOT__ap_col0__DOT__norm_u__DOT__reset__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mlp_top__DOT__ap_col0__DOT__loss_u__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mlp_top__DOT__ap_col0__DOT__loss_u__DOT__reset__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mlp_top__DOT__ap_col1__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mlp_top__DOT__ap_col1__DOT__reset__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mlp_top__DOT__ap_col1__DOT__act_u__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mlp_top__DOT__ap_col1__DOT__act_u__DOT__reset__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mlp_top__DOT__ap_col1__DOT__norm_u__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mlp_top__DOT__ap_col1__DOT__norm_u__DOT__reset__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mlp_top__DOT__ap_col1__DOT__loss_u__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__mlp_top__DOT__ap_col1__DOT__loss_u__DOT__reset__0;
    };
    struct {
        VL_IN16(init_act_data,15,0);
        VL_IN16(norm_gain,15,0);
        VL_IN16(q_inv_scale,15,0);
        VL_OUT16(mmu_acc0_out,15,0);
        VL_OUT16(mmu_acc1_out,15,0);
        SData/*15:0*/ mlp_top__DOT__init_act_data;
        SData/*15:0*/ mlp_top__DOT__norm_gain;
        SData/*15:0*/ mlp_top__DOT__q_inv_scale;
        SData/*15:0*/ mlp_top__DOT__mmu_acc0_out;
        SData/*15:0*/ mlp_top__DOT__mmu_acc1_out;
        SData/*15:0*/ mlp_top__DOT__ub_a_wr_data;
        SData/*15:0*/ mlp_top__DOT__ub_a_rd_data;
        SData/*15:0*/ mlp_top__DOT__ub_b_wr_data;
        SData/*15:0*/ mlp_top__DOT__ub_b_rd_data;
        SData/*15:0*/ mlp_top__DOT__act_ub_rd_data;
        SData/*15:0*/ mlp_top__DOT__refill_data;
        SData/*15:0*/ mlp_top__DOT__ub_a__DOT__wr_data;
        SData/*15:0*/ mlp_top__DOT__ub_a__DOT__rd_data;
        SData/*15:0*/ mlp_top__DOT__ub_b__DOT__wr_data;
        SData/*15:0*/ mlp_top__DOT__ub_b__DOT__rd_data;
        SData/*15:0*/ mlp_top__DOT__mmu_u__DOT__acc0_out;
        SData/*15:0*/ mlp_top__DOT__mmu_u__DOT__acc1_out;
        SData/*15:0*/ mlp_top__DOT__mmu_u__DOT__pe00_10_psum;
        SData/*15:0*/ mlp_top__DOT__mmu_u__DOT__pe01_11_psum;
        SData/*15:0*/ mlp_top__DOT__mmu_u__DOT__pe00__DOT__in_psum;
        SData/*15:0*/ mlp_top__DOT__mmu_u__DOT__pe00__DOT__out_psum;
        SData/*15:0*/ mlp_top__DOT__mmu_u__DOT__pe01__DOT__in_psum;
        SData/*15:0*/ mlp_top__DOT__mmu_u__DOT__pe01__DOT__out_psum;
        SData/*15:0*/ mlp_top__DOT__mmu_u__DOT__pe10__DOT__in_psum;
        SData/*15:0*/ mlp_top__DOT__mmu_u__DOT__pe10__DOT__out_psum;
        SData/*15:0*/ mlp_top__DOT__mmu_u__DOT__pe11__DOT__in_psum;
        SData/*15:0*/ mlp_top__DOT__mmu_u__DOT__pe11__DOT__out_psum;
        SData/*15:0*/ mlp_top__DOT__accum_u__DOT__mmu_col0_in;
        SData/*15:0*/ mlp_top__DOT__accum_u__DOT__mmu_col1_in;
        SData/*15:0*/ mlp_top__DOT__accum_u__DOT__aligned_c0;
        SData/*15:0*/ mlp_top__DOT__accum_u__DOT__aligned_c1;
        SData/*15:0*/ mlp_top__DOT__accum_u__DOT__u_align__DOT__raw_col0;
        SData/*15:0*/ mlp_top__DOT__accum_u__DOT__u_align__DOT__raw_col1;
        SData/*15:0*/ mlp_top__DOT__accum_u__DOT__u_align__DOT__align_col0;
        SData/*15:0*/ mlp_top__DOT__accum_u__DOT__u_align__DOT__align_col1;
        SData/*15:0*/ mlp_top__DOT__accum_u__DOT__u_align__DOT__col0_delay_reg;
        SData/*15:0*/ mlp_top__DOT__accum_u__DOT__u_mem__DOT__in_col0;
        SData/*15:0*/ mlp_top__DOT__accum_u__DOT__u_mem__DOT__in_col1;
        SData/*15:0*/ mlp_top__DOT__ap_col0__DOT__norm_gain;
        SData/*15:0*/ mlp_top__DOT__ap_col0__DOT__q_inv_scale;
        SData/*15:0*/ mlp_top__DOT__ap_col0__DOT__norm_u__DOT__gain;
        SData/*15:0*/ mlp_top__DOT__ap_col1__DOT__norm_gain;
        SData/*15:0*/ mlp_top__DOT__ap_col1__DOT__q_inv_scale;
        SData/*15:0*/ mlp_top__DOT__ap_col1__DOT__norm_u__DOT__gain;
        VL_IN(norm_bias,31,0);
        VL_OUT(acc0,31,0);
        VL_OUT(acc1,31,0);
        IData/*31:0*/ mlp_top__DOT__norm_bias;
        IData/*31:0*/ mlp_top__DOT__acc0;
        IData/*31:0*/ mlp_top__DOT__acc1;
        IData/*31:0*/ mlp_top__DOT__accum_u__DOT__acc_col0_out;
        IData/*31:0*/ mlp_top__DOT__accum_u__DOT__acc_col1_out;
        IData/*31:0*/ mlp_top__DOT__accum_u__DOT__u_mem__DOT__out_col0;
        IData/*31:0*/ mlp_top__DOT__accum_u__DOT__u_mem__DOT__out_col1;
        IData/*31:0*/ mlp_top__DOT__accum_u__DOT__u_mem__DOT__mem_buff0_col0;
        IData/*31:0*/ mlp_top__DOT__accum_u__DOT__u_mem__DOT__mem_buff0_col1;
        IData/*31:0*/ mlp_top__DOT__accum_u__DOT__u_mem__DOT__mem_buff1_col0;
        IData/*31:0*/ mlp_top__DOT__accum_u__DOT__u_mem__DOT__mem_buff1_col1;
        IData/*31:0*/ mlp_top__DOT__ap_col0__DOT__acc_in;
    };
    struct {
        IData/*31:0*/ mlp_top__DOT__ap_col0__DOT__target_in;
        IData/*31:0*/ mlp_top__DOT__ap_col0__DOT__norm_bias;
        IData/*31:0*/ mlp_top__DOT__ap_col0__DOT__loss_out;
        IData/*31:0*/ mlp_top__DOT__ap_col0__DOT__s1_data;
        IData/*31:0*/ mlp_top__DOT__ap_col0__DOT__target_d1;
        IData/*31:0*/ mlp_top__DOT__ap_col0__DOT__s2_data;
        IData/*31:0*/ mlp_top__DOT__ap_col0__DOT__scaled;
        IData/*31:0*/ mlp_top__DOT__ap_col0__DOT__biased;
        IData/*31:0*/ mlp_top__DOT__ap_col0__DOT__act_u__DOT__data_in;
        IData/*31:0*/ mlp_top__DOT__ap_col0__DOT__act_u__DOT__data_out;
        IData/*31:0*/ mlp_top__DOT__ap_col0__DOT__norm_u__DOT__data_in;
        IData/*31:0*/ mlp_top__DOT__ap_col0__DOT__norm_u__DOT__bias;
        IData/*31:0*/ mlp_top__DOT__ap_col0__DOT__norm_u__DOT__data_out;
        IData/*31:0*/ mlp_top__DOT__ap_col0__DOT__loss_u__DOT__data_in;
        IData/*31:0*/ mlp_top__DOT__ap_col0__DOT__loss_u__DOT__target_in;
        IData/*31:0*/ mlp_top__DOT__ap_col0__DOT__loss_u__DOT__loss_out;
        IData/*31:0*/ mlp_top__DOT__ap_col0__DOT__loss_u__DOT__diff;
        IData/*31:0*/ mlp_top__DOT__ap_col0__DOT__loss_u__DOT__abs_diff;
        IData/*31:0*/ mlp_top__DOT__ap_col1__DOT__acc_in;
        IData/*31:0*/ mlp_top__DOT__ap_col1__DOT__target_in;
        IData/*31:0*/ mlp_top__DOT__ap_col1__DOT__norm_bias;
        IData/*31:0*/ mlp_top__DOT__ap_col1__DOT__loss_out;
        IData/*31:0*/ mlp_top__DOT__ap_col1__DOT__s1_data;
        IData/*31:0*/ mlp_top__DOT__ap_col1__DOT__target_d1;
        IData/*31:0*/ mlp_top__DOT__ap_col1__DOT__s2_data;
        IData/*31:0*/ mlp_top__DOT__ap_col1__DOT__scaled;
        IData/*31:0*/ mlp_top__DOT__ap_col1__DOT__biased;
        IData/*31:0*/ mlp_top__DOT__ap_col1__DOT__act_u__DOT__data_in;
        IData/*31:0*/ mlp_top__DOT__ap_col1__DOT__act_u__DOT__data_out;
        IData/*31:0*/ mlp_top__DOT__ap_col1__DOT__norm_u__DOT__data_in;
        IData/*31:0*/ mlp_top__DOT__ap_col1__DOT__norm_u__DOT__bias;
        IData/*31:0*/ mlp_top__DOT__ap_col1__DOT__norm_u__DOT__data_out;
        IData/*31:0*/ mlp_top__DOT__ap_col1__DOT__loss_u__DOT__data_in;
        IData/*31:0*/ mlp_top__DOT__ap_col1__DOT__loss_u__DOT__target_in;
        IData/*31:0*/ mlp_top__DOT__ap_col1__DOT__loss_u__DOT__loss_out;
        IData/*31:0*/ mlp_top__DOT__ap_col1__DOT__loss_u__DOT__diff;
        IData/*31:0*/ mlp_top__DOT__ap_col1__DOT__loss_u__DOT__abs_diff;
        IData/*31:0*/ __VactIterCount;
        QData/*47:0*/ mlp_top__DOT__ap_col0__DOT__mult;
        QData/*47:0*/ mlp_top__DOT__ap_col0__DOT__mult_rounded;
        QData/*47:0*/ mlp_top__DOT__ap_col0__DOT__norm_u__DOT__mult;
        QData/*47:0*/ mlp_top__DOT__ap_col0__DOT__norm_u__DOT__shifted;
        QData/*47:0*/ mlp_top__DOT__ap_col1__DOT__mult;
        QData/*47:0*/ mlp_top__DOT__ap_col1__DOT__mult_rounded;
        QData/*47:0*/ mlp_top__DOT__ap_col1__DOT__norm_u__DOT__mult;
        QData/*47:0*/ mlp_top__DOT__ap_col1__DOT__norm_u__DOT__shifted;
        VlUnpacked<CData/*7:0*/, 4> mlp_top__DOT__weight_fifo_u__DOT__queue0;
        VlUnpacked<CData/*7:0*/, 4> mlp_top__DOT__weight_fifo_u__DOT__queue1;
        VlUnpacked<SData/*15:0*/, 16> mlp_top__DOT__ub_a__DOT__mem;
        VlUnpacked<SData/*15:0*/, 16> mlp_top__DOT__ub_b__DOT__mem;
        VlUnpacked<QData/*63:0*/, 1> __VstlTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VicoTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VactTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VnbaTriggered;
    };

    // INTERNAL VARIABLES
    Vtop__Syms* const vlSymsp;

    // PARAMETERS
    static constexpr CData/*3:0*/ mlp_top__DOT__IDLE = 0U;
    static constexpr CData/*3:0*/ mlp_top__DOT__LOAD_WEIGHT = 1U;
    static constexpr CData/*3:0*/ mlp_top__DOT__LOAD_ACT = 2U;
    static constexpr CData/*3:0*/ mlp_top__DOT__COMPUTE = 3U;
    static constexpr CData/*3:0*/ mlp_top__DOT__DRAIN = 4U;
    static constexpr CData/*3:0*/ mlp_top__DOT__TRANSFER = 5U;
    static constexpr CData/*3:0*/ mlp_top__DOT__NEXT_LAYER = 6U;
    static constexpr CData/*3:0*/ mlp_top__DOT__WAIT_WEIGHTS = 7U;
    static constexpr CData/*3:0*/ mlp_top__DOT__DONE = 8U;
    static constexpr CData/*0:0*/ mlp_top__DOT__accum_u__DOT__u_mem__DOT__BYPASS_READ_NEW = 1U;
    static constexpr CData/*1:0*/ mlp_top__DOT__ap_col0__DOT__act_u__DOT__DEFAULT_ACT = 1U;
    static constexpr CData/*1:0*/ mlp_top__DOT__ap_col1__DOT__act_u__DOT__DEFAULT_ACT = 1U;
    static constexpr IData/*31:0*/ mlp_top__DOT__NUM_LAYERS = 2U;
    static constexpr IData/*31:0*/ mlp_top__DOT__ub_a__DOT__WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ mlp_top__DOT__ub_a__DOT__DEPTH = 0x00000010U;
    static constexpr IData/*31:0*/ mlp_top__DOT__ub_a__DOT__ADDR_W = 4U;
    static constexpr IData/*31:0*/ mlp_top__DOT__ub_b__DOT__WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ mlp_top__DOT__ub_b__DOT__DEPTH = 0x00000010U;
    static constexpr IData/*31:0*/ mlp_top__DOT__ub_b__DOT__ADDR_W = 4U;

    // CONSTRUCTORS
    Vtop___024root(Vtop__Syms* symsp, const char* v__name);
    ~Vtop___024root();
    VL_UNCOPYABLE(Vtop___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
