// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Symbol table implementation internals

#include "Vtop__pch.h"
#include "Vtop.h"
#include "Vtop___024root.h"

// FUNCTIONS
Vtop__Syms::~Vtop__Syms()
{

    // Tear down scope hierarchy
    __Vhier.remove(0, &__Vscope_tpu_top);
    __Vhier.remove(&__Vscope_tpu_top, &__Vscope_tpu_top__bridge_u);
    __Vhier.remove(&__Vscope_tpu_top, &__Vscope_tpu_top__mlp_u);
    __Vhier.remove(&__Vscope_tpu_top, &__Vscope_tpu_top__uart_ctrl_u);
    __Vhier.remove(&__Vscope_tpu_top__mlp_u, &__Vscope_tpu_top__mlp_u__accum_u);
    __Vhier.remove(&__Vscope_tpu_top__mlp_u, &__Vscope_tpu_top__mlp_u__ap_col0);
    __Vhier.remove(&__Vscope_tpu_top__mlp_u, &__Vscope_tpu_top__mlp_u__ap_col1);
    __Vhier.remove(&__Vscope_tpu_top__mlp_u, &__Vscope_tpu_top__mlp_u__mmu_u);
    __Vhier.remove(&__Vscope_tpu_top__mlp_u, &__Vscope_tpu_top__mlp_u__ub_a);
    __Vhier.remove(&__Vscope_tpu_top__mlp_u, &__Vscope_tpu_top__mlp_u__ub_b);
    __Vhier.remove(&__Vscope_tpu_top__mlp_u, &__Vscope_tpu_top__mlp_u__weight_fifo_u);
    __Vhier.remove(&__Vscope_tpu_top__mlp_u__accum_u, &__Vscope_tpu_top__mlp_u__accum_u__u_align);
    __Vhier.remove(&__Vscope_tpu_top__mlp_u__accum_u, &__Vscope_tpu_top__mlp_u__accum_u__u_mem);
    __Vhier.remove(&__Vscope_tpu_top__mlp_u__ap_col0, &__Vscope_tpu_top__mlp_u__ap_col0__act_u);
    __Vhier.remove(&__Vscope_tpu_top__mlp_u__ap_col0, &__Vscope_tpu_top__mlp_u__ap_col0__loss_u);
    __Vhier.remove(&__Vscope_tpu_top__mlp_u__ap_col0, &__Vscope_tpu_top__mlp_u__ap_col0__norm_u);
    __Vhier.remove(&__Vscope_tpu_top__mlp_u__ap_col1, &__Vscope_tpu_top__mlp_u__ap_col1__act_u);
    __Vhier.remove(&__Vscope_tpu_top__mlp_u__ap_col1, &__Vscope_tpu_top__mlp_u__ap_col1__loss_u);
    __Vhier.remove(&__Vscope_tpu_top__mlp_u__ap_col1, &__Vscope_tpu_top__mlp_u__ap_col1__norm_u);
    __Vhier.remove(&__Vscope_tpu_top__mlp_u__mmu_u, &__Vscope_tpu_top__mlp_u__mmu_u__pe00);
    __Vhier.remove(&__Vscope_tpu_top__mlp_u__mmu_u, &__Vscope_tpu_top__mlp_u__mmu_u__pe01);
    __Vhier.remove(&__Vscope_tpu_top__mlp_u__mmu_u, &__Vscope_tpu_top__mlp_u__mmu_u__pe10);
    __Vhier.remove(&__Vscope_tpu_top__mlp_u__mmu_u, &__Vscope_tpu_top__mlp_u__mmu_u__pe11);
    __Vhier.remove(&__Vscope_tpu_top__uart_ctrl_u, &__Vscope_tpu_top__uart_ctrl_u__uart_rx_u);
    __Vhier.remove(&__Vscope_tpu_top__uart_ctrl_u, &__Vscope_tpu_top__uart_ctrl_u__uart_tx_u);
    __Vhier.remove(&__Vscope_tpu_top__uart_ctrl_u, &__Vscope_tpu_top__uart_ctrl_u__unnamedblk1);

}

Vtop__Syms::Vtop__Syms(VerilatedContext* contextp, const char* namep, Vtop* modelp)
    : VerilatedSyms{contextp}
    // Setup internal state of the Syms class
    , __Vm_modelp{modelp}
    // Setup module instances
    , TOP{this, namep}
{
    // Check resources
    Verilated::stackCheck(424);
    // Configure time unit / time precision
    _vm_contextp__->timeunit(-9);
    _vm_contextp__->timeprecision(-12);
    // Setup each module's pointers to their submodules
    // Setup each module's pointer back to symbol table (for public functions)
    TOP.__Vconfigure(true);
    // Setup scopes
    __Vscope_TOP.configure(this, name(), "TOP", "TOP", "<null>", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_tpu_top.configure(this, name(), "tpu_top", "tpu_top", "tpu_top", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_tpu_top__bridge_u.configure(this, name(), "tpu_top.bridge_u", "bridge_u", "tpu_bridge", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_tpu_top__mlp_u.configure(this, name(), "tpu_top.mlp_u", "mlp_u", "mlp_top", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_tpu_top__mlp_u__accum_u.configure(this, name(), "tpu_top.mlp_u.accum_u", "accum_u", "accumulator", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_tpu_top__mlp_u__accum_u__u_align.configure(this, name(), "tpu_top.mlp_u.accum_u.u_align", "u_align", "accumulator_align", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_tpu_top__mlp_u__accum_u__u_mem.configure(this, name(), "tpu_top.mlp_u.accum_u.u_mem", "u_mem", "accumulator_mem", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_tpu_top__mlp_u__ap_col0.configure(this, name(), "tpu_top.mlp_u.ap_col0", "ap_col0", "activation_pipeline", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_tpu_top__mlp_u__ap_col0__act_u.configure(this, name(), "tpu_top.mlp_u.ap_col0.act_u", "act_u", "activation_func", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_tpu_top__mlp_u__ap_col0__loss_u.configure(this, name(), "tpu_top.mlp_u.ap_col0.loss_u", "loss_u", "loss_block", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_tpu_top__mlp_u__ap_col0__norm_u.configure(this, name(), "tpu_top.mlp_u.ap_col0.norm_u", "norm_u", "normalizer", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_tpu_top__mlp_u__ap_col1.configure(this, name(), "tpu_top.mlp_u.ap_col1", "ap_col1", "activation_pipeline", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_tpu_top__mlp_u__ap_col1__act_u.configure(this, name(), "tpu_top.mlp_u.ap_col1.act_u", "act_u", "activation_func", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_tpu_top__mlp_u__ap_col1__loss_u.configure(this, name(), "tpu_top.mlp_u.ap_col1.loss_u", "loss_u", "loss_block", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_tpu_top__mlp_u__ap_col1__norm_u.configure(this, name(), "tpu_top.mlp_u.ap_col1.norm_u", "norm_u", "normalizer", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_tpu_top__mlp_u__mmu_u.configure(this, name(), "tpu_top.mlp_u.mmu_u", "mmu_u", "mmu", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_tpu_top__mlp_u__mmu_u__pe00.configure(this, name(), "tpu_top.mlp_u.mmu_u.pe00", "pe00", "pe", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_tpu_top__mlp_u__mmu_u__pe01.configure(this, name(), "tpu_top.mlp_u.mmu_u.pe01", "pe01", "pe", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_tpu_top__mlp_u__mmu_u__pe10.configure(this, name(), "tpu_top.mlp_u.mmu_u.pe10", "pe10", "pe", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_tpu_top__mlp_u__mmu_u__pe11.configure(this, name(), "tpu_top.mlp_u.mmu_u.pe11", "pe11", "pe", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_tpu_top__mlp_u__ub_a.configure(this, name(), "tpu_top.mlp_u.ub_a", "ub_a", "unified_buffer", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_tpu_top__mlp_u__ub_b.configure(this, name(), "tpu_top.mlp_u.ub_b", "ub_b", "unified_buffer", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_tpu_top__mlp_u__weight_fifo_u.configure(this, name(), "tpu_top.mlp_u.weight_fifo_u", "weight_fifo_u", "dual_weight_fifo", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_tpu_top__uart_ctrl_u.configure(this, name(), "tpu_top.uart_ctrl_u", "uart_ctrl_u", "uart_controller", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_tpu_top__uart_ctrl_u__uart_rx_u.configure(this, name(), "tpu_top.uart_ctrl_u.uart_rx_u", "uart_rx_u", "uart_rx", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_tpu_top__uart_ctrl_u__uart_tx_u.configure(this, name(), "tpu_top.uart_ctrl_u.uart_tx_u", "uart_tx_u", "uart_tx", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_tpu_top__uart_ctrl_u__unnamedblk1.configure(this, name(), "tpu_top.uart_ctrl_u.unnamedblk1", "unnamedblk1", "<null>", -9, VerilatedScope::SCOPE_OTHER);

    // Set up scope hierarchy
    __Vhier.add(0, &__Vscope_tpu_top);
    __Vhier.add(&__Vscope_tpu_top, &__Vscope_tpu_top__bridge_u);
    __Vhier.add(&__Vscope_tpu_top, &__Vscope_tpu_top__mlp_u);
    __Vhier.add(&__Vscope_tpu_top, &__Vscope_tpu_top__uart_ctrl_u);
    __Vhier.add(&__Vscope_tpu_top__mlp_u, &__Vscope_tpu_top__mlp_u__accum_u);
    __Vhier.add(&__Vscope_tpu_top__mlp_u, &__Vscope_tpu_top__mlp_u__ap_col0);
    __Vhier.add(&__Vscope_tpu_top__mlp_u, &__Vscope_tpu_top__mlp_u__ap_col1);
    __Vhier.add(&__Vscope_tpu_top__mlp_u, &__Vscope_tpu_top__mlp_u__mmu_u);
    __Vhier.add(&__Vscope_tpu_top__mlp_u, &__Vscope_tpu_top__mlp_u__ub_a);
    __Vhier.add(&__Vscope_tpu_top__mlp_u, &__Vscope_tpu_top__mlp_u__ub_b);
    __Vhier.add(&__Vscope_tpu_top__mlp_u, &__Vscope_tpu_top__mlp_u__weight_fifo_u);
    __Vhier.add(&__Vscope_tpu_top__mlp_u__accum_u, &__Vscope_tpu_top__mlp_u__accum_u__u_align);
    __Vhier.add(&__Vscope_tpu_top__mlp_u__accum_u, &__Vscope_tpu_top__mlp_u__accum_u__u_mem);
    __Vhier.add(&__Vscope_tpu_top__mlp_u__ap_col0, &__Vscope_tpu_top__mlp_u__ap_col0__act_u);
    __Vhier.add(&__Vscope_tpu_top__mlp_u__ap_col0, &__Vscope_tpu_top__mlp_u__ap_col0__loss_u);
    __Vhier.add(&__Vscope_tpu_top__mlp_u__ap_col0, &__Vscope_tpu_top__mlp_u__ap_col0__norm_u);
    __Vhier.add(&__Vscope_tpu_top__mlp_u__ap_col1, &__Vscope_tpu_top__mlp_u__ap_col1__act_u);
    __Vhier.add(&__Vscope_tpu_top__mlp_u__ap_col1, &__Vscope_tpu_top__mlp_u__ap_col1__loss_u);
    __Vhier.add(&__Vscope_tpu_top__mlp_u__ap_col1, &__Vscope_tpu_top__mlp_u__ap_col1__norm_u);
    __Vhier.add(&__Vscope_tpu_top__mlp_u__mmu_u, &__Vscope_tpu_top__mlp_u__mmu_u__pe00);
    __Vhier.add(&__Vscope_tpu_top__mlp_u__mmu_u, &__Vscope_tpu_top__mlp_u__mmu_u__pe01);
    __Vhier.add(&__Vscope_tpu_top__mlp_u__mmu_u, &__Vscope_tpu_top__mlp_u__mmu_u__pe10);
    __Vhier.add(&__Vscope_tpu_top__mlp_u__mmu_u, &__Vscope_tpu_top__mlp_u__mmu_u__pe11);
    __Vhier.add(&__Vscope_tpu_top__uart_ctrl_u, &__Vscope_tpu_top__uart_ctrl_u__uart_rx_u);
    __Vhier.add(&__Vscope_tpu_top__uart_ctrl_u, &__Vscope_tpu_top__uart_ctrl_u__uart_tx_u);
    __Vhier.add(&__Vscope_tpu_top__uart_ctrl_u, &__Vscope_tpu_top__uart_ctrl_u__unnamedblk1);

    // Setup export functions
    for (int __Vfinal = 0; __Vfinal < 2; ++__Vfinal) {
        __Vscope_TOP.varInsert(__Vfinal,"clk", &(TOP.clk), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"rst", &(TOP.rst), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"uart_rx", &(TOP.uart_rx), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"uart_tx", &(TOP.uart_tx), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top.varInsert(__Vfinal,"BAUD_RATE", const_cast<void*>(static_cast<const void*>(&(TOP.tpu_top__DOT__BAUD_RATE))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_tpu_top.varInsert(__Vfinal,"CLOCK_FREQ", const_cast<void*>(static_cast<const void*>(&(TOP.tpu_top__DOT__CLOCK_FREQ))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_tpu_top.varInsert(__Vfinal,"clk", &(TOP.tpu_top__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top.varInsert(__Vfinal,"init_act_data", &(TOP.tpu_top__DOT__init_act_data), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_tpu_top.varInsert(__Vfinal,"init_act_valid", &(TOP.tpu_top__DOT__init_act_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top.varInsert(__Vfinal,"mlp_acc0", &(TOP.tpu_top__DOT__mlp_acc0), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_tpu_top.varInsert(__Vfinal,"mlp_acc0_out", &(TOP.tpu_top__DOT__mlp_acc0_out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_tpu_top.varInsert(__Vfinal,"mlp_acc1", &(TOP.tpu_top__DOT__mlp_acc1), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_tpu_top.varInsert(__Vfinal,"mlp_acc1_out", &(TOP.tpu_top__DOT__mlp_acc1_out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_tpu_top.varInsert(__Vfinal,"mlp_acc_valid", &(TOP.tpu_top__DOT__mlp_acc_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top.varInsert(__Vfinal,"mlp_acc_valid_out", &(TOP.tpu_top__DOT__mlp_acc_valid_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top.varInsert(__Vfinal,"mlp_current_layer", &(TOP.tpu_top__DOT__mlp_current_layer), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_tpu_top.varInsert(__Vfinal,"mlp_current_layer_out", &(TOP.tpu_top__DOT__mlp_current_layer_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_tpu_top.varInsert(__Vfinal,"mlp_cycle_cnt", &(TOP.tpu_top__DOT__mlp_cycle_cnt), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_tpu_top.varInsert(__Vfinal,"mlp_cycle_cnt_out", &(TOP.tpu_top__DOT__mlp_cycle_cnt_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_tpu_top.varInsert(__Vfinal,"mlp_init_act_data", &(TOP.tpu_top__DOT__mlp_init_act_data), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_tpu_top.varInsert(__Vfinal,"mlp_init_act_valid", &(TOP.tpu_top__DOT__mlp_init_act_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top.varInsert(__Vfinal,"mlp_layer_complete", &(TOP.tpu_top__DOT__mlp_layer_complete), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top.varInsert(__Vfinal,"mlp_layer_complete_out", &(TOP.tpu_top__DOT__mlp_layer_complete_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top.varInsert(__Vfinal,"mlp_norm_bias", &(TOP.tpu_top__DOT__mlp_norm_bias), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_tpu_top.varInsert(__Vfinal,"mlp_norm_gain", &(TOP.tpu_top__DOT__mlp_norm_gain), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_tpu_top.varInsert(__Vfinal,"mlp_norm_shift", &(TOP.tpu_top__DOT__mlp_norm_shift), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_tpu_top.varInsert(__Vfinal,"mlp_q_inv_scale", &(TOP.tpu_top__DOT__mlp_q_inv_scale), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_tpu_top.varInsert(__Vfinal,"mlp_q_zero_point", &(TOP.tpu_top__DOT__mlp_q_zero_point), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_tpu_top.varInsert(__Vfinal,"mlp_start_mlp", &(TOP.tpu_top__DOT__mlp_start_mlp), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top.varInsert(__Vfinal,"mlp_state", &(TOP.tpu_top__DOT__mlp_state), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_tpu_top.varInsert(__Vfinal,"mlp_state_out", &(TOP.tpu_top__DOT__mlp_state_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_tpu_top.varInsert(__Vfinal,"mlp_weights_ready", &(TOP.tpu_top__DOT__mlp_weights_ready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top.varInsert(__Vfinal,"mlp_wf_data_in", &(TOP.tpu_top__DOT__mlp_wf_data_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_tpu_top.varInsert(__Vfinal,"mlp_wf_push_col0", &(TOP.tpu_top__DOT__mlp_wf_push_col0), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top.varInsert(__Vfinal,"mlp_wf_push_col1", &(TOP.tpu_top__DOT__mlp_wf_push_col1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top.varInsert(__Vfinal,"mlp_wf_reset", &(TOP.tpu_top__DOT__mlp_wf_reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top.varInsert(__Vfinal,"rst", &(TOP.tpu_top__DOT__rst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top.varInsert(__Vfinal,"start_mlp", &(TOP.tpu_top__DOT__start_mlp), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top.varInsert(__Vfinal,"uart_rx", &(TOP.tpu_top__DOT__uart_rx), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top.varInsert(__Vfinal,"uart_tx", &(TOP.tpu_top__DOT__uart_tx), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top.varInsert(__Vfinal,"weights_ready", &(TOP.tpu_top__DOT__weights_ready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top.varInsert(__Vfinal,"wf_data_in", &(TOP.tpu_top__DOT__wf_data_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_tpu_top.varInsert(__Vfinal,"wf_push_col0", &(TOP.tpu_top__DOT__wf_push_col0), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top.varInsert(__Vfinal,"wf_push_col1", &(TOP.tpu_top__DOT__wf_push_col1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top.varInsert(__Vfinal,"wf_reset", &(TOP.tpu_top__DOT__wf_reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__bridge_u.varInsert(__Vfinal,"clk", &(TOP.tpu_top__DOT__bridge_u__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__bridge_u.varInsert(__Vfinal,"ctrl_init_act_data", &(TOP.tpu_top__DOT__bridge_u__DOT__ctrl_init_act_data), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_tpu_top__bridge_u.varInsert(__Vfinal,"ctrl_init_act_valid", &(TOP.tpu_top__DOT__bridge_u__DOT__ctrl_init_act_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__bridge_u.varInsert(__Vfinal,"ctrl_start_mlp", &(TOP.tpu_top__DOT__bridge_u__DOT__ctrl_start_mlp), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__bridge_u.varInsert(__Vfinal,"ctrl_weights_ready", &(TOP.tpu_top__DOT__bridge_u__DOT__ctrl_weights_ready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__bridge_u.varInsert(__Vfinal,"ctrl_wf_data_in", &(TOP.tpu_top__DOT__bridge_u__DOT__ctrl_wf_data_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_tpu_top__bridge_u.varInsert(__Vfinal,"ctrl_wf_push_col0", &(TOP.tpu_top__DOT__bridge_u__DOT__ctrl_wf_push_col0), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__bridge_u.varInsert(__Vfinal,"ctrl_wf_push_col1", &(TOP.tpu_top__DOT__bridge_u__DOT__ctrl_wf_push_col1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__bridge_u.varInsert(__Vfinal,"ctrl_wf_reset", &(TOP.tpu_top__DOT__bridge_u__DOT__ctrl_wf_reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__bridge_u.varInsert(__Vfinal,"mlp_acc0", &(TOP.tpu_top__DOT__bridge_u__DOT__mlp_acc0), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_tpu_top__bridge_u.varInsert(__Vfinal,"mlp_acc0_in", &(TOP.tpu_top__DOT__bridge_u__DOT__mlp_acc0_in), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_tpu_top__bridge_u.varInsert(__Vfinal,"mlp_acc1", &(TOP.tpu_top__DOT__bridge_u__DOT__mlp_acc1), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_tpu_top__bridge_u.varInsert(__Vfinal,"mlp_acc1_in", &(TOP.tpu_top__DOT__bridge_u__DOT__mlp_acc1_in), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_tpu_top__bridge_u.varInsert(__Vfinal,"mlp_acc_valid", &(TOP.tpu_top__DOT__bridge_u__DOT__mlp_acc_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__bridge_u.varInsert(__Vfinal,"mlp_acc_valid_in", &(TOP.tpu_top__DOT__bridge_u__DOT__mlp_acc_valid_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__bridge_u.varInsert(__Vfinal,"mlp_current_layer", &(TOP.tpu_top__DOT__bridge_u__DOT__mlp_current_layer), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_tpu_top__bridge_u.varInsert(__Vfinal,"mlp_current_layer_in", &(TOP.tpu_top__DOT__bridge_u__DOT__mlp_current_layer_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_tpu_top__bridge_u.varInsert(__Vfinal,"mlp_cycle_cnt", &(TOP.tpu_top__DOT__bridge_u__DOT__mlp_cycle_cnt), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_tpu_top__bridge_u.varInsert(__Vfinal,"mlp_cycle_cnt_in", &(TOP.tpu_top__DOT__bridge_u__DOT__mlp_cycle_cnt_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_tpu_top__bridge_u.varInsert(__Vfinal,"mlp_init_act_data", &(TOP.tpu_top__DOT__bridge_u__DOT__mlp_init_act_data), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_tpu_top__bridge_u.varInsert(__Vfinal,"mlp_init_act_valid", &(TOP.tpu_top__DOT__bridge_u__DOT__mlp_init_act_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__bridge_u.varInsert(__Vfinal,"mlp_layer_complete", &(TOP.tpu_top__DOT__bridge_u__DOT__mlp_layer_complete), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__bridge_u.varInsert(__Vfinal,"mlp_layer_complete_in", &(TOP.tpu_top__DOT__bridge_u__DOT__mlp_layer_complete_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__bridge_u.varInsert(__Vfinal,"mlp_norm_bias", &(TOP.tpu_top__DOT__bridge_u__DOT__mlp_norm_bias), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_tpu_top__bridge_u.varInsert(__Vfinal,"mlp_norm_gain", &(TOP.tpu_top__DOT__bridge_u__DOT__mlp_norm_gain), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_tpu_top__bridge_u.varInsert(__Vfinal,"mlp_norm_shift", &(TOP.tpu_top__DOT__bridge_u__DOT__mlp_norm_shift), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_tpu_top__bridge_u.varInsert(__Vfinal,"mlp_q_inv_scale", &(TOP.tpu_top__DOT__bridge_u__DOT__mlp_q_inv_scale), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_tpu_top__bridge_u.varInsert(__Vfinal,"mlp_q_zero_point", &(TOP.tpu_top__DOT__bridge_u__DOT__mlp_q_zero_point), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_tpu_top__bridge_u.varInsert(__Vfinal,"mlp_start_mlp", &(TOP.tpu_top__DOT__bridge_u__DOT__mlp_start_mlp), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__bridge_u.varInsert(__Vfinal,"mlp_state", &(TOP.tpu_top__DOT__bridge_u__DOT__mlp_state), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_tpu_top__bridge_u.varInsert(__Vfinal,"mlp_state_in", &(TOP.tpu_top__DOT__bridge_u__DOT__mlp_state_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_tpu_top__bridge_u.varInsert(__Vfinal,"mlp_weights_ready", &(TOP.tpu_top__DOT__bridge_u__DOT__mlp_weights_ready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__bridge_u.varInsert(__Vfinal,"mlp_wf_data_in", &(TOP.tpu_top__DOT__bridge_u__DOT__mlp_wf_data_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_tpu_top__bridge_u.varInsert(__Vfinal,"mlp_wf_push_col0", &(TOP.tpu_top__DOT__bridge_u__DOT__mlp_wf_push_col0), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__bridge_u.varInsert(__Vfinal,"mlp_wf_push_col1", &(TOP.tpu_top__DOT__bridge_u__DOT__mlp_wf_push_col1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__bridge_u.varInsert(__Vfinal,"mlp_wf_reset", &(TOP.tpu_top__DOT__bridge_u__DOT__mlp_wf_reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__bridge_u.varInsert(__Vfinal,"reset", &(TOP.tpu_top__DOT__bridge_u__DOT__reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"COMPUTE", const_cast<void*>(static_cast<const void*>(&(TOP.tpu_top__DOT__mlp_u__DOT__COMPUTE))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"DONE", const_cast<void*>(static_cast<const void*>(&(TOP.tpu_top__DOT__mlp_u__DOT__DONE))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"DRAIN", const_cast<void*>(static_cast<const void*>(&(TOP.tpu_top__DOT__mlp_u__DOT__DRAIN))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"IDLE", const_cast<void*>(static_cast<const void*>(&(TOP.tpu_top__DOT__mlp_u__DOT__IDLE))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"LOAD_ACT", const_cast<void*>(static_cast<const void*>(&(TOP.tpu_top__DOT__mlp_u__DOT__LOAD_ACT))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"LOAD_WEIGHT", const_cast<void*>(static_cast<const void*>(&(TOP.tpu_top__DOT__mlp_u__DOT__LOAD_WEIGHT))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"NEXT_LAYER", const_cast<void*>(static_cast<const void*>(&(TOP.tpu_top__DOT__mlp_u__DOT__NEXT_LAYER))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"NUM_LAYERS", const_cast<void*>(static_cast<const void*>(&(TOP.tpu_top__DOT__mlp_u__DOT__NUM_LAYERS))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"TRANSFER", const_cast<void*>(static_cast<const void*>(&(TOP.tpu_top__DOT__mlp_u__DOT__TRANSFER))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"WAIT_WEIGHTS", const_cast<void*>(static_cast<const void*>(&(TOP.tpu_top__DOT__mlp_u__DOT__WAIT_WEIGHTS))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"acc0", &(TOP.tpu_top__DOT__mlp_u__DOT__acc0), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"acc1", &(TOP.tpu_top__DOT__mlp_u__DOT__acc1), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"acc_valid", &(TOP.tpu_top__DOT__mlp_u__DOT__acc_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"accum_en", &(TOP.tpu_top__DOT__mlp_u__DOT__accum_en), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"act_row0_data", &(TOP.tpu_top__DOT__mlp_u__DOT__act_row0_data), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"act_row1_data", &(TOP.tpu_top__DOT__mlp_u__DOT__act_row1_data), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"act_ub_empty", &(TOP.tpu_top__DOT__mlp_u__DOT__act_ub_empty), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"act_ub_rd_data", &(TOP.tpu_top__DOT__mlp_u__DOT__act_ub_rd_data), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"act_ub_rd_valid", &(TOP.tpu_top__DOT__mlp_u__DOT__act_ub_rd_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"addr_sel", &(TOP.tpu_top__DOT__mlp_u__DOT__addr_sel), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"ap_data_col0", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_data_col0), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"ap_data_col1", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_data_col1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"ap_valid", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"buffer_select", &(TOP.tpu_top__DOT__mlp_u__DOT__buffer_select), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"clk", &(TOP.tpu_top__DOT__mlp_u__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"compute_phase", &(TOP.tpu_top__DOT__mlp_u__DOT__compute_phase), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"current_layer", &(TOP.tpu_top__DOT__mlp_u__DOT__current_layer), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"current_layer_reg", &(TOP.tpu_top__DOT__mlp_u__DOT__current_layer_reg), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"cycle_cnt", &(TOP.tpu_top__DOT__mlp_u__DOT__cycle_cnt), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"cycle_cnt_reg", &(TOP.tpu_top__DOT__mlp_u__DOT__cycle_cnt_reg), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"drain_phase", &(TOP.tpu_top__DOT__mlp_u__DOT__drain_phase), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"en_capture_col0", &(TOP.tpu_top__DOT__mlp_u__DOT__en_capture_col0), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"en_capture_col1", &(TOP.tpu_top__DOT__mlp_u__DOT__en_capture_col1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"en_load_weight", &(TOP.tpu_top__DOT__mlp_u__DOT__en_load_weight), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"init_act_data", &(TOP.tpu_top__DOT__mlp_u__DOT__init_act_data), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"init_act_valid", &(TOP.tpu_top__DOT__mlp_u__DOT__init_act_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"layer_complete", &(TOP.tpu_top__DOT__mlp_u__DOT__layer_complete), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"mmu_acc0_out", &(TOP.tpu_top__DOT__mlp_u__DOT__mmu_acc0_out), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"mmu_acc1_out", &(TOP.tpu_top__DOT__mlp_u__DOT__mmu_acc1_out), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"mmu_col0_in", &(TOP.tpu_top__DOT__mlp_u__DOT__mmu_col0_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"mmu_col1_in", &(TOP.tpu_top__DOT__mlp_u__DOT__mmu_col1_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"mmu_row0_in", &(TOP.tpu_top__DOT__mlp_u__DOT__mmu_row0_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"mmu_row1_in", &(TOP.tpu_top__DOT__mlp_u__DOT__mmu_row1_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"mmu_valid", &(TOP.tpu_top__DOT__mlp_u__DOT__mmu_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"norm_bias", &(TOP.tpu_top__DOT__mlp_u__DOT__norm_bias), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"norm_gain", &(TOP.tpu_top__DOT__mlp_u__DOT__norm_gain), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"norm_shift", &(TOP.tpu_top__DOT__mlp_u__DOT__norm_shift), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"q_inv_scale", &(TOP.tpu_top__DOT__mlp_u__DOT__q_inv_scale), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"q_zero_point", &(TOP.tpu_top__DOT__mlp_u__DOT__q_zero_point), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"refill_data", &(TOP.tpu_top__DOT__mlp_u__DOT__refill_data), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"refill_valid", &(TOP.tpu_top__DOT__mlp_u__DOT__refill_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"reset", &(TOP.tpu_top__DOT__mlp_u__DOT__reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"row1_skew_reg", &(TOP.tpu_top__DOT__mlp_u__DOT__row1_skew_reg), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"start_mlp", &(TOP.tpu_top__DOT__mlp_u__DOT__start_mlp), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"state", &(TOP.tpu_top__DOT__mlp_u__DOT__state), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"state_reg", &(TOP.tpu_top__DOT__mlp_u__DOT__state_reg), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"transfer_phase", &(TOP.tpu_top__DOT__mlp_u__DOT__transfer_phase), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"ub_a_empty", &(TOP.tpu_top__DOT__mlp_u__DOT__ub_a_empty), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"ub_a_rd_data", &(TOP.tpu_top__DOT__mlp_u__DOT__ub_a_rd_data), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"ub_a_rd_ready", &(TOP.tpu_top__DOT__mlp_u__DOT__ub_a_rd_ready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"ub_a_rd_valid", &(TOP.tpu_top__DOT__mlp_u__DOT__ub_a_rd_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"ub_a_wr_data", &(TOP.tpu_top__DOT__mlp_u__DOT__ub_a_wr_data), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"ub_a_wr_ready", &(TOP.tpu_top__DOT__mlp_u__DOT__ub_a_wr_ready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"ub_a_wr_valid", &(TOP.tpu_top__DOT__mlp_u__DOT__ub_a_wr_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"ub_b_empty", &(TOP.tpu_top__DOT__mlp_u__DOT__ub_b_empty), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"ub_b_rd_data", &(TOP.tpu_top__DOT__mlp_u__DOT__ub_b_rd_data), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"ub_b_rd_ready", &(TOP.tpu_top__DOT__mlp_u__DOT__ub_b_rd_ready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"ub_b_rd_valid", &(TOP.tpu_top__DOT__mlp_u__DOT__ub_b_rd_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"ub_b_wr_data", &(TOP.tpu_top__DOT__mlp_u__DOT__ub_b_wr_data), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"ub_b_wr_ready", &(TOP.tpu_top__DOT__mlp_u__DOT__ub_b_wr_ready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"ub_b_wr_valid", &(TOP.tpu_top__DOT__mlp_u__DOT__ub_b_wr_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"weights_loaded", &(TOP.tpu_top__DOT__mlp_u__DOT__weights_loaded), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"weights_ready", &(TOP.tpu_top__DOT__mlp_u__DOT__weights_ready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"wf_col0_out", &(TOP.tpu_top__DOT__mlp_u__DOT__wf_col0_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"wf_col1_out", &(TOP.tpu_top__DOT__mlp_u__DOT__wf_col1_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"wf_col1_raw", &(TOP.tpu_top__DOT__mlp_u__DOT__wf_col1_raw), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"wf_data_in", &(TOP.tpu_top__DOT__mlp_u__DOT__wf_data_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"wf_push_col0", &(TOP.tpu_top__DOT__mlp_u__DOT__wf_push_col0), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"wf_push_col1", &(TOP.tpu_top__DOT__mlp_u__DOT__wf_push_col1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u.varInsert(__Vfinal,"wf_reset", &(TOP.tpu_top__DOT__mlp_u__DOT__wf_reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__accum_u.varInsert(__Vfinal,"acc_col0_out", &(TOP.tpu_top__DOT__mlp_u__DOT__accum_u__DOT__acc_col0_out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_tpu_top__mlp_u__accum_u.varInsert(__Vfinal,"acc_col1_out", &(TOP.tpu_top__DOT__mlp_u__DOT__accum_u__DOT__acc_col1_out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_tpu_top__mlp_u__accum_u.varInsert(__Vfinal,"accumulator_enable", &(TOP.tpu_top__DOT__mlp_u__DOT__accum_u__DOT__accumulator_enable), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__accum_u.varInsert(__Vfinal,"addr_sel", &(TOP.tpu_top__DOT__mlp_u__DOT__accum_u__DOT__addr_sel), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__accum_u.varInsert(__Vfinal,"aligned_c0", &(TOP.tpu_top__DOT__mlp_u__DOT__accum_u__DOT__aligned_c0), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_tpu_top__mlp_u__accum_u.varInsert(__Vfinal,"aligned_c1", &(TOP.tpu_top__DOT__mlp_u__DOT__accum_u__DOT__aligned_c1), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_tpu_top__mlp_u__accum_u.varInsert(__Vfinal,"aligned_valid", &(TOP.tpu_top__DOT__mlp_u__DOT__accum_u__DOT__aligned_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__accum_u.varInsert(__Vfinal,"clk", &(TOP.tpu_top__DOT__mlp_u__DOT__accum_u__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__accum_u.varInsert(__Vfinal,"mmu_col0_in", &(TOP.tpu_top__DOT__mlp_u__DOT__accum_u__DOT__mmu_col0_in), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_tpu_top__mlp_u__accum_u.varInsert(__Vfinal,"mmu_col1_in", &(TOP.tpu_top__DOT__mlp_u__DOT__accum_u__DOT__mmu_col1_in), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_tpu_top__mlp_u__accum_u.varInsert(__Vfinal,"reset", &(TOP.tpu_top__DOT__mlp_u__DOT__accum_u__DOT__reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__accum_u.varInsert(__Vfinal,"valid_in", &(TOP.tpu_top__DOT__mlp_u__DOT__accum_u__DOT__valid_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__accum_u.varInsert(__Vfinal,"valid_out", &(TOP.tpu_top__DOT__mlp_u__DOT__accum_u__DOT__valid_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__accum_u__u_align.varInsert(__Vfinal,"align_col0", &(TOP.tpu_top__DOT__mlp_u__DOT__accum_u__DOT__u_align__DOT__align_col0), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_tpu_top__mlp_u__accum_u__u_align.varInsert(__Vfinal,"align_col1", &(TOP.tpu_top__DOT__mlp_u__DOT__accum_u__DOT__u_align__DOT__align_col1), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_tpu_top__mlp_u__accum_u__u_align.varInsert(__Vfinal,"aligned_valid", &(TOP.tpu_top__DOT__mlp_u__DOT__accum_u__DOT__u_align__DOT__aligned_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__accum_u__u_align.varInsert(__Vfinal,"clk", &(TOP.tpu_top__DOT__mlp_u__DOT__accum_u__DOT__u_align__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__accum_u__u_align.varInsert(__Vfinal,"col0_delay_reg", &(TOP.tpu_top__DOT__mlp_u__DOT__accum_u__DOT__u_align__DOT__col0_delay_reg), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_tpu_top__mlp_u__accum_u__u_align.varInsert(__Vfinal,"pending", &(TOP.tpu_top__DOT__mlp_u__DOT__accum_u__DOT__u_align__DOT__pending), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__accum_u__u_align.varInsert(__Vfinal,"raw_col0", &(TOP.tpu_top__DOT__mlp_u__DOT__accum_u__DOT__u_align__DOT__raw_col0), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_tpu_top__mlp_u__accum_u__u_align.varInsert(__Vfinal,"raw_col1", &(TOP.tpu_top__DOT__mlp_u__DOT__accum_u__DOT__u_align__DOT__raw_col1), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_tpu_top__mlp_u__accum_u__u_align.varInsert(__Vfinal,"reset", &(TOP.tpu_top__DOT__mlp_u__DOT__accum_u__DOT__u_align__DOT__reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__accum_u__u_align.varInsert(__Vfinal,"valid_in", &(TOP.tpu_top__DOT__mlp_u__DOT__accum_u__DOT__u_align__DOT__valid_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__accum_u__u_mem.varInsert(__Vfinal,"BYPASS_READ_NEW", const_cast<void*>(static_cast<const void*>(&(TOP.tpu_top__DOT__mlp_u__DOT__accum_u__DOT__u_mem__DOT__BYPASS_READ_NEW))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,0);
        __Vscope_tpu_top__mlp_u__accum_u__u_mem.varInsert(__Vfinal,"accumulator_mode", &(TOP.tpu_top__DOT__mlp_u__DOT__accum_u__DOT__u_mem__DOT__accumulator_mode), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__accum_u__u_mem.varInsert(__Vfinal,"buffer_select", &(TOP.tpu_top__DOT__mlp_u__DOT__accum_u__DOT__u_mem__DOT__buffer_select), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__accum_u__u_mem.varInsert(__Vfinal,"clk", &(TOP.tpu_top__DOT__mlp_u__DOT__accum_u__DOT__u_mem__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__accum_u__u_mem.varInsert(__Vfinal,"enable", &(TOP.tpu_top__DOT__mlp_u__DOT__accum_u__DOT__u_mem__DOT__enable), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__accum_u__u_mem.varInsert(__Vfinal,"in_col0", &(TOP.tpu_top__DOT__mlp_u__DOT__accum_u__DOT__u_mem__DOT__in_col0), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_tpu_top__mlp_u__accum_u__u_mem.varInsert(__Vfinal,"in_col1", &(TOP.tpu_top__DOT__mlp_u__DOT__accum_u__DOT__u_mem__DOT__in_col1), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_tpu_top__mlp_u__accum_u__u_mem.varInsert(__Vfinal,"mem_buff0_col0", &(TOP.tpu_top__DOT__mlp_u__DOT__accum_u__DOT__u_mem__DOT__mem_buff0_col0), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_tpu_top__mlp_u__accum_u__u_mem.varInsert(__Vfinal,"mem_buff0_col1", &(TOP.tpu_top__DOT__mlp_u__DOT__accum_u__DOT__u_mem__DOT__mem_buff0_col1), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_tpu_top__mlp_u__accum_u__u_mem.varInsert(__Vfinal,"mem_buff1_col0", &(TOP.tpu_top__DOT__mlp_u__DOT__accum_u__DOT__u_mem__DOT__mem_buff1_col0), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_tpu_top__mlp_u__accum_u__u_mem.varInsert(__Vfinal,"mem_buff1_col1", &(TOP.tpu_top__DOT__mlp_u__DOT__accum_u__DOT__u_mem__DOT__mem_buff1_col1), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_tpu_top__mlp_u__accum_u__u_mem.varInsert(__Vfinal,"out_col0", &(TOP.tpu_top__DOT__mlp_u__DOT__accum_u__DOT__u_mem__DOT__out_col0), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_tpu_top__mlp_u__accum_u__u_mem.varInsert(__Vfinal,"out_col1", &(TOP.tpu_top__DOT__mlp_u__DOT__accum_u__DOT__u_mem__DOT__out_col1), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_tpu_top__mlp_u__accum_u__u_mem.varInsert(__Vfinal,"reset", &(TOP.tpu_top__DOT__mlp_u__DOT__accum_u__DOT__u_mem__DOT__reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__accum_u__u_mem.varInsert(__Vfinal,"valid_out", &(TOP.tpu_top__DOT__mlp_u__DOT__accum_u__DOT__u_mem__DOT__valid_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__ap_col0.varInsert(__Vfinal,"acc_in", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col0__DOT__acc_in), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_tpu_top__mlp_u__ap_col0.varInsert(__Vfinal,"biased", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col0__DOT__biased), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_tpu_top__mlp_u__ap_col0.varInsert(__Vfinal,"clk", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col0__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__ap_col0.varInsert(__Vfinal,"loss_out", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col0__DOT__loss_out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_tpu_top__mlp_u__ap_col0.varInsert(__Vfinal,"loss_valid", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col0__DOT__loss_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__ap_col0.varInsert(__Vfinal,"mult", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col0__DOT__mult), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,0,1 ,47,0);
        __Vscope_tpu_top__mlp_u__ap_col0.varInsert(__Vfinal,"mult_rounded", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col0__DOT__mult_rounded), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,0,1 ,47,0);
        __Vscope_tpu_top__mlp_u__ap_col0.varInsert(__Vfinal,"norm_bias", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col0__DOT__norm_bias), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_tpu_top__mlp_u__ap_col0.varInsert(__Vfinal,"norm_gain", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col0__DOT__norm_gain), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_tpu_top__mlp_u__ap_col0.varInsert(__Vfinal,"norm_shift", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col0__DOT__norm_shift), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_tpu_top__mlp_u__ap_col0.varInsert(__Vfinal,"q_inv_scale", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col0__DOT__q_inv_scale), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_tpu_top__mlp_u__ap_col0.varInsert(__Vfinal,"q_zero_point", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col0__DOT__q_zero_point), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_tpu_top__mlp_u__ap_col0.varInsert(__Vfinal,"reset", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col0__DOT__reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__ap_col0.varInsert(__Vfinal,"s1_data", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col0__DOT__s1_data), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_tpu_top__mlp_u__ap_col0.varInsert(__Vfinal,"s1_valid", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col0__DOT__s1_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__ap_col0.varInsert(__Vfinal,"s2_data", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col0__DOT__s2_data), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_tpu_top__mlp_u__ap_col0.varInsert(__Vfinal,"s2_valid", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col0__DOT__s2_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__ap_col0.varInsert(__Vfinal,"scaled", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col0__DOT__scaled), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_tpu_top__mlp_u__ap_col0.varInsert(__Vfinal,"target_d1", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col0__DOT__target_d1), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_tpu_top__mlp_u__ap_col0.varInsert(__Vfinal,"target_in", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col0__DOT__target_in), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_tpu_top__mlp_u__ap_col0.varInsert(__Vfinal,"ub_data_out", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col0__DOT__ub_data_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_tpu_top__mlp_u__ap_col0.varInsert(__Vfinal,"ub_q_reg", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col0__DOT__ub_q_reg), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_tpu_top__mlp_u__ap_col0.varInsert(__Vfinal,"valid_in", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col0__DOT__valid_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__ap_col0.varInsert(__Vfinal,"valid_out", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col0__DOT__valid_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__ap_col0.varInsert(__Vfinal,"valid_reg", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col0__DOT__valid_reg), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__ap_col0__act_u.varInsert(__Vfinal,"DEFAULT_ACT", const_cast<void*>(static_cast<const void*>(&(TOP.tpu_top__DOT__mlp_u__DOT__ap_col0__DOT__act_u__DOT__DEFAULT_ACT))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_tpu_top__mlp_u__ap_col0__act_u.varInsert(__Vfinal,"clk", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col0__DOT__act_u__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__ap_col0__act_u.varInsert(__Vfinal,"data_in", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col0__DOT__act_u__DOT__data_in), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_tpu_top__mlp_u__ap_col0__act_u.varInsert(__Vfinal,"data_out", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col0__DOT__act_u__DOT__data_out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_tpu_top__mlp_u__ap_col0__act_u.varInsert(__Vfinal,"reset", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col0__DOT__act_u__DOT__reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__ap_col0__act_u.varInsert(__Vfinal,"valid_in", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col0__DOT__act_u__DOT__valid_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__ap_col0__act_u.varInsert(__Vfinal,"valid_out", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col0__DOT__act_u__DOT__valid_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__ap_col0__loss_u.varInsert(__Vfinal,"abs_diff", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col0__DOT__loss_u__DOT__abs_diff), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_tpu_top__mlp_u__ap_col0__loss_u.varInsert(__Vfinal,"clk", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col0__DOT__loss_u__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__ap_col0__loss_u.varInsert(__Vfinal,"data_in", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col0__DOT__loss_u__DOT__data_in), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_tpu_top__mlp_u__ap_col0__loss_u.varInsert(__Vfinal,"diff", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col0__DOT__loss_u__DOT__diff), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_tpu_top__mlp_u__ap_col0__loss_u.varInsert(__Vfinal,"loss_out", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col0__DOT__loss_u__DOT__loss_out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_tpu_top__mlp_u__ap_col0__loss_u.varInsert(__Vfinal,"reset", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col0__DOT__loss_u__DOT__reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__ap_col0__loss_u.varInsert(__Vfinal,"target_in", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col0__DOT__loss_u__DOT__target_in), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_tpu_top__mlp_u__ap_col0__loss_u.varInsert(__Vfinal,"valid_in", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col0__DOT__loss_u__DOT__valid_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__ap_col0__loss_u.varInsert(__Vfinal,"valid_out", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col0__DOT__loss_u__DOT__valid_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__ap_col0__norm_u.varInsert(__Vfinal,"bias", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col0__DOT__norm_u__DOT__bias), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_tpu_top__mlp_u__ap_col0__norm_u.varInsert(__Vfinal,"clk", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col0__DOT__norm_u__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__ap_col0__norm_u.varInsert(__Vfinal,"data_in", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col0__DOT__norm_u__DOT__data_in), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_tpu_top__mlp_u__ap_col0__norm_u.varInsert(__Vfinal,"data_out", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col0__DOT__norm_u__DOT__data_out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_tpu_top__mlp_u__ap_col0__norm_u.varInsert(__Vfinal,"gain", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col0__DOT__norm_u__DOT__gain), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_tpu_top__mlp_u__ap_col0__norm_u.varInsert(__Vfinal,"mult", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col0__DOT__norm_u__DOT__mult), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,0,1 ,47,0);
        __Vscope_tpu_top__mlp_u__ap_col0__norm_u.varInsert(__Vfinal,"reset", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col0__DOT__norm_u__DOT__reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__ap_col0__norm_u.varInsert(__Vfinal,"shift", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col0__DOT__norm_u__DOT__shift), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_tpu_top__mlp_u__ap_col0__norm_u.varInsert(__Vfinal,"shifted", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col0__DOT__norm_u__DOT__shifted), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,0,1 ,47,0);
        __Vscope_tpu_top__mlp_u__ap_col0__norm_u.varInsert(__Vfinal,"valid_in", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col0__DOT__norm_u__DOT__valid_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__ap_col0__norm_u.varInsert(__Vfinal,"valid_out", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col0__DOT__norm_u__DOT__valid_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__ap_col1.varInsert(__Vfinal,"acc_in", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col1__DOT__acc_in), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_tpu_top__mlp_u__ap_col1.varInsert(__Vfinal,"biased", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col1__DOT__biased), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_tpu_top__mlp_u__ap_col1.varInsert(__Vfinal,"clk", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col1__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__ap_col1.varInsert(__Vfinal,"loss_out", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col1__DOT__loss_out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_tpu_top__mlp_u__ap_col1.varInsert(__Vfinal,"loss_valid", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col1__DOT__loss_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__ap_col1.varInsert(__Vfinal,"mult", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col1__DOT__mult), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,0,1 ,47,0);
        __Vscope_tpu_top__mlp_u__ap_col1.varInsert(__Vfinal,"mult_rounded", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col1__DOT__mult_rounded), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,0,1 ,47,0);
        __Vscope_tpu_top__mlp_u__ap_col1.varInsert(__Vfinal,"norm_bias", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col1__DOT__norm_bias), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_tpu_top__mlp_u__ap_col1.varInsert(__Vfinal,"norm_gain", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col1__DOT__norm_gain), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_tpu_top__mlp_u__ap_col1.varInsert(__Vfinal,"norm_shift", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col1__DOT__norm_shift), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_tpu_top__mlp_u__ap_col1.varInsert(__Vfinal,"q_inv_scale", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col1__DOT__q_inv_scale), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_tpu_top__mlp_u__ap_col1.varInsert(__Vfinal,"q_zero_point", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col1__DOT__q_zero_point), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_tpu_top__mlp_u__ap_col1.varInsert(__Vfinal,"reset", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col1__DOT__reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__ap_col1.varInsert(__Vfinal,"s1_data", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col1__DOT__s1_data), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_tpu_top__mlp_u__ap_col1.varInsert(__Vfinal,"s1_valid", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col1__DOT__s1_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__ap_col1.varInsert(__Vfinal,"s2_data", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col1__DOT__s2_data), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_tpu_top__mlp_u__ap_col1.varInsert(__Vfinal,"s2_valid", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col1__DOT__s2_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__ap_col1.varInsert(__Vfinal,"scaled", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col1__DOT__scaled), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_tpu_top__mlp_u__ap_col1.varInsert(__Vfinal,"target_d1", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col1__DOT__target_d1), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_tpu_top__mlp_u__ap_col1.varInsert(__Vfinal,"target_in", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col1__DOT__target_in), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_tpu_top__mlp_u__ap_col1.varInsert(__Vfinal,"ub_data_out", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col1__DOT__ub_data_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_tpu_top__mlp_u__ap_col1.varInsert(__Vfinal,"ub_q_reg", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col1__DOT__ub_q_reg), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_tpu_top__mlp_u__ap_col1.varInsert(__Vfinal,"valid_in", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col1__DOT__valid_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__ap_col1.varInsert(__Vfinal,"valid_out", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col1__DOT__valid_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__ap_col1.varInsert(__Vfinal,"valid_reg", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col1__DOT__valid_reg), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__ap_col1__act_u.varInsert(__Vfinal,"DEFAULT_ACT", const_cast<void*>(static_cast<const void*>(&(TOP.tpu_top__DOT__mlp_u__DOT__ap_col1__DOT__act_u__DOT__DEFAULT_ACT))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_tpu_top__mlp_u__ap_col1__act_u.varInsert(__Vfinal,"clk", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col1__DOT__act_u__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__ap_col1__act_u.varInsert(__Vfinal,"data_in", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col1__DOT__act_u__DOT__data_in), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_tpu_top__mlp_u__ap_col1__act_u.varInsert(__Vfinal,"data_out", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col1__DOT__act_u__DOT__data_out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_tpu_top__mlp_u__ap_col1__act_u.varInsert(__Vfinal,"reset", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col1__DOT__act_u__DOT__reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__ap_col1__act_u.varInsert(__Vfinal,"valid_in", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col1__DOT__act_u__DOT__valid_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__ap_col1__act_u.varInsert(__Vfinal,"valid_out", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col1__DOT__act_u__DOT__valid_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__ap_col1__loss_u.varInsert(__Vfinal,"abs_diff", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col1__DOT__loss_u__DOT__abs_diff), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_tpu_top__mlp_u__ap_col1__loss_u.varInsert(__Vfinal,"clk", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col1__DOT__loss_u__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__ap_col1__loss_u.varInsert(__Vfinal,"data_in", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col1__DOT__loss_u__DOT__data_in), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_tpu_top__mlp_u__ap_col1__loss_u.varInsert(__Vfinal,"diff", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col1__DOT__loss_u__DOT__diff), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_tpu_top__mlp_u__ap_col1__loss_u.varInsert(__Vfinal,"loss_out", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col1__DOT__loss_u__DOT__loss_out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_tpu_top__mlp_u__ap_col1__loss_u.varInsert(__Vfinal,"reset", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col1__DOT__loss_u__DOT__reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__ap_col1__loss_u.varInsert(__Vfinal,"target_in", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col1__DOT__loss_u__DOT__target_in), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_tpu_top__mlp_u__ap_col1__loss_u.varInsert(__Vfinal,"valid_in", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col1__DOT__loss_u__DOT__valid_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__ap_col1__loss_u.varInsert(__Vfinal,"valid_out", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col1__DOT__loss_u__DOT__valid_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__ap_col1__norm_u.varInsert(__Vfinal,"bias", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col1__DOT__norm_u__DOT__bias), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_tpu_top__mlp_u__ap_col1__norm_u.varInsert(__Vfinal,"clk", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col1__DOT__norm_u__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__ap_col1__norm_u.varInsert(__Vfinal,"data_in", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col1__DOT__norm_u__DOT__data_in), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_tpu_top__mlp_u__ap_col1__norm_u.varInsert(__Vfinal,"data_out", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col1__DOT__norm_u__DOT__data_out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_tpu_top__mlp_u__ap_col1__norm_u.varInsert(__Vfinal,"gain", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col1__DOT__norm_u__DOT__gain), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_tpu_top__mlp_u__ap_col1__norm_u.varInsert(__Vfinal,"mult", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col1__DOT__norm_u__DOT__mult), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,0,1 ,47,0);
        __Vscope_tpu_top__mlp_u__ap_col1__norm_u.varInsert(__Vfinal,"reset", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col1__DOT__norm_u__DOT__reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__ap_col1__norm_u.varInsert(__Vfinal,"shift", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col1__DOT__norm_u__DOT__shift), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_tpu_top__mlp_u__ap_col1__norm_u.varInsert(__Vfinal,"shifted", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col1__DOT__norm_u__DOT__shifted), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,0,1 ,47,0);
        __Vscope_tpu_top__mlp_u__ap_col1__norm_u.varInsert(__Vfinal,"valid_in", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col1__DOT__norm_u__DOT__valid_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__ap_col1__norm_u.varInsert(__Vfinal,"valid_out", &(TOP.tpu_top__DOT__mlp_u__DOT__ap_col1__DOT__norm_u__DOT__valid_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__mmu_u.varInsert(__Vfinal,"acc0_out", &(TOP.tpu_top__DOT__mlp_u__DOT__mmu_u__DOT__acc0_out), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_tpu_top__mlp_u__mmu_u.varInsert(__Vfinal,"acc1_out", &(TOP.tpu_top__DOT__mlp_u__DOT__mmu_u__DOT__acc1_out), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_tpu_top__mlp_u__mmu_u.varInsert(__Vfinal,"clk", &(TOP.tpu_top__DOT__mlp_u__DOT__mmu_u__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__mmu_u.varInsert(__Vfinal,"col0_in", &(TOP.tpu_top__DOT__mlp_u__DOT__mmu_u__DOT__col0_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_tpu_top__mlp_u__mmu_u.varInsert(__Vfinal,"col1_in", &(TOP.tpu_top__DOT__mlp_u__DOT__mmu_u__DOT__col1_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_tpu_top__mlp_u__mmu_u.varInsert(__Vfinal,"en_capture_col0", &(TOP.tpu_top__DOT__mlp_u__DOT__mmu_u__DOT__en_capture_col0), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__mmu_u.varInsert(__Vfinal,"en_capture_col1", &(TOP.tpu_top__DOT__mlp_u__DOT__mmu_u__DOT__en_capture_col1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__mmu_u.varInsert(__Vfinal,"en_weight_pass", &(TOP.tpu_top__DOT__mlp_u__DOT__mmu_u__DOT__en_weight_pass), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__mmu_u.varInsert(__Vfinal,"pe00_01_act", &(TOP.tpu_top__DOT__mlp_u__DOT__mmu_u__DOT__pe00_01_act), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_tpu_top__mlp_u__mmu_u.varInsert(__Vfinal,"pe00_10_psum", &(TOP.tpu_top__DOT__mlp_u__DOT__mmu_u__DOT__pe00_10_psum), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_tpu_top__mlp_u__mmu_u.varInsert(__Vfinal,"pe01_11_psum", &(TOP.tpu_top__DOT__mlp_u__DOT__mmu_u__DOT__pe01_11_psum), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_tpu_top__mlp_u__mmu_u.varInsert(__Vfinal,"pe10_11_act", &(TOP.tpu_top__DOT__mlp_u__DOT__mmu_u__DOT__pe10_11_act), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_tpu_top__mlp_u__mmu_u.varInsert(__Vfinal,"reset", &(TOP.tpu_top__DOT__mlp_u__DOT__mmu_u__DOT__reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__mmu_u.varInsert(__Vfinal,"row0_in", &(TOP.tpu_top__DOT__mlp_u__DOT__mmu_u__DOT__row0_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_tpu_top__mlp_u__mmu_u.varInsert(__Vfinal,"row1_in", &(TOP.tpu_top__DOT__mlp_u__DOT__mmu_u__DOT__row1_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_tpu_top__mlp_u__mmu_u__pe00.varInsert(__Vfinal,"clk", &(TOP.tpu_top__DOT__mlp_u__DOT__mmu_u__DOT__pe00__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__mmu_u__pe00.varInsert(__Vfinal,"en_weight_capture", &(TOP.tpu_top__DOT__mlp_u__DOT__mmu_u__DOT__pe00__DOT__en_weight_capture), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__mmu_u__pe00.varInsert(__Vfinal,"en_weight_pass", &(TOP.tpu_top__DOT__mlp_u__DOT__mmu_u__DOT__pe00__DOT__en_weight_pass), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__mmu_u__pe00.varInsert(__Vfinal,"in_act", &(TOP.tpu_top__DOT__mlp_u__DOT__mmu_u__DOT__pe00__DOT__in_act), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_tpu_top__mlp_u__mmu_u__pe00.varInsert(__Vfinal,"in_psum", &(TOP.tpu_top__DOT__mlp_u__DOT__mmu_u__DOT__pe00__DOT__in_psum), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_tpu_top__mlp_u__mmu_u__pe00.varInsert(__Vfinal,"out_act", &(TOP.tpu_top__DOT__mlp_u__DOT__mmu_u__DOT__pe00__DOT__out_act), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_tpu_top__mlp_u__mmu_u__pe00.varInsert(__Vfinal,"out_psum", &(TOP.tpu_top__DOT__mlp_u__DOT__mmu_u__DOT__pe00__DOT__out_psum), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_tpu_top__mlp_u__mmu_u__pe00.varInsert(__Vfinal,"reset", &(TOP.tpu_top__DOT__mlp_u__DOT__mmu_u__DOT__pe00__DOT__reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__mmu_u__pe00.varInsert(__Vfinal,"weight", &(TOP.tpu_top__DOT__mlp_u__DOT__mmu_u__DOT__pe00__DOT__weight), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_tpu_top__mlp_u__mmu_u__pe01.varInsert(__Vfinal,"clk", &(TOP.tpu_top__DOT__mlp_u__DOT__mmu_u__DOT__pe01__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__mmu_u__pe01.varInsert(__Vfinal,"en_weight_capture", &(TOP.tpu_top__DOT__mlp_u__DOT__mmu_u__DOT__pe01__DOT__en_weight_capture), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__mmu_u__pe01.varInsert(__Vfinal,"en_weight_pass", &(TOP.tpu_top__DOT__mlp_u__DOT__mmu_u__DOT__pe01__DOT__en_weight_pass), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__mmu_u__pe01.varInsert(__Vfinal,"in_act", &(TOP.tpu_top__DOT__mlp_u__DOT__mmu_u__DOT__pe01__DOT__in_act), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_tpu_top__mlp_u__mmu_u__pe01.varInsert(__Vfinal,"in_psum", &(TOP.tpu_top__DOT__mlp_u__DOT__mmu_u__DOT__pe01__DOT__in_psum), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_tpu_top__mlp_u__mmu_u__pe01.varInsert(__Vfinal,"out_act", &(TOP.tpu_top__DOT__mlp_u__DOT__mmu_u__DOT__pe01__DOT__out_act), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_tpu_top__mlp_u__mmu_u__pe01.varInsert(__Vfinal,"out_psum", &(TOP.tpu_top__DOT__mlp_u__DOT__mmu_u__DOT__pe01__DOT__out_psum), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_tpu_top__mlp_u__mmu_u__pe01.varInsert(__Vfinal,"reset", &(TOP.tpu_top__DOT__mlp_u__DOT__mmu_u__DOT__pe01__DOT__reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__mmu_u__pe01.varInsert(__Vfinal,"weight", &(TOP.tpu_top__DOT__mlp_u__DOT__mmu_u__DOT__pe01__DOT__weight), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_tpu_top__mlp_u__mmu_u__pe10.varInsert(__Vfinal,"clk", &(TOP.tpu_top__DOT__mlp_u__DOT__mmu_u__DOT__pe10__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__mmu_u__pe10.varInsert(__Vfinal,"en_weight_capture", &(TOP.tpu_top__DOT__mlp_u__DOT__mmu_u__DOT__pe10__DOT__en_weight_capture), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__mmu_u__pe10.varInsert(__Vfinal,"en_weight_pass", &(TOP.tpu_top__DOT__mlp_u__DOT__mmu_u__DOT__pe10__DOT__en_weight_pass), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__mmu_u__pe10.varInsert(__Vfinal,"in_act", &(TOP.tpu_top__DOT__mlp_u__DOT__mmu_u__DOT__pe10__DOT__in_act), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_tpu_top__mlp_u__mmu_u__pe10.varInsert(__Vfinal,"in_psum", &(TOP.tpu_top__DOT__mlp_u__DOT__mmu_u__DOT__pe10__DOT__in_psum), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_tpu_top__mlp_u__mmu_u__pe10.varInsert(__Vfinal,"out_act", &(TOP.tpu_top__DOT__mlp_u__DOT__mmu_u__DOT__pe10__DOT__out_act), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_tpu_top__mlp_u__mmu_u__pe10.varInsert(__Vfinal,"out_psum", &(TOP.tpu_top__DOT__mlp_u__DOT__mmu_u__DOT__pe10__DOT__out_psum), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_tpu_top__mlp_u__mmu_u__pe10.varInsert(__Vfinal,"reset", &(TOP.tpu_top__DOT__mlp_u__DOT__mmu_u__DOT__pe10__DOT__reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__mmu_u__pe10.varInsert(__Vfinal,"weight", &(TOP.tpu_top__DOT__mlp_u__DOT__mmu_u__DOT__pe10__DOT__weight), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_tpu_top__mlp_u__mmu_u__pe11.varInsert(__Vfinal,"clk", &(TOP.tpu_top__DOT__mlp_u__DOT__mmu_u__DOT__pe11__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__mmu_u__pe11.varInsert(__Vfinal,"en_weight_capture", &(TOP.tpu_top__DOT__mlp_u__DOT__mmu_u__DOT__pe11__DOT__en_weight_capture), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__mmu_u__pe11.varInsert(__Vfinal,"en_weight_pass", &(TOP.tpu_top__DOT__mlp_u__DOT__mmu_u__DOT__pe11__DOT__en_weight_pass), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__mmu_u__pe11.varInsert(__Vfinal,"in_act", &(TOP.tpu_top__DOT__mlp_u__DOT__mmu_u__DOT__pe11__DOT__in_act), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_tpu_top__mlp_u__mmu_u__pe11.varInsert(__Vfinal,"in_psum", &(TOP.tpu_top__DOT__mlp_u__DOT__mmu_u__DOT__pe11__DOT__in_psum), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_tpu_top__mlp_u__mmu_u__pe11.varInsert(__Vfinal,"out_act", &(TOP.tpu_top__DOT__mlp_u__DOT__mmu_u__DOT__pe11__DOT__out_act), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_tpu_top__mlp_u__mmu_u__pe11.varInsert(__Vfinal,"out_psum", &(TOP.tpu_top__DOT__mlp_u__DOT__mmu_u__DOT__pe11__DOT__out_psum), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_tpu_top__mlp_u__mmu_u__pe11.varInsert(__Vfinal,"reset", &(TOP.tpu_top__DOT__mlp_u__DOT__mmu_u__DOT__pe11__DOT__reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__mmu_u__pe11.varInsert(__Vfinal,"weight", &(TOP.tpu_top__DOT__mlp_u__DOT__mmu_u__DOT__pe11__DOT__weight), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_tpu_top__mlp_u__ub_a.varInsert(__Vfinal,"ADDR_W", const_cast<void*>(static_cast<const void*>(&(TOP.tpu_top__DOT__mlp_u__DOT__ub_a__DOT__ADDR_W))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_tpu_top__mlp_u__ub_a.varInsert(__Vfinal,"DEPTH", const_cast<void*>(static_cast<const void*>(&(TOP.tpu_top__DOT__mlp_u__DOT__ub_a__DOT__DEPTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_tpu_top__mlp_u__ub_a.varInsert(__Vfinal,"WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.tpu_top__DOT__mlp_u__DOT__ub_a__DOT__WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_tpu_top__mlp_u__ub_a.varInsert(__Vfinal,"clk", &(TOP.tpu_top__DOT__mlp_u__DOT__ub_a__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__ub_a.varInsert(__Vfinal,"count", &(TOP.tpu_top__DOT__mlp_u__DOT__ub_a__DOT__count), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_tpu_top__mlp_u__ub_a.varInsert(__Vfinal,"do_read", &(TOP.tpu_top__DOT__mlp_u__DOT__ub_a__DOT__do_read), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__ub_a.varInsert(__Vfinal,"do_write", &(TOP.tpu_top__DOT__mlp_u__DOT__ub_a__DOT__do_write), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__ub_a.varInsert(__Vfinal,"empty", &(TOP.tpu_top__DOT__mlp_u__DOT__ub_a__DOT__empty), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__ub_a.varInsert(__Vfinal,"full", &(TOP.tpu_top__DOT__mlp_u__DOT__ub_a__DOT__full), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__ub_a.varInsert(__Vfinal,"mem", &(TOP.tpu_top__DOT__mlp_u__DOT__ub_a__DOT__mem), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1,1 ,0,15 ,15,0);
        __Vscope_tpu_top__mlp_u__ub_a.varInsert(__Vfinal,"rd_data", &(TOP.tpu_top__DOT__mlp_u__DOT__ub_a__DOT__rd_data), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_tpu_top__mlp_u__ub_a.varInsert(__Vfinal,"rd_ptr", &(TOP.tpu_top__DOT__mlp_u__DOT__ub_a__DOT__rd_ptr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_tpu_top__mlp_u__ub_a.varInsert(__Vfinal,"rd_ready", &(TOP.tpu_top__DOT__mlp_u__DOT__ub_a__DOT__rd_ready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__ub_a.varInsert(__Vfinal,"rd_valid", &(TOP.tpu_top__DOT__mlp_u__DOT__ub_a__DOT__rd_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__ub_a.varInsert(__Vfinal,"reset", &(TOP.tpu_top__DOT__mlp_u__DOT__ub_a__DOT__reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__ub_a.varInsert(__Vfinal,"wr_data", &(TOP.tpu_top__DOT__mlp_u__DOT__ub_a__DOT__wr_data), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_tpu_top__mlp_u__ub_a.varInsert(__Vfinal,"wr_ptr", &(TOP.tpu_top__DOT__mlp_u__DOT__ub_a__DOT__wr_ptr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_tpu_top__mlp_u__ub_a.varInsert(__Vfinal,"wr_ready", &(TOP.tpu_top__DOT__mlp_u__DOT__ub_a__DOT__wr_ready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__ub_a.varInsert(__Vfinal,"wr_valid", &(TOP.tpu_top__DOT__mlp_u__DOT__ub_a__DOT__wr_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__ub_b.varInsert(__Vfinal,"ADDR_W", const_cast<void*>(static_cast<const void*>(&(TOP.tpu_top__DOT__mlp_u__DOT__ub_b__DOT__ADDR_W))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_tpu_top__mlp_u__ub_b.varInsert(__Vfinal,"DEPTH", const_cast<void*>(static_cast<const void*>(&(TOP.tpu_top__DOT__mlp_u__DOT__ub_b__DOT__DEPTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_tpu_top__mlp_u__ub_b.varInsert(__Vfinal,"WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.tpu_top__DOT__mlp_u__DOT__ub_b__DOT__WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_tpu_top__mlp_u__ub_b.varInsert(__Vfinal,"clk", &(TOP.tpu_top__DOT__mlp_u__DOT__ub_b__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__ub_b.varInsert(__Vfinal,"count", &(TOP.tpu_top__DOT__mlp_u__DOT__ub_b__DOT__count), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_tpu_top__mlp_u__ub_b.varInsert(__Vfinal,"do_read", &(TOP.tpu_top__DOT__mlp_u__DOT__ub_b__DOT__do_read), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__ub_b.varInsert(__Vfinal,"do_write", &(TOP.tpu_top__DOT__mlp_u__DOT__ub_b__DOT__do_write), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__ub_b.varInsert(__Vfinal,"empty", &(TOP.tpu_top__DOT__mlp_u__DOT__ub_b__DOT__empty), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__ub_b.varInsert(__Vfinal,"full", &(TOP.tpu_top__DOT__mlp_u__DOT__ub_b__DOT__full), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__ub_b.varInsert(__Vfinal,"mem", &(TOP.tpu_top__DOT__mlp_u__DOT__ub_b__DOT__mem), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1,1 ,0,15 ,15,0);
        __Vscope_tpu_top__mlp_u__ub_b.varInsert(__Vfinal,"rd_data", &(TOP.tpu_top__DOT__mlp_u__DOT__ub_b__DOT__rd_data), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_tpu_top__mlp_u__ub_b.varInsert(__Vfinal,"rd_ptr", &(TOP.tpu_top__DOT__mlp_u__DOT__ub_b__DOT__rd_ptr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_tpu_top__mlp_u__ub_b.varInsert(__Vfinal,"rd_ready", &(TOP.tpu_top__DOT__mlp_u__DOT__ub_b__DOT__rd_ready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__ub_b.varInsert(__Vfinal,"rd_valid", &(TOP.tpu_top__DOT__mlp_u__DOT__ub_b__DOT__rd_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__ub_b.varInsert(__Vfinal,"reset", &(TOP.tpu_top__DOT__mlp_u__DOT__ub_b__DOT__reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__ub_b.varInsert(__Vfinal,"wr_data", &(TOP.tpu_top__DOT__mlp_u__DOT__ub_b__DOT__wr_data), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_tpu_top__mlp_u__ub_b.varInsert(__Vfinal,"wr_ptr", &(TOP.tpu_top__DOT__mlp_u__DOT__ub_b__DOT__wr_ptr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_tpu_top__mlp_u__ub_b.varInsert(__Vfinal,"wr_ready", &(TOP.tpu_top__DOT__mlp_u__DOT__ub_b__DOT__wr_ready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__ub_b.varInsert(__Vfinal,"wr_valid", &(TOP.tpu_top__DOT__mlp_u__DOT__ub_b__DOT__wr_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__weight_fifo_u.varInsert(__Vfinal,"clk", &(TOP.tpu_top__DOT__mlp_u__DOT__weight_fifo_u__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__weight_fifo_u.varInsert(__Vfinal,"col0_out", &(TOP.tpu_top__DOT__mlp_u__DOT__weight_fifo_u__DOT__col0_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_tpu_top__mlp_u__weight_fifo_u.varInsert(__Vfinal,"col1_out", &(TOP.tpu_top__DOT__mlp_u__DOT__weight_fifo_u__DOT__col1_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_tpu_top__mlp_u__weight_fifo_u.varInsert(__Vfinal,"col1_raw", &(TOP.tpu_top__DOT__mlp_u__DOT__weight_fifo_u__DOT__col1_raw), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_tpu_top__mlp_u__weight_fifo_u.varInsert(__Vfinal,"data_in", &(TOP.tpu_top__DOT__mlp_u__DOT__weight_fifo_u__DOT__data_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_tpu_top__mlp_u__weight_fifo_u.varInsert(__Vfinal,"pop", &(TOP.tpu_top__DOT__mlp_u__DOT__weight_fifo_u__DOT__pop), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__weight_fifo_u.varInsert(__Vfinal,"push_col0", &(TOP.tpu_top__DOT__mlp_u__DOT__weight_fifo_u__DOT__push_col0), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__weight_fifo_u.varInsert(__Vfinal,"push_col1", &(TOP.tpu_top__DOT__mlp_u__DOT__weight_fifo_u__DOT__push_col1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__weight_fifo_u.varInsert(__Vfinal,"queue0", &(TOP.tpu_top__DOT__mlp_u__DOT__weight_fifo_u__DOT__queue0), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1,1 ,0,3 ,7,0);
        __Vscope_tpu_top__mlp_u__weight_fifo_u.varInsert(__Vfinal,"queue1", &(TOP.tpu_top__DOT__mlp_u__DOT__weight_fifo_u__DOT__queue1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1,1 ,0,3 ,7,0);
        __Vscope_tpu_top__mlp_u__weight_fifo_u.varInsert(__Vfinal,"rd_ptr0", &(TOP.tpu_top__DOT__mlp_u__DOT__weight_fifo_u__DOT__rd_ptr0), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_tpu_top__mlp_u__weight_fifo_u.varInsert(__Vfinal,"rd_ptr1", &(TOP.tpu_top__DOT__mlp_u__DOT__weight_fifo_u__DOT__rd_ptr1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_tpu_top__mlp_u__weight_fifo_u.varInsert(__Vfinal,"reset", &(TOP.tpu_top__DOT__mlp_u__DOT__weight_fifo_u__DOT__reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__mlp_u__weight_fifo_u.varInsert(__Vfinal,"wr_ptr0", &(TOP.tpu_top__DOT__mlp_u__DOT__weight_fifo_u__DOT__wr_ptr0), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_tpu_top__mlp_u__weight_fifo_u.varInsert(__Vfinal,"wr_ptr1", &(TOP.tpu_top__DOT__mlp_u__DOT__weight_fifo_u__DOT__wr_ptr1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_tpu_top__uart_ctrl_u.varInsert(__Vfinal,"BAUD_RATE", const_cast<void*>(static_cast<const void*>(&(TOP.tpu_top__DOT__uart_ctrl_u__DOT__BAUD_RATE))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_tpu_top__uart_ctrl_u.varInsert(__Vfinal,"CLOCK_FREQ", const_cast<void*>(static_cast<const void*>(&(TOP.tpu_top__DOT__uart_ctrl_u__DOT__CLOCK_FREQ))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_tpu_top__uart_ctrl_u.varInsert(__Vfinal,"CMD_EXECUTE", const_cast<void*>(static_cast<const void*>(&(TOP.tpu_top__DOT__uart_ctrl_u__DOT__CMD_EXECUTE))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_tpu_top__uart_ctrl_u.varInsert(__Vfinal,"CMD_READ_RESULT", const_cast<void*>(static_cast<const void*>(&(TOP.tpu_top__DOT__uart_ctrl_u__DOT__CMD_READ_RESULT))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_tpu_top__uart_ctrl_u.varInsert(__Vfinal,"CMD_STATUS", const_cast<void*>(static_cast<const void*>(&(TOP.tpu_top__DOT__uart_ctrl_u__DOT__CMD_STATUS))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_tpu_top__uart_ctrl_u.varInsert(__Vfinal,"CMD_WRITE_ACT", const_cast<void*>(static_cast<const void*>(&(TOP.tpu_top__DOT__uart_ctrl_u__DOT__CMD_WRITE_ACT))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_tpu_top__uart_ctrl_u.varInsert(__Vfinal,"CMD_WRITE_WEIGHT", const_cast<void*>(static_cast<const void*>(&(TOP.tpu_top__DOT__uart_ctrl_u__DOT__CMD_WRITE_WEIGHT))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_tpu_top__uart_ctrl_u.varInsert(__Vfinal,"act_seq_idx", &(TOP.tpu_top__DOT__uart_ctrl_u__DOT__act_seq_idx), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_tpu_top__uart_ctrl_u.varInsert(__Vfinal,"byte_count", &(TOP.tpu_top__DOT__uart_ctrl_u__DOT__byte_count), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_tpu_top__uart_ctrl_u.varInsert(__Vfinal,"byte_sent", &(TOP.tpu_top__DOT__uart_ctrl_u__DOT__byte_sent), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__uart_ctrl_u.varInsert(__Vfinal,"clk", &(TOP.tpu_top__DOT__uart_ctrl_u__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__uart_ctrl_u.varInsert(__Vfinal,"cmd_reg", &(TOP.tpu_top__DOT__uart_ctrl_u__DOT__cmd_reg), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_tpu_top__uart_ctrl_u.varInsert(__Vfinal,"data_buffer", &(TOP.tpu_top__DOT__uart_ctrl_u__DOT__data_buffer), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1,1 ,0,3 ,7,0);
        __Vscope_tpu_top__uart_ctrl_u.varInsert(__Vfinal,"init_act_data", &(TOP.tpu_top__DOT__uart_ctrl_u__DOT__init_act_data), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_tpu_top__uart_ctrl_u.varInsert(__Vfinal,"init_act_data_reg", &(TOP.tpu_top__DOT__uart_ctrl_u__DOT__init_act_data_reg), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_tpu_top__uart_ctrl_u.varInsert(__Vfinal,"init_act_valid", &(TOP.tpu_top__DOT__uart_ctrl_u__DOT__init_act_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__uart_ctrl_u.varInsert(__Vfinal,"init_act_valid_reg", &(TOP.tpu_top__DOT__uart_ctrl_u__DOT__init_act_valid_reg), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__uart_ctrl_u.varInsert(__Vfinal,"mlp_acc0", &(TOP.tpu_top__DOT__uart_ctrl_u__DOT__mlp_acc0), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_tpu_top__uart_ctrl_u.varInsert(__Vfinal,"mlp_acc1", &(TOP.tpu_top__DOT__uart_ctrl_u__DOT__mlp_acc1), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_tpu_top__uart_ctrl_u.varInsert(__Vfinal,"mlp_acc_valid", &(TOP.tpu_top__DOT__uart_ctrl_u__DOT__mlp_acc_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__uart_ctrl_u.varInsert(__Vfinal,"mlp_current_layer", &(TOP.tpu_top__DOT__uart_ctrl_u__DOT__mlp_current_layer), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_tpu_top__uart_ctrl_u.varInsert(__Vfinal,"mlp_cycle_cnt", &(TOP.tpu_top__DOT__uart_ctrl_u__DOT__mlp_cycle_cnt), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_tpu_top__uart_ctrl_u.varInsert(__Vfinal,"mlp_layer_complete", &(TOP.tpu_top__DOT__uart_ctrl_u__DOT__mlp_layer_complete), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__uart_ctrl_u.varInsert(__Vfinal,"mlp_state", &(TOP.tpu_top__DOT__uart_ctrl_u__DOT__mlp_state), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_tpu_top__uart_ctrl_u.varInsert(__Vfinal,"resp_buffer", &(TOP.tpu_top__DOT__uart_ctrl_u__DOT__resp_buffer), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1,1 ,0,3 ,7,0);
        __Vscope_tpu_top__uart_ctrl_u.varInsert(__Vfinal,"resp_byte_idx", &(TOP.tpu_top__DOT__uart_ctrl_u__DOT__resp_byte_idx), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_tpu_top__uart_ctrl_u.varInsert(__Vfinal,"resp_delay_count", &(TOP.tpu_top__DOT__uart_ctrl_u__DOT__resp_delay_count), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_tpu_top__uart_ctrl_u.varInsert(__Vfinal,"rst", &(TOP.tpu_top__DOT__uart_ctrl_u__DOT__rst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__uart_ctrl_u.varInsert(__Vfinal,"rx_data", &(TOP.tpu_top__DOT__uart_ctrl_u__DOT__rx_data), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_tpu_top__uart_ctrl_u.varInsert(__Vfinal,"rx_ready", &(TOP.tpu_top__DOT__uart_ctrl_u__DOT__rx_ready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__uart_ctrl_u.varInsert(__Vfinal,"rx_valid", &(TOP.tpu_top__DOT__uart_ctrl_u__DOT__rx_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__uart_ctrl_u.varInsert(__Vfinal,"start_mlp", &(TOP.tpu_top__DOT__uart_ctrl_u__DOT__start_mlp), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__uart_ctrl_u.varInsert(__Vfinal,"start_mlp_reg", &(TOP.tpu_top__DOT__uart_ctrl_u__DOT__start_mlp_reg), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__uart_ctrl_u.varInsert(__Vfinal,"state", &(TOP.tpu_top__DOT__uart_ctrl_u__DOT__state), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_tpu_top__uart_ctrl_u.varInsert(__Vfinal,"tx_data", &(TOP.tpu_top__DOT__uart_ctrl_u__DOT__tx_data), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_tpu_top__uart_ctrl_u.varInsert(__Vfinal,"tx_data_reg", &(TOP.tpu_top__DOT__uart_ctrl_u__DOT__tx_data_reg), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_tpu_top__uart_ctrl_u.varInsert(__Vfinal,"tx_ready", &(TOP.tpu_top__DOT__uart_ctrl_u__DOT__tx_ready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__uart_ctrl_u.varInsert(__Vfinal,"tx_valid", &(TOP.tpu_top__DOT__uart_ctrl_u__DOT__tx_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__uart_ctrl_u.varInsert(__Vfinal,"tx_valid_reg", &(TOP.tpu_top__DOT__uart_ctrl_u__DOT__tx_valid_reg), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__uart_ctrl_u.varInsert(__Vfinal,"uart_rx", &(TOP.tpu_top__DOT__uart_ctrl_u__DOT__uart_rx), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__uart_ctrl_u.varInsert(__Vfinal,"uart_tx", &(TOP.tpu_top__DOT__uart_ctrl_u__DOT__uart_tx), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__uart_ctrl_u.varInsert(__Vfinal,"weight_seq_idx", &(TOP.tpu_top__DOT__uart_ctrl_u__DOT__weight_seq_idx), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_tpu_top__uart_ctrl_u.varInsert(__Vfinal,"weights_ready", &(TOP.tpu_top__DOT__uart_ctrl_u__DOT__weights_ready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__uart_ctrl_u.varInsert(__Vfinal,"weights_ready_reg", &(TOP.tpu_top__DOT__uart_ctrl_u__DOT__weights_ready_reg), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__uart_ctrl_u.varInsert(__Vfinal,"wf_data_in", &(TOP.tpu_top__DOT__uart_ctrl_u__DOT__wf_data_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_tpu_top__uart_ctrl_u.varInsert(__Vfinal,"wf_data_in_reg", &(TOP.tpu_top__DOT__uart_ctrl_u__DOT__wf_data_in_reg), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_tpu_top__uart_ctrl_u.varInsert(__Vfinal,"wf_push_col0", &(TOP.tpu_top__DOT__uart_ctrl_u__DOT__wf_push_col0), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__uart_ctrl_u.varInsert(__Vfinal,"wf_push_col0_reg", &(TOP.tpu_top__DOT__uart_ctrl_u__DOT__wf_push_col0_reg), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__uart_ctrl_u.varInsert(__Vfinal,"wf_push_col1", &(TOP.tpu_top__DOT__uart_ctrl_u__DOT__wf_push_col1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__uart_ctrl_u.varInsert(__Vfinal,"wf_push_col1_reg", &(TOP.tpu_top__DOT__uart_ctrl_u__DOT__wf_push_col1_reg), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__uart_ctrl_u.varInsert(__Vfinal,"wf_reset", &(TOP.tpu_top__DOT__uart_ctrl_u__DOT__wf_reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__uart_ctrl_u.varInsert(__Vfinal,"wf_reset_reg", &(TOP.tpu_top__DOT__uart_ctrl_u__DOT__wf_reset_reg), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__uart_ctrl_u__uart_rx_u.varInsert(__Vfinal,"BAUD_RATE", const_cast<void*>(static_cast<const void*>(&(TOP.tpu_top__DOT__uart_ctrl_u__DOT__uart_rx_u__DOT__BAUD_RATE))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_tpu_top__uart_ctrl_u__uart_rx_u.varInsert(__Vfinal,"CLKS_PER_BIT", const_cast<void*>(static_cast<const void*>(&(TOP.tpu_top__DOT__uart_ctrl_u__DOT__uart_rx_u__DOT__CLKS_PER_BIT))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_tpu_top__uart_ctrl_u__uart_rx_u.varInsert(__Vfinal,"CLOCK_FREQ", const_cast<void*>(static_cast<const void*>(&(TOP.tpu_top__DOT__uart_ctrl_u__DOT__uart_rx_u__DOT__CLOCK_FREQ))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_tpu_top__uart_ctrl_u__uart_rx_u.varInsert(__Vfinal,"HALF_BIT", const_cast<void*>(static_cast<const void*>(&(TOP.tpu_top__DOT__uart_ctrl_u__DOT__uart_rx_u__DOT__HALF_BIT))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_tpu_top__uart_ctrl_u__uart_rx_u.varInsert(__Vfinal,"bit_index", &(TOP.tpu_top__DOT__uart_ctrl_u__DOT__uart_rx_u__DOT__bit_index), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_tpu_top__uart_ctrl_u__uart_rx_u.varInsert(__Vfinal,"clk", &(TOP.tpu_top__DOT__uart_ctrl_u__DOT__uart_rx_u__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__uart_ctrl_u__uart_rx_u.varInsert(__Vfinal,"clk_count", &(TOP.tpu_top__DOT__uart_ctrl_u__DOT__uart_rx_u__DOT__clk_count), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_tpu_top__uart_ctrl_u__uart_rx_u.varInsert(__Vfinal,"rst", &(TOP.tpu_top__DOT__uart_ctrl_u__DOT__uart_rx_u__DOT__rst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__uart_ctrl_u__uart_rx_u.varInsert(__Vfinal,"rx", &(TOP.tpu_top__DOT__uart_ctrl_u__DOT__uart_rx_u__DOT__rx), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__uart_ctrl_u__uart_rx_u.varInsert(__Vfinal,"rx_byte", &(TOP.tpu_top__DOT__uart_ctrl_u__DOT__uart_rx_u__DOT__rx_byte), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_tpu_top__uart_ctrl_u__uart_rx_u.varInsert(__Vfinal,"rx_data", &(TOP.tpu_top__DOT__uart_ctrl_u__DOT__uart_rx_u__DOT__rx_data), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_tpu_top__uart_ctrl_u__uart_rx_u.varInsert(__Vfinal,"rx_ready", &(TOP.tpu_top__DOT__uart_ctrl_u__DOT__uart_rx_u__DOT__rx_ready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__uart_ctrl_u__uart_rx_u.varInsert(__Vfinal,"rx_sync_1", &(TOP.tpu_top__DOT__uart_ctrl_u__DOT__uart_rx_u__DOT__rx_sync_1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__uart_ctrl_u__uart_rx_u.varInsert(__Vfinal,"rx_sync_2", &(TOP.tpu_top__DOT__uart_ctrl_u__DOT__uart_rx_u__DOT__rx_sync_2), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__uart_ctrl_u__uart_rx_u.varInsert(__Vfinal,"rx_valid", &(TOP.tpu_top__DOT__uart_ctrl_u__DOT__uart_rx_u__DOT__rx_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__uart_ctrl_u__uart_rx_u.varInsert(__Vfinal,"state", &(TOP.tpu_top__DOT__uart_ctrl_u__DOT__uart_rx_u__DOT__state), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_tpu_top__uart_ctrl_u__uart_tx_u.varInsert(__Vfinal,"BAUD_RATE", const_cast<void*>(static_cast<const void*>(&(TOP.tpu_top__DOT__uart_ctrl_u__DOT__uart_tx_u__DOT__BAUD_RATE))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_tpu_top__uart_ctrl_u__uart_tx_u.varInsert(__Vfinal,"CLKS_PER_BIT", const_cast<void*>(static_cast<const void*>(&(TOP.tpu_top__DOT__uart_ctrl_u__DOT__uart_tx_u__DOT__CLKS_PER_BIT))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_tpu_top__uart_ctrl_u__uart_tx_u.varInsert(__Vfinal,"CLOCK_FREQ", const_cast<void*>(static_cast<const void*>(&(TOP.tpu_top__DOT__uart_ctrl_u__DOT__uart_tx_u__DOT__CLOCK_FREQ))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_tpu_top__uart_ctrl_u__uart_tx_u.varInsert(__Vfinal,"bit_index", &(TOP.tpu_top__DOT__uart_ctrl_u__DOT__uart_tx_u__DOT__bit_index), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_tpu_top__uart_ctrl_u__uart_tx_u.varInsert(__Vfinal,"clk", &(TOP.tpu_top__DOT__uart_ctrl_u__DOT__uart_tx_u__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__uart_ctrl_u__uart_tx_u.varInsert(__Vfinal,"clk_count", &(TOP.tpu_top__DOT__uart_ctrl_u__DOT__uart_tx_u__DOT__clk_count), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_tpu_top__uart_ctrl_u__uart_tx_u.varInsert(__Vfinal,"rst", &(TOP.tpu_top__DOT__uart_ctrl_u__DOT__uart_tx_u__DOT__rst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__uart_ctrl_u__uart_tx_u.varInsert(__Vfinal,"state", &(TOP.tpu_top__DOT__uart_ctrl_u__DOT__uart_tx_u__DOT__state), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_tpu_top__uart_ctrl_u__uart_tx_u.varInsert(__Vfinal,"tx", &(TOP.tpu_top__DOT__uart_ctrl_u__DOT__uart_tx_u__DOT__tx), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__uart_ctrl_u__uart_tx_u.varInsert(__Vfinal,"tx_byte", &(TOP.tpu_top__DOT__uart_ctrl_u__DOT__uart_tx_u__DOT__tx_byte), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_tpu_top__uart_ctrl_u__uart_tx_u.varInsert(__Vfinal,"tx_data", &(TOP.tpu_top__DOT__uart_ctrl_u__DOT__uart_tx_u__DOT__tx_data), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_tpu_top__uart_ctrl_u__uart_tx_u.varInsert(__Vfinal,"tx_ready", &(TOP.tpu_top__DOT__uart_ctrl_u__DOT__uart_tx_u__DOT__tx_ready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__uart_ctrl_u__uart_tx_u.varInsert(__Vfinal,"tx_valid", &(TOP.tpu_top__DOT__uart_ctrl_u__DOT__uart_tx_u__DOT__tx_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_tpu_top__uart_ctrl_u__unnamedblk1.varInsert(__Vfinal,"i", &(TOP.tpu_top__DOT__uart_ctrl_u__DOT__unnamedblk1__DOT__i), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
    }
}
